import {assertMediaImportPermit} from './media-import-policy.mjs'; // 新規取込にはOneDrive確認済みの許可が必要です。
import {mediaAssert,mediaRef,digestBlob,inspectMedia,mediaFilename} from './media-model.mjs'; // メタデータと実ファイルの検査を共用します。
export class MediaStore{ // 写真・動画をSQLiteとは別のアカウント専用OPFS領域へ保管します。
  constructor(scope,storage=globalThis.navigator?.storage){mediaAssert(typeof scope==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(scope),'添付の保存先が不正です。');this.scope=scope;this.storage=storage;this.rootPromise=null;this.closed=false;} // 本人・ゲストの保存先を分離します。
  active(){mediaAssert(!this.closed,'アカウントが切り替わりました。添付を開き直してください。');} // 別アカウントの処理結果を使用しません。
  async root(){this.active();if(!this.rootPromise)this.rootPromise=(async()=>{mediaAssert(this.storage?.getDirectory,'このブラウザでは写真・動画の端末保存が利用できません。');const hash=await digestBlob(new Blob([this.scope]));const base=await(await this.storage.getDirectory()).getDirectoryHandle('.zero-one-practice-media-v1',{create:true});return base.getDirectoryHandle(hash,{create:true});})().catch(error=>{this.rootPromise=null;throw error;});return this.rootPromise;} // 既存SQLiteフォルダーを変更しません。
  async read(name){const root=await this.root();try{return await(await root.getFileHandle(name)).getFile();}catch(error){if(error.name==='NotFoundError')return null;throw error;}} // 未取得と読取エラーを区別します。
  async write(name,blob,checkpoint=()=>{}){this.active();checkpoint();const root=await this.root();this.active();checkpoint();const handle=await root.getFileHandle(name,{create:true});this.active();checkpoint();mediaAssert(typeof handle.createWritable==='function','写真・動画の保存には対応ブラウザへの更新が必要です。練習プランは引き続き利用できます。');const writer=await handle.createWritable();try{this.active();checkpoint();await writer.write(blob);this.active();checkpoint();await writer.close();this.active();checkpoint();}catch(error){try{await writer.abort();}catch{}if(error.name==='QuotaExceededError')throw new Error('端末の空き容量が不足しています。元の写真・動画は削除されていません。');throw error;}} // 新規取込は書込前と確定前にも接続を確認します。
  async get(value){const ref=mediaRef(value);const file=await this.read(mediaFilename(ref));if(!file)return null;mediaAssert(file.size===ref.size&&await digestBlob(file)===ref.hash,'端末の添付ファイルを確認できません。元ファイルを再添付するかOneDriveから取得してください。');this.active();return file.slice(0,file.size,ref.type);} // 読み戻した実体の検査値を照合します。
  async put(blob,value,checkpoint=()=>{}){this.active();checkpoint();const ref=mediaRef(value);mediaAssert(blob.size===ref.size&&await digestBlob(blob)===ref.hash,'添付ファイルの内容が一致しません。');this.active();checkpoint();let existing;try{existing=await this.get(ref);}catch{existing=null;}this.active();checkpoint();if(!existing){await this.write(mediaFilename(ref),blob,checkpoint);mediaAssert(await this.get(ref),'写真・動画の保存を確認できません。');}this.active();checkpoint();return ref;} // 過去ファイルの取得は維持し、新規取込だけ確認処理を引き継ぎます。
  async import(file,permit){const checkpoint=()=>{this.active();assertMediaImportPermit(permit,this.scope);};checkpoint();const ref=await inspectMedia(file);checkpoint();await this.put(file,ref,checkpoint);checkpoint();return ref;} // 許可がない、または途中で接続を失った取込は参照を返しません。
  async receipt(value,next){const ref=mediaRef(value);const name=ref.hash+'.receipt.json';if(next){mediaAssert(typeof next.id==='string'&&typeof next.eTag==='string'&&next.size===ref.size,'添付の送信確認が不正です。');await this.write(name,new Blob([JSON.stringify({id:next.id,eTag:next.eTag,size:next.size})]));return next;}const file=await this.read(name);if(!file||file.size>4000)return null;try{return JSON.parse(await file.text());}catch{return null;}} // 認証トークンや一時URLを保存せず、確認情報だけを保持します。
  close(){this.closed=true;} // 既存の添付ファイルは消さず、新しい要求だけを停止します。
} // アカウント専用保存を閉じます。
