import test from 'node:test'; // ブラウザを起動せず実際のUI関数を検証します。
import assert from 'node:assert/strict'; // 拒否時の副作用と接続済み時の取込を確認します。
import vm from 'node:vm'; // 実際のUI断片を最小の模擬DOMで実行します。
import {readFile} from 'node:fs/promises'; // 未公開ソースのUI断片を読みます。
import {mediaImportAccess,authorizeMediaImport,assertMediaImportPermit} from '../web/media-import-policy.mjs'; // 候補の許可判定をそのまま使います。
import {mediaList,mediaRef,mediaSize,MEDIA_COUNT} from '../web/media-model.mjs'; // 参照検査は模擬しません。
import {MediaStore} from '../web/media-store.mjs'; // 保存層の取込制限も使います。
const fragment=await readFile(new URL('./media-ui.fixture.mjs',import.meta.url),'utf8'); // ビルドと同じUI関数を検査します。
class Directory{constructor(){this.files=new Map();this.dirs=new Map();}async getDirectoryHandle(name,{create=false}={}){if(!this.dirs.has(name)&&create)this.dirs.set(name,new Directory());if(!this.dirs.has(name))throw Object.assign(new Error('missing'),{name:'NotFoundError'});return this.dirs.get(name);}async getFileHandle(name,{create=false}={}){if(!this.files.has(name)&&!create)throw Object.assign(new Error('missing'),{name:'NotFoundError'});return {getFile:async()=>this.files.get(name)||new Blob([]),createWritable:async()=>{let data;return {write:async b=>{data=b;},close:async()=>this.files.set(name,data),abort:async()=>{}};}};}} // 実OPFSではないメモリ保存領域を用意します。
const image=name=>new File([Buffer.from('89504e470d0a1a0a0000000000000000','hex')],name||'sample.png',{type:'image/png'}); // 合成の形式確認用データを使います。
function harness({connected=true,account=true,online=true,needsInteraction=false,verify}={}){ // 各テストのUI状態を分離します。
  const state={scope:'ms-a',lastError:'',blocked:false},root=new Directory(),store=new MediaStore('ms-a',{getDirectory:async()=>root}),nodes=new Map(),listeners=new Map(); // 本人情報と保存は人工データだけです。
  const element=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',hidden:false,disabled:false,dataset:{},addEventListener(){},setAttribute(){}});return nodes.get(id);}; // テキスト表示と無効状態だけを模擬します。
  const label={dataset:{},setAttribute(name,value){this.dataset[name]=value;}},input={dataset:{mediaFile:'row-a'},files:[],value:'',disabled:false,closest:()=>label}; // ファイル選択欄を模擬します。
  const counters={checks:0,gathers:0,renders:0},hint=element('accessHint'),windowListeners=new Map(); // 読取確認と更新の副作用を数えます。
  const session={store,closed:false,controller:new AbortController(),summary:()=>({count:0})}; // 同期の実通信は発生させません。
  const sandbox={mediaImportAccess,authorizeMediaImport,assertMediaImportPermit,mediaList,mediaRef,mediaSize,MEDIA_COUNT,MediaStore,AbortController,AbortSignal,URL,console,mediaSession:session,mediaImportAbort:null,mediaImporting:false,saving:false,initialized:true,cloudReady:connected,dirty:false,syncFailure:'',state,auth:{account:account?{username:'synthetic@example.invalid'}:null,needsInteraction,scope:()=>state.scope},navigator:{onLine:online},rows:[{id:'row-a',name:'スライド',media:[]}],currentDetail:null,$:element,e:value=>String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;'),gather:()=>{counters.gathers++;},renderRows:()=>{counters.renders++;},saveFeedback:(text,kind)=>{element('saveFeedback').textContent=text;element('saveFeedback').kind=kind;},message:(text,error)=>{element('notice').textContent=text;element('notice').error=error;},request:async command=>{assert.equal(command,'mediaConnection');counters.checks++;return verify?verify(sandbox,counters):{scope:state.scope,folderId:'folder-a'};},document:{addEventListener:(name,fn)=>listeners.set(name,fn),querySelectorAll:selector=>selector==='[data-media-file]'?[input]:selector==='[data-media-access-hint]'?[hint]:[]},window:{addEventListener:(name,fn)=>windowListeners.set(name,fn)},guard:async fn=>fn()}; // 最小の依存だけを模擬し、取込関数を差し替えません。
  sandbox.refreshPresentation=()=>sandbox.ui?.renderMediaAccess();const context=vm.createContext(sandbox);vm.runInContext(fragment+'\nglobalThis.ui={importMedia,mediaEditor,renderMediaAccess};',context); // 候補UIの本体を実行します。
  return {s:sandbox,input,counters,store,root,node:element,windowListeners,select:async files=>{input.files=files;input.value='selected';await sandbox.ui.importMedia(input);}}; // 実際のimportMediaをテストから呼びます。
} // 模擬画面の準備を閉じます。
for(const [label,setup]of [['ゲスト',{account:false,connected:false}],['サインインのみ',{connected:false}],['オフライン',{online:false}],['再認証待ち',{needsInteraction:true}]])test('U '+label+'は入力欄と処理の両方で追加拒否',async()=>{const h=harness(setup);h.s.ui.renderMediaAccess();assert.equal(h.input.disabled,true);const before=JSON.stringify(h.s.rows);await h.select([image()]);assert.equal(h.counters.checks,0);assert.equal(h.counters.gathers,0);assert.equal(h.s.dirty,false);assert.equal(JSON.stringify(h.s.rows),before);assert.equal(h.input.value,'');assert.match(h.node('saveFeedback').textContent,/OneDrive|オフライン|再接続/);}); // 無効化した欄へファイルを渡しても追加しません。
test('U 接続確認に成功したファイルだけ参照追加',async()=>{const h=harness();h.s.ui.renderMediaAccess();assert.equal(h.input.disabled,false);await h.select([image()]);assert.equal(h.counters.checks,1);assert.equal(h.s.rows[0].media.length,1);assert.equal(h.s.dirty,true);assert.equal(h.s.mediaImporting,false);assert.match(h.node('saveFeedback').textContent,/写真・動画を追加しました/);}); // 実際の保存層を通過して参照を追加します。
test('U 接続確認失敗では本体を読まず既存入力を保持',async()=>{const h=harness({verify:async()=>{throw new Error('network failed');}}),file=image();let reads=0;file.slice=()=>{reads++;throw new Error('must not read');};await h.select([file]);assert.equal(reads,0);assert.equal(h.s.rows[0].media.length,0);assert.equal(h.s.dirty,false);assert.equal(h.input.disabled,true);assert.match(h.node('notice').textContent,/network failed/);}); // 接続済み表示だけで新規添付を許可しません。
test('U ファイル選択後の切断は複数ファイルの途中で停止',async()=>{const h=harness();const a=image('first.png'),b=image('second.png');let secondReads=0;b.slice=()=>{secondReads++;throw new Error('should not read');};const original=a.arrayBuffer.bind(a);a.arrayBuffer=async()=>{h.s.navigator.onLine=false;h.s.ui.renderMediaAccess();h.s.navigator.onLine=true;return original();};await h.select([a,b]);assert.equal(h.s.rows[0].media.length,0);assert.equal(secondReads,0);assert.equal(h.s.dirty,false);assert.equal(h.s.mediaImporting,false);}); // 一度の切断を復帰で帳消しにしません。
test('U 接続解除でも保存済み参照や名前を消さない',async()=>{const h=harness();await h.select([image()]);const before=JSON.stringify(h.s.rows);h.s.cloudReady=false;h.s.ui.renderMediaAccess();assert.equal(h.input.disabled,true);assert.equal(JSON.stringify(h.s.rows),before);assert.match(h.s.ui.mediaEditor(h.s.rows[0]),/data-media-preview/);}); // 表示と添付解除の導線は残します。
test('U 同期確認が回復したら追加欄を再度有効化',()=>{const h=harness();h.s.syncFailure='offline';h.s.ui.renderMediaAccess();assert.equal(h.input.disabled,true);h.s.syncFailure='';h.s.ui.renderMediaAccess();assert.equal(h.input.disabled,false);}); // 失敗理由が残っている間は復帰済みとしません。
test('U アカウント切替後の結果を別のメニューへ入れない',async()=>{const h=harness({verify:async s=>{s.state.scope='ms-b';return {scope:'ms-b',folderId:'folder-b'};}});await h.select([image()]);assert.equal(h.s.rows[0].media.length,0);assert.equal(h.s.dirty,false);assert.equal(h.counters.renders,1);assert.equal(h.input.disabled,true);}); // 古いアカウントの許可や取込結果を流用しません。
