import {chromium,webkit} from 'playwright'; // 実ブラウザでファイル選択とOPFSを使用します。
import assert from 'node:assert/strict'; // 実際の表示と保存された参照を照合します。
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises'; // 合成ファイルと検証結果だけを保存します。
import {join} from 'node:path'; // 保存先を検証領域へ限定します。
import {tmpdir} from 'node:os'; // 検証用ブラウザのOS領域を分離します。
import {createServer} from './serve-project.mjs'; // 既存と同じ専用サブパスを配信します。
import {FIXTURES} from './media-fixtures.mjs'; // 人物が映っていないPNGと短いMP4だけを使用します。
const live=process.env.SITE_URL,reports=live?'reports/media-live':'reports/media';const results=[],errors=[];let server,url=live;await mkdir(reports,{recursive:true}); // 公開前と公開後を別の証拠として保持します。
if(live)assert.equal(live,'https://yuge-u.github.io/zero-one-practice-lab/');else{server=createServer();await new Promise(done=>server.listen(0,'127.0.0.1',done));url=`http://127.0.0.1:${server.address().port}/zero-one-practice-lab/`;} // 本人のOneDriveは使いません。
const png=Buffer.from(FIXTURES['photo.png'],'base64'),mp4=Buffer.from(FIXTURES['clip.mp4'],'base64'),scope='ms-'+'d'.repeat(64); // 新しい検証専用のアカウント境界を使います。
const syntheticAuth=`export class Auth{constructor(){this.account={username:'media-test@example.invalid'};this.client={};this.redirectUri=new URL('./',location.href).href;}async init(){}scope(){return '${scope}';}get needsInteraction(){return sessionStorage.getItem('synthetic-media-reauth')==='1';}async token(){if(this.needsInteraction)throw new Error('synthetic reauth');return 'synthetic-media-token';}lastOfflineScope(){return null;}}`; // Microsoft認証応答だけを合成し保存処理は置換しません。
async function check(engine,name,fn){await fn();results.push({engine,name,pass:true});console.log('PASS',engine,name);} // 実行できていないケースを合格に数えません。
async function ready(page){await page.waitForFunction(()=>document.getElementById('editorFields')&&!document.getElementById('editorFields').disabled);assert.match(await page.locator('footer').innerText(),/1\.3\.0/);} // 実際のアプリ初期化を待ちます。
async function save(page){await page.locator('#savePlan').click();await page.waitForFunction(()=>document.getElementById('saveFeedback').textContent.includes('練習を保存しました'));} // 保存完了を確認してから次へ進みます。
async function fill(page,title){await page.locator('#title').fill(title);await page.locator('#goal').fill('写真と映像を参考に姿勢を見る');await page.locator('[data-field="category"]').first().fill('フットワーク');await page.locator('[data-field="name"]').first().fill('スライド確認');} // メニューの人工データを入力します。
async function attach(page,files){await page.locator('[data-media-file]').first().setInputFiles(files);await page.waitForFunction(()=>!document.getElementById('editorFields').disabled&&document.getElementById('saveFeedback').textContent.includes('写真・動画を追加しました'));} // ファイル書込みの完了まで待ちます。
async function library(page,title){await page.locator('[data-tab="library"]').click();const card=page.locator('.saved-card').filter({hasText:title}).first();await card.locator('[data-open]').click();await page.waitForFunction(title=>document.getElementById('detailTitle').textContent===title,title);} // 保存した対象だけを開きます。
try{for(const [engine,type]of Object.entries({chromium,webkit})){const contexts=[];const files=new Map(),binaries=new Map();let folder=false,mediaFolder=false,mediaDownloads=0,mediaPuts=0,failMedia=false,holdMedia=false,heldRelease=null;let heldPromise=Promise.resolve(); // エンジンごとに合成クラウドを分離します。
  const meta=name=>({id:name,name,file:{},size:Buffer.byteLength(files.get(name)||''),'@microsoft.graph.downloadUrl':'https://media-test.1drv.com/data/'+encodeURIComponent(name)}); // 計画の読戻しを元の形式で再現します。
  const binaryMeta=name=>({id:'media-'+name,name,file:{},size:binaries.get(name)?.length,eTag:'v1-'+name,'@microsoft.graph.downloadUrl':'https://media-test.1drv.com/media/'+name}); // バイナリのメタデータだけを返します。
  async function browser(cloud=false){const home=await mkdtemp(join(tmpdir(),'practice-media-'));const context=await type.launchPersistentContext(join(home,'profile'),{headless:true,viewport:{width:390,height:844},hasTouch:true,serviceWorkers:'block',env:{...process.env,HOME:home,CFFIXED_USER_HOME:home,XDG_DATA_HOME:join(home,'data'),XDG_CACHE_HOME:join(home,'cache'),XDG_CONFIG_HOME:join(home,'config')}});contexts.push(context); // SDK合成試験ではSWを停止し、既存の本物SW試験は別途維持します。
    await context.route('**/*',async route=>{const request=route.request(),target=new URL(request.url()),local=new URL(url);const reply=(status,value)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value),headers:{'Access-Control-Allow-Origin':'*'}}); // 外部通信は合成のGraphだけへ限定します。
      if(target.origin===local.origin){if(cloud&&target.pathname===local.pathname+'auth.mjs')return route.fulfill({status:200,contentType:'text/javascript',body:syntheticAuth});return route.continue();} // アプリ・保存・メディア処理の実コードを読みます。
      if(!['graph.microsoft.com','media-test.1drv.com'].includes(target.hostname))return route.abort();const path=decodeURIComponent(target.pathname); // 本人の資格情報を外部へ送信しません。
      if(target.hostname==='media-test.1drv.com'){assert(!request.headers().authorization);if(path.startsWith('/media/')){mediaDownloads++;const name=path.slice(7);return binaries.has(name)?route.fulfill({status:200,contentType:'application/octet-stream',body:binaries.get(name),headers:{'Access-Control-Allow-Origin':'*'}}):reply(404,{});}const name=path.slice(6);return files.has(name)?route.fulfill({status:200,contentType:'application/json',body:files.get(name),headers:{'Access-Control-Allow-Origin':'*'}}):reply(404,{});} // 一時URLへBearerを付けないことを実通信で検査します。
      assert.equal(request.headers().authorization,'Bearer synthetic-media-token');if(path.endsWith('/special/approot'))return reply(200,{id:'root',folder:{}}); // 合成認証のみが使用されていることを確認します。
      if(path.endsWith('/items/root/children')){if(request.method()==='POST'){folder=true;return reply(201,{id:'folder',folder:{}});}return reply(200,{value:folder?[{id:'folder',name:'ZERO_ONE_PRACTICE_LAB_V02',folder:{}}]:[]});} // 親フォルダーの作成は既存の接続操作から行います。
      if(path.endsWith('/items/folder/children')){if(request.method()==='POST'){const data=JSON.parse(request.postData());assert.equal(data.name,'media-v1');mediaFolder=true;return reply(201,{id:'media',name:'media-v1',folder:{}});}return reply(200,{value:[...[...files.keys()].map(meta),...(mediaFolder?[{id:'media',name:'media-v1',folder:{}}]:[])]});} // 添付を追加しても旧計画の一覧を壊しません。
      if(path.endsWith('/items/folder:/media-v1'))return mediaFolder?reply(200,{id:'media',name:'media-v1',folder:{}}):reply(404,{}); // 添付専用子フォルダーです。
      const binary=/\/items\/media:\/(M_[a-f0-9]{64}\.bin)(:\/content)?$/.exec(path);if(binary){const name=binary[1];if(binary[2]){assert.equal(request.method(),'PUT');assert.equal(target.searchParams.get('@microsoft.graph.conflictBehavior'),'fail');if(holdMedia)await heldPromise;if(failMedia)return reply(503,{});if(binaries.has(name))return reply(409,{});mediaPuts++;binaries.set(name,request.postDataBuffer());return reply(201,binaryMeta(name));}return binaries.has(name)?reply(200,binaryMeta(name)):reply(404,{});} // 再試行が上書きや重複を起こさないことを確認します。
      const match=/\/items\/folder:\/(.+?)(:\/content)?$/.exec(path);if(match){const name=match[1];if(match[2]&&request.method()==='PUT'){files.set(name,request.postData());return reply(201,meta(name));}return files.has(name)?reply(200,meta(name)):reply(404,{});} // 計画本体は既存の同期エンジンを通します。
      const name=path.split('/items/')[1];if(name&&files.has(name))return reply(200,meta(name));return reply(404,{}); // 未対応の要求を成功に見せません。
    });const page=await context.newPage();page.setDefaultTimeout(25000);page.on('pageerror',e=>errors.push({engine,message:e.message}));page.on('dialog',d=>d.accept());await page.goto(url);await ready(page);return {page,context};} // エラーも証拠として保持します。
  let page;try{ // 各エンジンで一連の実操作を検証します。
    ({page}=await browser());await check(engine,'V01 任意の添付欄と15人180分を維持',async()=>{assert.equal(await page.locator('#players').inputValue(),'15');assert.equal(await page.locator('#totalMinutes').inputValue(),'180');assert.equal(await page.locator('[data-media-file]').count(),1);assert.equal(await page.locator('[data-media-file]').first().isDisabled(),true);assert.equal(await page.locator('#mediaSyncStatus').isVisible(),false);assert.equal(await page.locator('#backup').textContent(),'計画バックアップ');}); // 写真を使わない操作を変えません。
    await check(engine,'V00 ゲストからの直接ファイル入力も拒否',async()=>{await page.evaluate(bytes=>{const input=document.querySelector('[data-media-file]');const files=new DataTransfer();files.items.add(new File([new Uint8Array(bytes)],'denied.png',{type:'image/png'}));input.files=files.files;input.dispatchEvent(new Event('change',{bubbles:true}));},[...png]);await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('OneDrive'));assert.equal(await page.locator('#items .media-entry').count(),0);assert.equal(files.size,0);assert.equal(binaries.size,0);}); // 非活性の欄を経由しなくても拒否することを検査します。
    const initialConnected=await browser(true);page=initialConnected.page;assert.equal(await page.locator('[data-media-file]').first().isDisabled(),true);await page.locator('#quickConnect').click();await page.waitForFunction(()=>!document.querySelector('[data-media-file]').disabled); // サインインだけでなくOneDrive接続完了を必要とします。
    await fill(page,'メディア原本');await attach(page,[{name:'photo.png',mimeType:'image/png',buffer:png},{name:'clip.mp4',mimeType:'video/mp4',buffer:mp4}]);await check(engine,'V02 写真と動画を選択しても未保存・未送信',async()=>{assert.equal(await page.locator('#items .media-entry').count(),2);assert.equal([...files.keys()].filter(name=>name.startsWith('O_')).length,0);assert.equal(binaries.size,0);assert.equal(await page.locator('.saved-card').count(),0);}); // 選択だけでクラウドへ送りません。
    await save(page);await page.reload();await ready(page);await library(page,'メディア原本');await check(engine,'V03 再読込後も添付2件を保持',async()=>{assert.equal(await page.locator('#detailItems .media-entry').count(),2);}); // 実OPFSから読み戻します。
    await page.locator('#detailItems [data-media-preview]').first().click();await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody img')?.naturalWidth===8);await check(engine,'V04 写真の実表示と元ファイル書出し',async()=>{const download=page.waitForEvent('download');await page.locator('#mediaOriginal').click();assert.equal((await download).suggestedFilename(),'photo.png');});await page.locator('#closeMedia').click(); // 実際にPNGをデコードします。
    await page.locator('#detailItems [data-media-preview]').nth(1).click();await page.locator('#mediaPreviewBody video').waitFor();await check(engine,'V05 合成MP4のデコード・インライン実再生',async()=>{const video=page.locator('#mediaPreviewBody video');assert(await video.evaluate(v=>v.controls&&v.playsInline&&!v.autoplay));await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.readyState>=2);await video.evaluate(async v=>{v.muted=true;await v.play();});await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.currentTime>0);await video.evaluate(v=>v.pause());await page.waitForFunction(()=>document.getElementById('mediaOriginal').disabled===false);});await page.locator('#closeMedia').click(); // コーデックの機種差を再生成功の断言に置き換えません。
    await page.locator('#copyPlan').click();await page.waitForFunction(()=>document.getElementById('draftMode').textContent.includes('コピーから'));await page.locator('#title').fill('メディア変更コピー');await page.locator('#items [data-media-remove]').first().click();await save(page);await check(engine,'V06 コピー後に添付を外しても原本を保持',async()=>{await library(page,'メディア原本');assert.equal(await page.locator('#detailItems .media-entry').count(),2);await library(page,'メディア変更コピー');assert.equal(await page.locator('#detailItems .media-entry').count(),1);}); // 計画をまたぐ参照解除で元画像を消しません。
    await page.locator('[data-tab="editor"]').click();await page.locator('#newPlan').click();await page.locator('#addPastMenu').click();await page.locator('.picker-results button').first().waitFor();await page.locator('.picker-results button').filter({hasText:'スライド確認'}).first().click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await check(engine,'V07 過去メニュー追加でも添付を引継ぐ',async()=>{assert((await page.locator('#items .media-entry').count())>=1);}); // 分類検索からの再利用も検証します。
    await page.locator('[data-media-file]').first().setInputFiles({name:'fake.png',mimeType:'image/png',buffer:Buffer.from('<svg onload="alert(1)"/>')});await page.waitForFunction(()=>document.getElementById('saveFeedback').textContent.includes('対応形式'));await check(engine,'V08 偽装した画像の取込を拒否',async()=>{assert.match(await page.locator('#saveFeedback').innerText(),/対応形式/);}); // HTMLやSVGを写真として保存しません。
    await check(engine,'V16 オフラインの追加を止め既存添付を保持',async()=>{const count=await page.locator('#items .media-entry').count();await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false});window.dispatchEvent(new Event('offline'));});assert.equal(await page.locator('[data-media-file]').first().isDisabled(),true);await page.evaluate(bytes=>{const input=document.querySelector('[data-media-file]');const files=new DataTransfer();files.items.add(new File([new Uint8Array(bytes)],'offline.png',{type:'image/png'}));input.files=files.files;input.dispatchEvent(new Event('change',{bubbles:true}));},[...png]);await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('オフライン'));assert.equal(await page.locator('#items .media-entry').count(),count);await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>true});window.dispatchEvent(new Event('online'));});await page.waitForFunction(()=>!document.querySelector('[data-media-file]').disabled);}); // 実機の機内モードではなくイベントを模擬した試験です。
    await check(engine,'V17 再認証待ちは追加禁止で復帰後に再開',async()=>{await page.evaluate(()=>{sessionStorage.setItem('synthetic-media-reauth','1');window.dispatchEvent(new Event('pageshow'));});assert.equal(await page.locator('[data-media-file]').first().isDisabled(),true);assert.match(await page.locator('[data-media-access-hint]').first().innerText(),/再接続/);await page.evaluate(()=>{sessionStorage.removeItem('synthetic-media-reauth');window.dispatchEvent(new Event('pageshow'));});await page.waitForFunction(()=>!document.querySelector('[data-media-file]').disabled);}); // 認証の再確認が済むまでは追加欄を使えません。
    await page.waitForFunction(()=>document.getElementById('mediaSyncStatus').textContent.includes('OneDrive確認済み'));await initialConnected.context.close();files.clear();binaries.clear();folder=false;mediaFolder=false;mediaDownloads=0;mediaPuts=0; // ここだけは人工クラウドの試験間リセットであり本人データには触れません。
    const source=await browser(true);page=source.page;await page.locator('#quickConnect').click();await page.waitForFunction(()=>document.getElementById('storageStatus').textContent.includes('OneDrive接続済み'));await fill(page,'クラウド添付');await attach(page,[{name:'photo.png',mimeType:'image/png',buffer:png},{name:'clip.mp4',mimeType:'video/mp4',buffer:mp4}]);failMedia=true;await save(page);await page.waitForFunction(()=>document.getElementById('mediaSyncStatus').textContent.includes('未完了'));await check(engine,'V09 添付送信失敗でも計画保存は成功',async()=>{assert.equal(await page.locator('#savePlan').isEnabled(),true);assert.match(await page.locator('#saveFeedback').innerText(),/練習を保存しました/);assert.equal(binaries.size,0);assert.equal([...files.keys()].filter(k=>k.startsWith('O_')).length,1);}); // 添付エラーが保存本体を巻き戻しません。
    failMedia=false;holdMedia=true;heldPromise=new Promise(done=>{heldRelease=done;});await page.locator('#syncNow').click();await page.waitForFunction(()=>document.getElementById('mediaSyncStatus').textContent.includes('同期中'));await page.locator('#newPlan').click();await fill(page,'添付送信中でも次のプラン');await save(page);await check(engine,'V10 添付送信中も新しい計画を保存できる',async()=>{assert.equal(await page.locator('.saved-card').count(),2);});holdMedia=false;heldRelease(); // 大きい動画で練習の保存を妨げないことを確認します。
    await page.waitForFunction(()=>document.getElementById('mediaSyncStatus').textContent.includes('OneDrive確認済み'));await check(engine,'V11 再試行は同じ実体を重複送信しない',async()=>{assert.equal(binaries.size,2);assert.equal(mediaPuts,2);}); // 再試行と重複排除を確認します。
    const before=mediaDownloads,peer=await browser(true);page=peer.page;await page.waitForFunction(()=>document.getElementById('mediaSyncStatus').textContent.includes('OneDrive確認済み'));await library(page,'クラウド添付');await check(engine,'V12 別端末で参照を受信し全動画は自動取得しない',async()=>{assert.equal(await page.locator('#detailItems .media-entry').count(),2);assert.equal(mediaDownloads,before);}); // 別端末への同期と必要時取得を区別します。
    await page.locator('#detailItems [data-media-preview]').first().click();await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody img')?.naturalWidth===8);await check(engine,'V13 別端末で写真本体を取得して表示',async()=>{assert.equal(mediaDownloads,before+1);});await page.locator('#closeMedia').click(); // 認証済みURLとハッシュ照合を通して取得します。
    await peer.context.route('https://media-test.1drv.com/media/**',route=>route.abort());await page.locator('#detailItems [data-media-preview]').first().click();await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody img')?.naturalWidth===8);await check(engine,'V14 取得済み写真はクラウド通信なしで表示',async()=>{assert.equal(mediaDownloads,before+1);});await page.locator('#closeMedia').click(); // 取得済みのローカル実体を利用します。
    await check(engine,'V15 写真欄も小画面で横にはみ出さない',async()=>{for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));}});await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(reports,engine+'-media.png'),fullPage:true}); // 表示品質の証拠を保存します。
  }catch(error){errors.push({engine,message:error.message});if(page)await page.screenshot({path:join(reports,engine+'-failure.png'),fullPage:true}).catch(()=>{});}finally{holdMedia=false;heldRelease?.();for(const context of contexts)await context.close();} // 失敗した環境の証拠も残します。
}}finally{if(server){server.closeAllConnections();await new Promise(done=>server.close(done));}const passed=results.length===36&&errors.length===0;await writeFile(join(reports,'results.json'),JSON.stringify({version:'1.3.0',results,errors,passed,realMicrosoft:false,physicalIPhone:false,notes:'OneDrive-only imports; actual OPFS/file inputs and PNG/MP4 decoding; synthetic Auth and Graph; Service Workers tested separately. Codec support for other real files remains device-dependent.'},null,2));if(!passed)process.exitCode=1;} // 必須シナリオが全て通った場合だけ成功とします。
