import {authorizeMediaImport} from '../web/media-import-policy.mjs'; // 新規添付は同期利用可能な本人として試験します。
import test from 'node:test'; // 添付の検査と記録保護を実行します。
import assert from 'node:assert/strict'; // 期待と実結果を厳密に比較します。
import {DatabaseSync} from 'node:sqlite'; // 合成データだけを実SQLiteへ保存します。
import {AppService} from '../web/core/service.mjs'; // 配信する保存処理を使用します。
import {rowsFromDetail,draftErrors} from '../web/draft.mjs'; // コピーと入力検査を実際のコードで確認します。
import {NO_TERM,menuChoices} from '../web/catalog.mjs'; // 添付違いの候補を確認します。
import {mediaRef,mediaList,inspectMedia,MEDIA_LIMIT,savedMedia,digestBlob,mediaFilename} from '../web/media-model.mjs'; // サイズ・形式・固定参照の検査を対象にします。
import {MediaStore} from '../web/media-store.mjs'; // 添付実体の保存処理を検証します。
import {MediaCloud,safeMediaUrl} from '../web/media-cloud.mjs'; // Graph以外へトークンを送らないことを確認します。
import {MediaSession} from '../web/media-session.mjs'; // 添付が失敗しても保存本体を妨げないことを確認します。
const png=Buffer.from('89504e470d0a1a0a0000000000000000','hex'),file=()=>new File([png],'photo.png',{type:'image/png'}),ref=await inspectMedia(file()); // 形式判定用の合成バイト列を使います。
const input=()=>({title:'写真付プラン',team:'U15',players:15,totalMinutes:180,goal:'姿勢を見る',items:[{section:'BODY',category:'フットワーク',name:'スライド',minutes:10,term:NO_TERM,media:[ref]}]}); // 元のメニュー構造へ任意の添付を追加します。
function service(t,scope='guest-local'){const app=new AppService(new DatabaseSync(':memory:'),scope);t.after(()=>app.repo.close());return app;} // 試験の終了後に保存領域を閉じます。
class Directory{constructor(){this.dirs=new Map();this.files=new Map();}async getDirectoryHandle(name,{create=false}={}){if(!this.dirs.has(name)&&create)this.dirs.set(name,new Directory());if(!this.dirs.has(name))throw Object.assign(new Error('missing'),{name:'NotFoundError'});return this.dirs.get(name);}async getFileHandle(name,{create=false}={}){const owner=this;if(!owner.files.has(name)&&!create)throw Object.assign(new Error('missing'),{name:'NotFoundError'});return {getFile:async()=>owner.files.get(name)||new Blob([]),createWritable:async()=>{let pending;return {write:async value=>{pending=value;},close:async()=>{owner.files.set(name,pending);},abort:async()=>{}};}};}} // OPFSの原子書込境界を小さな模擬領域で再現します。
const storage=()=>{const root=new Directory();return {getDirectory:async()=>root};}; // 実ブラウザのOPFS試験は別の必須試験で行います。
function cloudFixture(store){const remote=new Map(),calls=[];let exists=false;const meta=r=>({id:r.hash,name:mediaFilename(r),size:remote.get(r.hash)?.size,file:{},eTag:'etag-'+r.hash,'@microsoft.graph.downloadUrl':'https://synthetic.1drv.com/'+r.hash});const graph={getToken:async()=>'synthetic-token',safeUrl:path=>'https://graph.microsoft.com/v1.0'+path,request:async(path,options={})=>{calls.push({path,method:options.method||'GET'});if(path.endsWith('/parent:/media-v1'))return exists?{id:'media',name:'media-v1',folder:{}}:null;if(path.endsWith('/parent/children')){exists=true;return{id:'media',name:'media-v1',folder:{}};}const hash=/M_([a-f0-9]{64})\.bin/.exec(path)?.[1];return hash&&remote.has(hash)?meta({...ref,hash}):null;},fetcher:async(url,options)=>{calls.push({url,options});if(url.startsWith('https://graph.microsoft.com')){const hash=/M_([a-f0-9]{64})\.bin/.exec(url)[1];remote.set(hash,options.body);return new Response('{}',{status:201});}assert(!options.headers?.Authorization);assert.equal(options.credentials,'omit');return new Response(remote.get(url.split('/').at(-1)),{status:200});}};return {cloud:new MediaCloud(graph,'parent',store,new AbortController().signal),remote,calls,graph};} // Graph応答と短期URLのみを合成します。
test('M01 写真の形式とバイナリSHAを取得',async()=>{assert.equal(ref.type,'image/png');assert.equal(ref.size,png.length);assert.equal(ref.hash,await digestBlob(file()));}); // 保存の識別値を検査します。
test('M02 動画MP4とMOVの形式を区別',async()=>{for(const [brand,type]of [['isom','video/mp4'],['qt  ','video/quicktime']])assert.equal((await inspectMedia(new File([Buffer.from('\0\0\0\x18ftyp'+brand+'\0\0\0\0')],'clip.mov'))).type,type);}); // 動画コンテナーの確認です。
test('M03 HEICを無変換で取り込む',async()=>{assert.equal((await inspectMedia(new File([Buffer.from('\0\0\0\x18ftypheic\0\0\0\0')],'photo.heic'))).type,'image/heic');}); // 再生能力とファイル保存を混同しません。
test('M04 SVGと偽のMIMEを拒否',async()=>{await assert.rejects(inspectMedia(new File(['<svg onload="alert(1)"></svg>'],'a.png',{type:'image/png'})));}); // 実行可能なファイルを画像扱いしません。
test('M05 空ファイルを拒否',async()=>{await assert.rejects(inspectMedia(new File([],'empty.png')));}); // 空の添付成功を表示しません。
test('M06 サイズ上限をメタデータでも検査',()=>{assert.throws(()=>mediaRef({...ref,size:MEDIA_LIMIT+1}));assert.throws(()=>mediaRef({...ref,size:-1}));}); // 入力と同期受信の両方を制限します。
test('M07 一メニュー8件まで',()=>{assert.equal(mediaList(Array.from({length:8},(_,i)=>({...ref,hash:i.toString(16).padStart(64,'0')}))).length,8);assert.throws(()=>mediaList(Array(9).fill(ref)));}); // 上限を超える登録を拒否します。
test('M08 同じ実体の重複参照を拒否',()=>{assert.throws(()=>mediaList([ref,ref]));}); // 不要な同一添付を増やしません。
test('M09 任意URLやパスを識別子にできない',()=>{assert.throws(()=>mediaRef({...ref,hash:'https://invalid.example'}));assert.throws(()=>mediaRef({...ref,name:'../a.png'}));}); // 外部URLへ認証を流しません。
test('M10 過去の添付なしプランを許可',()=>{assert.deepEqual(mediaList(undefined),[]);const data=input();delete data.items[0].media;assert.deepEqual(draftErrors(data),[]);}); // 過去データを初期化しません。
test('M11 SQLiteへ添付の参照だけ保存',async t=>{const app=service(t);const value=await app.run('savePlan',{input:input()});assert.deepEqual(value.operation.body.payload.items[0].media,[ref]);assert.deepEqual(value.state.mediaRefs,[ref]);assert(!JSON.stringify(value).includes('base64'));}); // 実体をJSONやSQLiteへ埋め込みません。
test('M12 計画コピーで写真を引継ぎ原本を保持',async t=>{const app=service(t),original=await app.run('savePlan',{input:input()});const detail=await app.run('detail',{revisionId:original.operation.body.opId});const copied=rowsFromDetail(detail,true);copied[0].media=[];const data={...input(),items:copied,title:'コピー'};await app.run('savePlan',{input:data});assert.deepEqual(app.repo.getOp(original.operation.body.opId).body.payload.items[0].media,[ref]);assert.equal(app.repo.state().practices.length,2);}); // コピー側の解除が元の写真を消さないことを確認します。
test('M13 名前・条件変更後も添付を維持',async t=>{const app=service(t),one=await app.run('savePlan',{input:input()});const detail=await app.run('detail',{revisionId:one.operation.body.opId});const row=rowsFromDetail(detail,true)[0];row.pinned=null;row.rule='反応する';row.name='変更した名前';const saved=await app.run('savePlan',{input:{...input(),items:[row]}});assert.deepEqual(saved.operation.body.payload.items[0].media,[ref]);}); // Variation変更で添付を落としません。
test('M14 固定版を残した添付解除が保存される',async t=>{const app=service(t),one=await app.run('savePlan',{input:input()});const detail=await app.run('detail',{revisionId:one.operation.body.opId});const row=rowsFromDetail(detail)[0];row.media=[];const saved=await app.run('savePlan',{revisionId:one.operation.body.opId,input:{...input(),items:[row]}});assert.deepEqual(saved.operation.body.payload.items[0].media,[]);assert.deepEqual(saved.state.mediaRefs,[ref]);}); // 過去の計画用の実体は保全対象として残します。
test('M15 バックアップ復元で参照を保持',async t=>{const a=service(t),b=service(t);await a.run('savePlan',{input:input()});await b.run('restore',{backup:await a.run('backup'),confirm:true});assert.deepEqual(b.repo.state().mediaRefs,[ref]);}); // 画像本体を含むバックアップとは表示しません。
test('M16 アカウント違いの計画取込を拒否',async t=>{const a=service(t),b=service(t,'ms-another');const one=await a.run('savePlan',{input:input()});assert.throws(()=>b.repo.ingest([one.operation],a.repo.objects()));assert.equal(b.repo.state().mediaRefs.length,0);}); // 他人の画像参照を取り込みません。
test('M17 添付違いのメニューは別候補',async t=>{const app=service(t);await app.run('savePlan',{input:input()});const data=input();data.items[0].media=[];await app.run('savePlan',{input:data});assert.equal(menuChoices(app.repo.state().practices).length,2);}); // 添付違いを重複として隠しません。
test('M18 ローカル実体を同じ内容で再利用',async()=>{const store=new MediaStore('ms-test',storage());await connectedImport(store,file());await connectedImport(store,file());assert.equal((await store.root()).files.size,1);assert.equal(await digestBlob(await store.get(ref)),ref.hash);}); // 同一写真をコピーして容量を増やしません。
test('M19 ローカルもアカウントごとに分離',async()=>{const fs=storage(),a=new MediaStore('ms-test',fs),b=new MediaStore('ms-another',fs);await connectedImport(a,file());assert.equal(await b.get(ref),null);}); // メタデータの識別値を知っていても別領域へ移りません。
test('M20 不一致のバイナリを保存しない',async()=>{const store=new MediaStore('ms-test',storage());await assert.rejects(store.put(new Blob(['corrupt']),ref));assert.equal(await store.get(ref),null);}); // 受信内容を検査してから保存します。
test('M21 閉じたアカウントの操作を拒否',async()=>{const store=new MediaStore('ms-test',storage());store.close();await assert.rejects(store.import(file()));}); // サインアウト後の書込を防ぎます。
test('M22 ダウンロードURLの安全性を検査',()=>{assert.equal(safeMediaUrl('https://abc.1drv.com/a'),'https://abc.1drv.com/a');for(const value of ['http://abc.1drv.com/a','https://abc.1drv.com.evil.example/a','https://u:p@abc.1drv.com/a','https://evil.example/a'])assert.throws(()=>safeMediaUrl(value));}); // 一時URLの許可先を検査します。
test('M23 送信後に読戻し確認し再送を抑止',async()=>{const store=new MediaStore('ms-test',storage());await connectedImport(store,file());const f=cloudFixture(store);await f.cloud.sync(ref);assert.equal(f.remote.size,1);assert((await store.receipt(ref)).eTag);await f.cloud.sync(ref);assert.equal(f.calls.filter(c=>c.options?.method==='PUT').length,1);assert(f.calls.filter(c=>c.url?.includes('synthetic.1drv.com')).every(c=>!c.options.headers?.Authorization));}); // 署名済みURLへトークンを送らず同じ実体を上書きしません。
test('M24 別端末では必要時だけ実体を取得',async()=>{const fs=storage(),a=new MediaStore('ms-test',fs);await connectedImport(a,file());const f=cloudFixture(a);await f.cloud.sync(ref);const b=new MediaStore('ms-peer',fs),peer=new MediaCloud(f.graph,'parent',b);const count=f.calls.filter(c=>c.url?.includes('synthetic.1drv.com')).length;await peer.sync(ref);assert.equal(f.calls.filter(c=>c.url?.includes('synthetic.1drv.com')).length,count);assert.equal(await b.get(ref),null);assert.equal(await digestBlob(await peer.fetch(ref)),ref.hash);}); // 同期で全動画を勝手にダウンロードしません。
test('M25 消えたクラウド添付を勝手に復活させない',async()=>{const store=new MediaStore('ms-test',storage());await connectedImport(store,file());const f=cloudFixture(store);await f.cloud.sync(ref);f.remote.clear();await assert.rejects(f.cloud.sync(ref),/見つかりません/);assert.equal(f.calls.filter(c=>c.options?.method==='PUT').length,1);}); // 本人の削除意思を自動上書きしません。
test('M26 未送信の添付がない端末で空ファイルを作らない',async()=>{const store=new MediaStore('ms-test',storage()),f=cloudFixture(store);await assert.rejects(f.cloud.sync(ref),/ありません/);assert.equal(f.remote.size,0);}); // 同期待ちを成功に偽装しません。
test('M27 添付失敗後の再試行で状態を回復',async()=>{const store=new MediaStore('ms-test',storage());let failure=true;const session=new MediaSession(store,async()=>({sync:async()=>{if(failure)throw new Error('失敗');}}));session.update([ref]);await session.sync();assert.equal(session.summary().pending,1);assert(session.summary().error);failure=false;await session.sync();assert.equal(session.summary().remote,1);assert.equal(session.summary().error,'');}); // 失敗を保存本体の失敗にしません。
test('M28 未保存参照を同期候補へ含めない',async()=>{let calls=0;const session=new MediaSession(new MediaStore('ms-test',storage()),async()=>{calls++;return {sync:async()=>{}};});session.update([]);await session.sync();assert.equal(calls,0);}); // 添付を選んだだけで外部へ送信しません。
test('M29 添付情報にある資格情報を保存しない',()=>{assert.deepEqual(mediaRef({...ref,url:'https://invalid.example',token:'secret'}),ref);}); // 参照は必要な4属性だけに限定します。
test('M30 同一ハッシュのサイズ不一致を拒否',()=>{assert.throws(()=>savedMedia([{body:{kind:'practice',payload:{items:[{media:[ref]},{media:[{...ref,size:ref.size+1}]}]}}}]));}); // 異なる実体を同じファイルとして扱いません。

async function connectedImport(store,file){const state={initialized:true,account:true,connected:true,online:true,scope:store.scope,storeScope:store.scope,recordScope:store.scope};const permit=await authorizeMediaImport(()=>state,async()=>({scope:store.scope,folderId:'parent'}));return store.import(file,permit);} // GraphとOPFSを模擬した試験でのみ使用する本人接続です。
