import test from 'node:test'; // 直前の参考資料版からの互換性を確認します。
import assert from 'node:assert/strict'; // 元の操作を厳密に照合します。
import {DatabaseSync} from 'node:sqlite'; // 個人データではなくメモリ内DBを使用します。
import {AppService as Previous} from '../pre-media-web/core/service.mjs'; // 直前1.2.1の実コードです。
import {AppService} from '../web/core/service.mjs'; // 今回の添付版の実コードです。
import {rowsFromDetail} from '../web/draft.mjs'; // 実際のコピー処理です。
import {NO_TERM,menuChoices} from '../web/catalog.mjs'; // 検索候補の独立性を確認します。
import {makeReference} from '../web/reference-links.mjs'; // 既存リンク形式を維持します。
import {inspectMedia} from '../web/media-model.mjs'; // 新規の添付形式を使用します。
const link=makeReference({url:'https://example.com/practice',title:'既存の参考資料'}); // 人工の公開リンクを用意します。
const photo=await inspectMedia(new File([Buffer.from('89504e470d0a1a0a0000000000000000','hex')],'test.png')); // 形式検査用の合成素材です。
const input=()=>({title:'互換性プラン',goal:'判断を見る',team:'U15',players:8,totalMinutes:120,items:[{section:'BODY',category:'判断',name:'2対1',minutes:10,term:NO_TERM,references:[link]}]}); // 既存1.2.1に保存できる計画です。
function service(t,Type=AppService){const app=new Type(new DatabaseSync(':memory:'),'ms-compatibility');app.referenceApprovals=new Set([link.url]);t.after(()=>app.repo.close());return app;} // 許可済みリンクの試験状態だけを人工的に準備します。
test('X01 1.2.1のリンク・振り返り・未送信を完全保持',async t=>{const old=service(t,Previous),next=service(t);const result=await old.run('savePlan',{input:input()});await old.run('record',{revisionId:result.operation.body.opId,kind:'reflection',note:'以前の学び'});const backup=await old.run('backup');await next.run('restore',{backup,confirm:true});const restored=await next.run('backup');for(const key of ['scope','operations','objects','pending','acknowledged'])assert.deepEqual(restored.body[key],backup.body[key]);}); // 過去のハッシュや保存先を移行しません。
test('X02 リンクと写真を持つ計画のコピーで原本を保護',async t=>{const app=service(t),data=input();data.items[0].media=[photo];const first=await app.run('savePlan',{input:data});const detail=await app.run('detail',{revisionId:first.operation.body.opId});const rows=rowsFromDetail(detail,true);assert.deepEqual(rows[0].references,[link]);assert.deepEqual(rows[0].media,[photo]);rows[0].media=[];rows[0].references=[];await app.run('savePlan',{input:{...data,title:'コピー',items:rows}});const original=app.repo.getOp(first.operation.body.opId);assert.deepEqual(original.body.payload.items[0].media,[photo]);assert.deepEqual(original.body.payload.items[0].references,[link]);}); // 二種類の添付を別々に解除できます。
test('X03 リンク違い・写真違いを別メニュー候補に保持',async t=>{const app=service(t);await app.run('savePlan',{input:input()});const photoOnly=input();photoOnly.items[0].references=[];photoOnly.items[0].media=[photo];await app.run('savePlan',{input:photoOnly});const both=input();both.items[0].media=[photo];await app.run('savePlan',{input:both});assert.equal(menuChoices(app.repo.state().practices).length,3);}); // 資料の違いを勝手に集約しません。
test('X04 リンクと写真を含むバックアップで原本とコピーを復元',async t=>{const app=service(t),next=service(t),data=input();data.items[0].media=[photo];const first=await app.run('savePlan',{input:data});const detail=await app.run('detail',{revisionId:first.operation.body.opId});await app.run('savePlan',{input:{...data,title:'再利用',items:rowsFromDetail(detail,true)}});const before=await app.run('backup');await next.run('restore',{backup:before,confirm:true});const after=(await next.run('backup')).body;assert(Number.isFinite(Date.parse(after.createdAt)));for(const key of Object.keys(before.body).filter(key=>key!=='createdAt'))assert.deepEqual(after[key],before.body[key]);assert.equal(next.repo.state().practices.length,2);}); // 添付本体を含まないメタデータの復元検査です。
