import {mediaAssert,mediaRef,mediaFilename,MEDIA_LIMIT,digestBlob} from './media-model.mjs'; // 添付の固定名と内容検査を共用します。
export const MEDIA_FOLDER='media-v1'; // 既存の同期フォルダー内に写真・動画専用の子フォルダーを用意します。
export function safeMediaUrl(value){mediaAssert(typeof value==='string'&&value,'写真・動画の取得先を確認できません。再同期してください。');const url=new URL(value);mediaAssert(url.protocol==='https:'&&!url.username&&!url.password&&(!url.port||url.port==='443')&&/(^|\.)(1drv\.com|live\.com|onedrive\.com|sharepoint\.com|sharepointonline\.com)$/.test(url.hostname),'許可されていない写真・動画の取得先です。');return url.href;} // Graphが返したURLでも接続先を制限します。
export class MediaCloud{ // 個人の既存OneDrive接続を使い、公開サーバーへ写真を保存しません。
  constructor(graph,folderId,store,signal){mediaAssert(typeof folderId==='string'&&folderId,'写真・動画の同期先が未確認です。');this.graph=graph;this.parent=folderId;this.store=store;this.signal=signal;this.folder=null;} // 親フォルダーは識別確認済みの値だけを受け取ります。
  active(){this.store.active();this.signal?.throwIfAborted();} // サインアウトやアカウント切替後の処理を中断します。
  async open(create=false){this.active();if(this.folder)return this.folder;const path=`/me/drive/items/${encodeURIComponent(this.parent)}:/${MEDIA_FOLDER}`;let folder=await this.graph.request(path);this.active();if(!folder&&create){try{folder=await this.graph.request(`/me/drive/items/${encodeURIComponent(this.parent)}/children`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:MEDIA_FOLDER,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});}catch(error){if(error.code!=='CONFLICT')throw error;folder=await this.graph.request(path);}}if(!folder)return null;mediaAssert(folder.folder&&folder.id&&folder.name===MEDIA_FOLDER,'写真・動画の保存先に同名の別データがあります。上書きしません。');this.active();this.folder=folder.id;return this.folder;} // 同時作成の競合では既存フォルダーを読み直します。
  async metadata(ref){const id=await this.open();if(!id)return null;const item=await this.graph.request(`/me/drive/items/${encodeURIComponent(id)}:/${mediaFilename(ref)}`);this.active();if(!item)return null;mediaAssert(item.file&&item.id&&item.name===mediaFilename(ref)&&item.size===ref.size,'OneDriveの添付ファイルが一致しません。上書きしません。');return item;} // 名前とサイズが一致しないファイルを変更しません。
  async read(value,meta=null){const ref=mediaRef(value);const item=meta||await this.metadata(ref);mediaAssert(item,'写真・動画がOneDriveにまだありません。添付した端末で送信完了を確認してください。');const url=safeMediaUrl(item['@microsoft.graph.downloadUrl']);this.active();const response=await this.graph.fetcher(url,{credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer',redirect:'error',signal:AbortSignal.any([AbortSignal.timeout(180000),...(this.signal?[this.signal]:[])])}); // 一時URLへMicrosoftのトークンを付けません。
    mediaAssert(response.ok,'写真・動画を取得できません。通信を確認して再試行してください。');const declared=Number(response.headers.get('Content-Length'));mediaAssert(!declared||declared<=Math.min(MEDIA_LIMIT,ref.size),'受信する写真・動画が大きすぎます。');mediaAssert(response.body,'写真・動画の応答が空です。');const reader=response.body.getReader(),chunks=[];let size=0; // 大きすぎる応答を全読み込みする前に止めます。
    try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;mediaAssert(size<=ref.size&&size<=MEDIA_LIMIT,'受信した写真・動画が大きすぎます。');chunks.push(value);this.active();}}catch(error){await reader.cancel().catch(()=>{});throw error;}finally{reader.releaseLock();} // 中断・超過時に通信を停止します。
    const blob=new Blob(chunks,{type:ref.type});mediaAssert(size===ref.size&&await digestBlob(blob)===ref.hash,'写真・動画の内容が一致しません。保存・表示を停止しました。');this.active();return blob; // 取得した実体を内容ハッシュで検査します。
  } // ファイル取得を閉じます。
  async upload(value,blob){const ref=mediaRef(value);mediaAssert(blob.size===ref.size&&await digestBlob(blob)===ref.hash,'送信する添付の内容が一致しません。');const id=await this.open(true);this.active();const url=this.graph.safeUrl(`/me/drive/items/${encodeURIComponent(id)}:/${mediaFilename(ref)}:/content?@microsoft.graph.conflictBehavior=fail`);const token=await this.graph.getToken();this.active();mediaAssert(typeof token==='string'&&token,'Microsoftへの再接続が必要です。'); // 既存の権限と許可済みGraph宛先だけを使います。
    const response=await this.graph.fetcher(url,{method:'PUT',body:blob,headers:{Authorization:'Bearer '+token,'Content-Type':'application/octet-stream'},credentials:'omit',cache:'no-store',redirect:'error',signal:AbortSignal.any([AbortSignal.timeout(180000),...(this.signal?[this.signal]:[])])});this.active(); // 長い動画の送信も時間上限と中断に対応します。
    mediaAssert(response.ok||response.status===409,`写真・動画の送信が未完了です（${response.status}）。端末の記録を残しています。再同期してください。`);const saved=await this.metadata(ref);mediaAssert(saved,'写真・動画の送信結果を確認できません。再同期してください。');await this.read(ref,saved);await this.store.receipt(ref,{id:saved.id,eTag:saved.eTag||'',size:saved.size});return saved; // 保存後の読戻しで確認し、応答不明時は再保存せず照合します。
  } // ファイル送信を閉じます。
  async sync(ref){this.active();const remote=await this.metadata(ref);const receipt=await this.store.receipt(ref);if(remote){if(!receipt||receipt.id!==remote.id||receipt.eTag!==remote.eTag||receipt.size!==remote.size){const local=await this.store.get(ref);if(local)await this.read(ref,remote);await this.store.receipt(ref,{id:remote.id,eTag:remote.eTag||'',size:remote.size});}return 'remote';}mediaAssert(!receipt,'以前OneDriveに送信した写真・動画が見つかりません。自動で復活させず停止しました。');const local=await this.store.get(ref);mediaAssert(local,'添付本体がこの端末にもOneDriveにもありません。元の端末で同期するか、元ファイルを再添付してください。');await this.upload(ref,local);return 'remote';} // 未送信の保存済み添付だけを送り、既存のクラウド消失を隠しません。
  async fetch(ref){let blob=await this.store.get(ref);if(blob)return blob;const remote=await this.metadata(ref);blob=await this.read(ref,remote);await this.store.put(blob,ref);await this.store.receipt(ref,{id:remote.id,eTag:remote.eTag||'',size:remote.size});return blob;} // 別端末では表示操作時だけ必要なファイルを取得します。
} // 写真・動画専用クラウド処理を閉じます。
