import test from 'node:test'; // 参考資料の入力・保存・原本保持を検査します。
import assert from 'node:assert/strict'; // 実行結果を厳密に照合します。
import {DatabaseSync} from 'node:sqlite'; // 本人記録とは無関係なメモリ内DBです。
import {referenceUrl,normalizeReferences,referenceAccess,hasNewReferences,referenceProvider,MAX_REFERENCES} from '../web/references.mjs'; // 実配信モジュールを対象にします。
import {referenceList} from '../web/references-ui.mjs'; // HTMLは文字列として検査します。
import {AppService} from '../web/core/service.mjs'; // 本番の保存層を使います。
import {rowsFromDetail,draftErrors} from '../web/draft.mjs'; // フォームとコピーの互換性を確認します。
import {NO_TERM,menuChoices} from '../web/catalog.mjs'; // 既存の用語なし・検索条件を使います。
const scope='ms-'+'a'.repeat(64),reference={title:'お手本',url:'https://youtu.be/coach-demo?t=15'},input=()=>({title:'参考資料の原本',team:'U15',players:15,totalMinutes:180,goal:'判断を言葉にする',items:[{section:'BODY',category:'フットワーク',name:'反応ステップ',minutes:10,term:NO_TERM,variationName:'基本条件',rule:'',references:[{...reference}]}]}); // 合成データだけを用意します。
function service(t,connected=false,user=scope){const app=new AppService(new DatabaseSync(':memory:'),user,{graph:connected?{}:null});if(connected){app.engine={};app.cloud={check:async()=>{app.checks=(app.checks||0)+1;}};}t.after(()=>app.repo.close());return app;} // 接続確認の応答だけを単体試験で合成します。
for(const url of ['http://example.org/a','file:///a','blob:https://example.org/a','data:text/html,hello','javascript:alert(1)','//example.org/a','/a','https://user:pass@example.org/a','https://localhost/a','https://foo.local/a','https://127.0.0.1/a','https://[::1]/a','https://2130706433/a','https://192.168.1.1/a','https://example.org/\na','https://example.org\\a','https://example.org/?access_token=secret','https://example.org/?id_token=secret'])test('URL拒否 '+url,()=>assert.throws(()=>referenceUrl(url))); // 実行形式・端末内参照・認証トークンを拒否します。
test('HTTPS共有リンク・再生位置・資料パスを保持',()=>{for(const url of ['https://1drv.ms/v/s!example?e=demo','https://drive.google.com/file/d/demo/view','https://www.dropbox.com/scl/fi/demo/a.pdf?rlkey=demo&dl=0','https://www.icloud.com/iclouddrive/demo','https://www.youtube.com/watch?v=demo&t=45s','https://example.org/資料.pdf#page=2'])assert.equal(referenceUrl(url),new URL(url).href);}); // 元の閲覧用情報は勝手に削りません。
test('表示名とURLだけを新しい配列として返す',()=>{const old=[reference];assert.deepEqual(normalizeReferences(old),old);assert.notEqual(normalizeReferences(old)[0],reference);assert.deepEqual(normalizeReferences(undefined),[]);}); // 原本を変更しません。
test('件数・重複・形式の検査',()=>{assert.equal(MAX_REFERENCES,8);for(const data of [null,{},[{title:'',url:reference.url}],[reference,reference],Array.from({length:9},(_,i)=>({title:'資料',url:'https://example.org/'+i})),[{...reference,token:'no'}]])assert.throws(()=>normalizeReferences(data));}); // 不要な機密用フィールドも受け入れません。
test('ホスト偽装をOneDriveと表示しない',()=>{assert.equal(referenceProvider('https://1drv.ms.evil.example.org/a'),'Webリンク');assert.equal(referenceProvider('https://drive.google.com/file/d/a'),'Google Drive');}); // 名称の部分一致では判定しません。
test('資料名をHTML実行せず外部リンクへ参照元を送らない',()=>{const html=referenceList([{title:'<img src=x onerror=alert(1)>',url:reference.url}]);assert(!html.includes('<img'));assert(html.includes('&lt;img'));assert(html.includes('rel="noopener noreferrer"'));assert(html.includes('referrerpolicy="no-referrer"'));}); // XSSと外部タブの参照を抑えます。
const connected={initialized:true,account:true,scope,storageScope:scope,connected:true,online:true}; // 許可される画面の基本条件です。
test('同期の待機状態でも追加可能',()=>assert.equal(referenceAccess(connected),'')); // 通信中の数秒だけに限定しません。
for(const change of [{initialized:false},{account:false},{connected:false},{online:false},{needsInteraction:true},{blocked:true},{error:true},{storageScope:'guest-local'}])test('追加拒否 '+JSON.stringify(change),()=>assert(referenceAccess({...connected,...change}))); // 接続条件を一つずつ検査します。
test('OneDrive未接続の直接保存も拒否',async t=>{const app=service(t);await assert.rejects(app.run('savePlan',{input:input()}),/OneDrive/);assert.equal(app.repo.operations().length,0);}); // 画面だけの制限にしません。
test('ゲストへの新規関連付けを拒否',async t=>{const app=service(t,true,'guest-local');await assert.rejects(app.run('savePlan',{input:input()}),/OneDrive/);}); // 別の保存領域へ混ぜません。
test('接続確認後にメタデータだけ保存',async t=>{const app=service(t,true);const saved=await app.run('savePlan',{input:input()});assert.equal(app.checks,1);assert.deepEqual(saved.operation.body.payload.items[0].references,[reference]);assert.deepEqual(Object.keys(saved.operation.body.payload.items[0].references[0]),['title','url']);}); // 実体・ダウンロードURL・認証情報は格納しません。
test('接続確認失敗なら入力参照を保存せず拒否',async t=>{const app=service(t,true);app.cloud.check=async()=>{throw new Error('模擬の通信切断');};await assert.rejects(app.run('savePlan',{input:input()}),/通信切断/);assert.equal(app.repo.operations().length,0);}); // 部分保存を残しません。
test('同期エラーと保護停止では関連付け拒否',async t=>{for(const key of ['lastError','blocked']){const app=service(t,true);app.repo.setMeta(key,'error');await assert.rejects(app.run('referenceConnection'),/同期の問題/);}}); // エラー表示を成功と扱いません。
test('通常プランは未接続でも保存可能',async t=>{const app=service(t,false,'guest-local'),data=input();delete data.items[0].references;const out=await app.run('savePlan',{input:data});assert.deepEqual(out.operation.body.payload.items[0].references,[]);}); // メディアなしの既存利用を妨げません。
async function seed(t){const app=service(t,true);const data=await app.run('savePlan',{input:input()});const detail=await app.run('detail',{revisionId:data.operation.body.opId});return {app,data,detail};} // コピー用の同一アカウントの原本です。
test('コピーで参照を保持し原本・実績は変更しない',async t=>{const {app,data,detail}=await seed(t);await app.run('record',{revisionId:data.operation.body.opId,kind:'reflection',note:'原本だけの記録'});app.engine=null;app.cloud=null;const draft={...detail.operation.body.payload,title:'コピー',items:rowsFromDetail(detail,true)};const copy=await app.run('savePlan',{input:draft});assert.notEqual(copy.operation.body.entityId,data.operation.body.entityId);assert.deepEqual(copy.operation.body.payload.items[0].references,[reference]);assert.deepEqual(app.repo.getOp(data.operation.body.opId),data.operation);assert(app.repo.state().records.every(o=>o.body.payload.practiceRevision===data.operation.body.opId));}); // 既存参照のコピーは新規ファイル取込とは区別します。
test('コピーで条件変更・参照解除しても元を保持',async t=>{const {app,data,detail}=await seed(t);const rows=rowsFromDetail(detail,true);rows[0].pinned=null;rows[0].references=[];rows[0].rule='新条件';const copy=await app.run('savePlan',{input:{...detail.operation.body.payload,title:'編集コピー',items:rows}});assert.deepEqual(copy.operation.body.payload.items[0].references,[]);assert.deepEqual(app.repo.getOp(data.operation.body.opId).body.payload.items[0].references,[reference]);}); // 解除を消去や全体書換えへしません。
test('既存URLでも別アカウントでは接続確認が必要',async t=>{const {detail}=await seed(t);const other=service(t,false,'ms-'+'b'.repeat(64));await assert.rejects(other.run('savePlan',{input:{...input(),items:rowsFromDetail(detail,true)}}),/OneDrive/);}); // 個人間の許可を流用しません。
test('新しいURLへ変更したら再度接続確認する',async t=>{const {app,detail}=await seed(t);const rows=rowsFromDetail(detail,true);rows[0].references[0].url='https://example.org/changed';app.cloud=null;await assert.rejects(app.run('savePlan',{input:{...input(),items:rows}}),/OneDrive/);}); // 保存済みURLのコピー条件だけを適用します。
test('リンクを含むバックアップを復元し再利用',async t=>{const {app}=await seed(t);const backup=await app.run('backup'),other=service(t);await other.run('restore',{backup,confirm:true});assert.equal(other.repo.operations().length,1);assert.deepEqual(other.repo.operations()[0].body.payload.items[0].references,[reference]);assert.equal(hasNewReferences(input(),other.repo.operations()),false);}); // バックアップにリンクの文字列を保持します。
test('参考資料だけ異なるメニューは別の候補',async t=>{const {app,detail}=await seed(t);const rows=rowsFromDetail(detail,true);rows[0].references=[];await app.run('savePlan',{input:{...input(),title:'資料なし',items:rows}});assert.equal(menuChoices(app.repo.state().practices).length,2);}); // 検索で一方の資料を落としません。
test('不正な参照は保存前に行番号付きで表示',()=>{const data=input();data.items[0].references[0].url='file:///no';assert(draftErrors(data).some(x=>x.field==='references'&&x.index===0));}); // フォームの値を消さず案内できます。
