import {normalizeReferences,referenceProvider,referenceUrl,MAX_REFERENCES} from './references.mjs'; // 検査済みのリンクだけを画面へ出します。
import {escapeHtml as e} from './ui.mjs'; // 資料名をHTMLとして実行しません。
export function referenceList(value,editable=false,rowIndex=0){ // 本体の取得・埋込み・サムネイル読込は行いません。
  const refs=normalizeReferences(value);if(!refs.length)return '<p class="reference-help">まだ参考資料はありません。</p>'; // 空の欄も説明します。
  return '<ul class="reference-list">'+refs.map((ref,index)=>`<li><div><strong>${e(ref.title)}</strong><small>${e(referenceProvider(ref.url))} · ${e(new URL(ref.url).hostname)}</small><a href="${e(ref.url)}" target="_blank" rel="noopener noreferrer" referrerpolicy="no-referrer">元のサービスで開く ↗</a></div>${editable?`<button type="button" data-reference-remove="${rowIndex}:${index}" aria-label="参考資料${index+1}を外す">外す</button>`:''}</li>`).join('')+'</ul>'; // 明示クリックでだけ外部サービスへ移動します。
} // 安全なリンク一覧を閉じます。
export function referenceEditor(row,index){const refs=normalizeReferences(row.references??row.pinned?.references);return `<details class="reference-section" data-reference-section="${e(row.id)}"><summary>参考資料${refs.length?' · '+refs.length+'件':'（任意）'}</summary>${referenceList(refs,true,index)}<button type="button" class="field-search" data-reference-add="${index}">＋ リンクを追加</button><small class="reference-help" data-reference-hint></small></details>`;} // 使わない時は折りたたんで場所を取りません。
export function referenceDetail(item){const refs=normalizeReferences(item.references);return refs.length?`<details class="reference-section"><summary>参考資料 · ${refs.length}件</summary>${referenceList(refs)}</details>`:'';} // 保存済みの詳細でも同じ参照を表示します。
export function createReferenceDialog({authorize,onAdded,reason}){ // 画面と保存層の両方で新規登録を制限します。
  const dialog=document.createElement('dialog');dialog.className='reference-dialog';dialog.setAttribute('aria-labelledby','referenceDialogTitle'); // 他の検索画面と識別子を分けます。
  dialog.innerHTML='<h2 id="referenceDialogTitle">参考資料のリンクを追加</h2><p class="reference-help">OneDrive・Google Drive・Dropbox・iCloud Drive・YouTube・Web資料のHTTPSリンクを登録します。ファイル本体の取込や公開権限の変更は行いません。</p><form novalidate><label>資料名（任意）<input name="referenceTitle" maxlength="160" placeholder="例：フットワークのお手本"></label><label>閲覧用リンク<input name="referenceUrl" type="url" inputmode="url" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="2048" required placeholder="https://…"></label><p class="reference-help">閲覧には参照先の権限が必要です。全員公開にする必要はありません。リンク情報は練習と一緒に保存・同期します。</p><p class="reference-dialog-error" role="alert"></p><div class="actions"><button type="button" data-reference-cancel>キャンセル</button><button type="submit" class="primary">追加</button></div></form>'; // 接続先を自動訪問する機能はありません。
  document.body.append(dialog);const form=dialog.querySelector('form'),submit=form.querySelector('[type=submit]'),error=dialog.querySelector('[role=alert]');let current=null,busy=false; // 一時入力はDBに保存しません。
  const cancel=()=>{if(!busy){dialog.close();current=null;}};dialog.querySelector('[data-reference-cancel]').onclick=cancel;dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();else current=null;}); // 読取確認中の二重操作を止めます。
  form.onsubmit=async event=>{event.preventDefault();if(busy||!current)return;const context=current;try{const why=reason();if(why)throw new Error(why);const url=referenceUrl(form.elements.referenceUrl.value);const title=form.elements.referenceTitle.value.trim()||new URL(url).hostname;const ref=normalizeReferences([{title,url}])[0];if((context.row.references||[]).length>=MAX_REFERENCES)throw new Error(`参考資料は${MAX_REFERENCES}件までです。`);normalizeReferences([...(context.row.references||[]),ref]);busy=true;submit.disabled=true;submit.textContent='接続を確認中…';await authorize(context);const changed=reason();if(changed)throw new Error(changed);await onAdded(context,ref);dialog.close();current=null;}catch(err){error.textContent=err.message||'追加できませんでした。';}finally{busy=false;submit.disabled=Boolean(reason());submit.textContent='追加';}}; // 接続確認後にも本人・メニューの一致を確認します。
  return {open(context){const why=reason();if(why)throw new Error(why);current=context;form.reset();error.textContent='';submit.disabled=false;dialog.showModal();form.elements.referenceUrl.focus();},refresh(){if(dialog.open&&!busy)submit.disabled=Boolean(reason());}}; // 状態変化があればダイアログ内も無効にします。
} // リンク入力画面を閉じます。
