import {chromium,webkit} from 'playwright'; // 実ブラウザで画面と保存を確認します。
import assert from 'node:assert/strict'; // 未確認の状態を成功としません。
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises'; // 合成データの検証結果だけを保存します。
import {join} from 'node:path'; // 証拠とブラウザを分離します。
import {tmpdir} from 'node:os'; // 他の端末の保存領域と分離します。
import {createServer} from './serve-project.mjs'; // 既存と同じサブパスでアプリを配信します。
const live=process.env.SITE_URL;let server,url=live;const results=[],errors=[];const reports=live?'reports/references-live':'reports/references';await mkdir(reports,{recursive:true}); // 公開前と実URLの結果を分けます。
if(live)assert.equal(live,'https://yuge-u.github.io/zero-one-practice-lab/');else{server=createServer();await new Promise(done=>server.listen(0,'127.0.0.1',done));url=`http://127.0.0.1:${server.address().port}/zero-one-practice-lab/`;} // 公開先を限定し本人クラウドは使いません。
const syntheticAuth=`export class Auth { // CI専用の架空アカウントです。
 constructor(){this.account={username:'synthetic@example.invalid'};this.client={};this.redirectUri=new URL('./',location.href).href;} // 本人トークンを取りません。
 async init(){} scope(){return 'ms-'+'a'.repeat(64);} async token(){return 'synthetic-not-a-real-token';} lastOfflineScope(){return null;} // 保存の本体は実SQLiteのままです。
}`; // 認証のみ合成し、HTTP通信と永続保存は実ブラウザを通します。
async function record(engine,name,fn){await fn();results.push({engine,name,pass:true});console.log('PASS',engine,name);} // 失敗時は以後を成功に数えません。
try{for(const [engine,type]of Object.entries({chromium,webkit})){ // 両エンジンで同じ画面遷移を検査します。
 const home=await mkdtemp(join(tmpdir(),'practice-save-status-'));const context=await type.launchPersistentContext(join(home,'profile'),{headless:true,serviceWorkers:"block",viewport:{width:390,height:844},hasTouch:true,env:{...process.env,HOME:home,CFFIXED_USER_HOME:home,XDG_DATA_HOME:join(home,'data'),XDG_CACHE_HOME:join(home,'cache'),XDG_CONFIG_HOME:join(home,'config')}}); // WebKitのOS共有保存も分離します。
 const files=new Map();const external=[];let folder=false,failure=false,hold=false;let releaseHold;let held=new Promise(done=>{releaseHold=done;});const meta=(name)=>({id:name,name,file:{},size:Buffer.byteLength(files.get(name)||'')}); // 合成OneDriveのファイルだけをメモリへ保管します。
 const setup=async ctx=>{await ctx.route('**/*',async route=>{ // ネイティブfetchの後段だけで合成Graph応答を返します。
  const request=route.request(),target=new URL(request.url()),local=new URL(url);const reply=(status,value)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value),headers:{'Access-Control-Allow-Origin':'*'}}); // 認証情報を外部へ転送しません。
  if(target.origin===local.origin){if(target.pathname===local.pathname+'auth.mjs')return route.fulfill({status:200,contentType:'text/javascript',body:syntheticAuth});return route.continue();} // 本体コード・SQLiteは通常の配信を使います。
  if(!['graph.microsoft.com','zero-one-synthetic.1drv.com'].includes(target.hostname)){external.push({url:target.href,headers:request.headers()});return route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><title>Synthetic reference</title><p>Public reference fixture</p>'});} // 未定義の外部宛先は拒否します。
  if(hold)await held;if(failure)return route.abort('failed'); // 長い同期と通信失敗を制御して表示を確認します。
  const path=decodeURIComponent(target.pathname);if(target.hostname==='zero-one-synthetic.1drv.com'){const name=path.slice(1);assert(!request.headers().authorization);if(!files.has(name))return reply(404,{});return route.fulfill({status:200,contentType:'application/json',body:files.get(name),headers:{'Access-Control-Allow-Origin':'*'}});} // 事前認証URLにBearerを送らないことも確認します。
  assert.equal(request.headers().authorization,'Bearer synthetic-not-a-real-token'); // 本人の秘密情報ではないことを保証します。
  if(path.endsWith('/special/approot'))return reply(200,{id:'root',folder:{}}); // アプリ領域の取得です。
  if(path.endsWith('/items/root/children')){if(request.method()==='POST'){folder=true;return reply(201,{id:'folder',folder:{}});}return reply(200,{value:folder?[{id:'folder',name:'ZERO_ONE_PRACTICE_LAB_V02',folder:{}}]:[]});} // 接続の明示同意と作成を再現します。
  if(path.endsWith('/items/folder/children'))return reply(200,{value:[...files.keys()].map(meta)}); // 保存した合成記録の一覧を返します。
  const match=/\/items\/folder:\/(.+?)(:\/content)?$/.exec(path);if(match){const name=match[1];if(match[2]&&request.method()==='PUT'){files.set(name,request.postData());return reply(201,meta(name));}return files.has(name)?reply(200,meta(name)):reply(404,{});} // 本体の保存形式で書込と読戻しを確認します。
  const name=path.split('/items/')[1];if(name&&files.has(name))return reply(200,{...meta(name),'@microsoft.graph.downloadUrl':'https://zero-one-synthetic.1drv.com/'+encodeURIComponent(name)}); // ハッシュ検証用の署名済みURLを模擬します。
  return reply(404,{}); // 不明な要求を成功に変えません。
 });};await setup(context); // 複数端末相当の同じ模擬クラウドを準備します。
 const extra=[];const page=await context.newPage();page.on('dialog',d=>d.accept());page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push({engine,message:e.message}));const title=()=>page.locator('#storageStatus').innerText();const waitTitle=text=>page.waitForFunction(text=>document.getElementById('storageStatus').textContent.includes(text),text,{timeout:20000});const saved=()=>page.waitForFunction(()=>document.getElementById('saveFeedback').textContent.includes('練習を保存しました'),null,{timeout:20000});const ops=()=>[...files.keys()].filter(k=>k.startsWith('O_')).length; // 表示と保存データを両方検査します。

 const ready=p=>p.waitForFunction(()=>document.getElementById('editorFields')&&!document.getElementById('editorFields').disabled); // SQLiteが実際に開くまで待ちます。
 const editor=()=>page.getByRole('button',{name:'練習をつくる',exact:true}).click(); // 編集画面を開きます。
 const open=async(p,title)=>{await p.getByRole('button',{name:'保存した練習',exact:true}).click();await p.locator('.saved-card').filter({has:p.getByRole('heading',{name:title,exact:true})}).locator('[data-open]').click();await p.waitForFunction(t=>document.getElementById('detailTitle').textContent===t&&!document.getElementById('detail').hidden,title);}; // 非同期の詳細表示完了を確認します。
 const add=async(address,name)=>{await page.locator('#items .reference-box').first().evaluate(e=>e.open=true);await page.locator('[data-reference-add]').first().click();await page.locator('#referenceUrl').fill(address);await page.locator('#referenceTitle').fill(name);await page.locator('#referenceApply').click();await page.waitForFunction(()=>!document.getElementById('referenceDialog').open);}; // 接続確認から参照反映まで実際のフォームを使います。
 const links=['https://example.com/instruction.pdf','https://1drv.ms/v/synthetic?e=test','https://drive.google.com/file/d/synthetic/view','https://youtu.be/synthetic?t=30']; // 公開しない合成リンクです。
 try{await page.goto(url);await ready(page); // 既存の本人領域と画面を開きます。
  await record(engine,'L01 未接続時はリンク追加不可',async()=>{await page.locator('#items .reference-box').evaluate(e=>e.open=true);assert.equal(await page.locator('[data-reference-add]').isDisabled(),true);assert.equal(await page.locator('#players').inputValue(),'15');assert.equal(await page.locator('#totalMinutes').inputValue(),'180');}); // 人数・時間の初期値も維持します。
  await page.locator('#quickConnect').click();await waitTitle('✓ OneDrive接続済み'); // 架空の本人クラウドへ接続します。
  await record(engine,'L02 接続後は新規追加可能',async()=>assert.equal(await page.locator('[data-reference-add]').isEnabled(),true)); // 認証だけでなくクラウド接続を要求します。
  await page.locator('#title').fill('資料付き原本');await page.locator('#goal').fill('足運びを確かめる');await page.locator('[data-field="name"]').fill('フットワーク');await page.locator('[data-field="category"]').fill('フットワーク'); // 合成の練習を入力します。
  await page.locator('[data-reference-add]').click();await page.locator('#referenceUrl').fill('javascript:alert(1)');await page.locator('#referenceApply').click(); // 不正な参照先は入力段階で拒否します。
  await record(engine,'L03 不正URLは拒否して追加しない',async()=>{assert.match(await page.locator('#referenceError').innerText(),/HTTPS/);assert.equal(await page.locator('#items .reference-list li').count(),0);assert.equal(external.length,0);}); // 自動アクセスがないことも検証します。
  await page.locator('#referenceUrl').fill(links[0]);await page.locator('#closeReference').click();await record(engine,'L04 キャンセルは関連付けを作らない',async()=>assert.equal(await page.locator('#items .reference-list li').count(),0)); // 途中入力を勝手に保存しません。
  for(const [i,link]of links.entries())await add(link,['足運びのお手本','OneDriveの動画','Driveの解説','開始位置つき動画'][i]); // 各サービスの閲覧リンクを登録します。
  await record(engine,'L05 複数資料を入力しても未保存',async()=>{assert.equal(await page.locator('#items .reference-list li').count(),4);assert.equal(ops(),0);assert.equal(external.length,0);assert.equal(await page.locator('#draftSyncHint').isVisible(),true);}); // 追加は外部参照先へのアップロードではありません。
  await page.locator('#savePlan').click();await saved();await waitTitle('✓ OneDrive同期済み'); // 計画と一緒にリンク情報を同期します。
  const original=[...files.values()].map(v=>JSON.parse(v)).find(v=>v.body?.kind==='practice'); // 原本の固定版を保存します。
  await record(engine,'L06 リンク情報だけが保存・同期される',async()=>{assert.equal(original.body.payload.items[0].references.length,4);assert.deepEqual(original.body.payload.items[0].references.map(r=>r.url),links);assert.equal(external.length,0);assert([...files.keys()].every(k=>k.endsWith('.data')));}); // ファイル本体をクラウドへ複製しません。
  await page.reload();await ready(page);await waitTitle('✓ OneDrive同期済み');await open(page,'資料付き原本'); // 再起動しても参照が残ります。
  await record(engine,'L07 再読込・詳細で安全なリンクを保持',async()=>{const anchors=page.locator('#detailItems .reference-list a');assert.equal(await anchors.count(),4);assert.equal(await anchors.first().getAttribute('href'),links[0]);assert.equal(await anchors.first().getAttribute('rel'),'noopener noreferrer');assert.equal(await anchors.first().getAttribute('referrerpolicy'),'no-referrer');assert.equal(external.length,0);}); // 閲覧前に外部データを先読みしません。
  await page.locator('#detailItems .reference-box').evaluate(e=>e.open=true);const popupPromise=context.waitForEvent('page');await page.locator('#detailItems .reference-list a').first().click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded'); // 明示操作だけで外部画面を開きます。
  await record(engine,'L08 開く操作時も認証情報と参照元を送らない',async()=>{assert.equal(external.length,1);assert.equal(external[0].url,links[0]);assert(!external[0].headers.authorization);assert(!external[0].headers.referer);assert.equal(await popup.evaluate(()=>window.opener),null);});await popup.close(); // 外部ページから元アプリを操作できません。
  await page.locator('#copyPlan').click();await page.waitForFunction(()=>document.getElementById('title').value.endsWith('（コピー）'));await page.locator('[data-field="rule"]').fill('コピー先だけ条件変更'); // 固定版を外す編集を含めて確認します。
  await record(engine,'L09 計画コピーと条件変更でも資料を保持',async()=>assert.equal(await page.locator('#items .reference-list li').count(),4)); // 元の資料参照を欠落させません。
  await page.locator('#savePlan').click();await saved();await waitTitle('✓ OneDrive同期済み');await open(page,'資料付き原本'); // 原本を読み戻します。
  await record(engine,'L10 コピー保存後も原本は不変',async()=>{assert.equal(await page.locator('#detailItems .reference-list li').count(),4);assert(!await page.locator('#detailItems').innerText().then(t=>t.includes('コピー先だけ条件変更')));assert.equal(await page.locator('.saved-card').count(),2);}); // 原本とコピーを別々に保存します。
  await editor();await page.locator('#newPlan').click();await page.locator('#title').fill('メニュー再利用');await page.locator('#goal').fill('次回も使う');await page.locator('#addPastMenu').click();await page.locator('#pickerFilter').selectOption('フットワーク');await page.locator('.picker-option').first().click();await page.waitForFunction(()=>!document.getElementById('searchPicker').open); // 保存済みの個別メニューも再利用します。
  await record(engine,'L11 メニュー再利用で全資料をコピー',async()=>assert.equal(await page.locator('#items .reference-list li').count(),4)); // 選択後に資料が付くことを確認します。
  await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false});window.dispatchEvent(new Event('offline'));});await page.locator('#items .reference-box').evaluate(e=>e.open=true); // オフラインの表示イベントを合成します。
  await record(engine,'L12 切断時は新規変更不可・解除は可能',async()=>{assert.equal(await page.locator('[data-reference-add]').isDisabled(),true);assert.equal(await page.locator('[data-reference-edit]').first().isDisabled(),true);await page.locator('[data-reference-remove]').first().click();assert.equal(await page.locator('#items .reference-list li').count(),3);}); // 元ファイルを削除せず参照だけ外します。
  await page.locator('#savePlan').click();await saved();await page.evaluate(()=>{delete navigator.onLine;window.dispatchEvent(new Event('online'));});await waitTitle('✓ OneDrive同期済み'); // 参照の解除は通常の計画として同期します。
  await record(engine,'L13 オフライン編集から復帰して同期',async()=>{assert.equal(await page.locator('.saved-card').count(),3);const stored=[...files.values()].map(v=>JSON.parse(v)).find(v=>v.body?.opId===original.body.opId);assert.deepEqual(stored,original);}); // 元の不変データを再確認します。
  const h=await mkdtemp(join(tmpdir(),'practice-reference-other-'));const other=await type.launchPersistentContext(join(h,'profile'),{headless:true,serviceWorkers:'block',viewport:{width:390,height:844},env:{...process.env,HOME:h,CFFIXED_USER_HOME:h,XDG_DATA_HOME:join(h,'data'),XDG_CACHE_HOME:join(h,'cache'),XDG_CONFIG_HOME:join(h,'config')}});extra.push(other);await setup(other);const second=await other.newPage();await second.goto(url);await ready(second);await second.waitForFunction(()=>document.getElementById('storageStatus').textContent.includes('✓ OneDrive同期済み'));await open(second,'資料付き原本'); // 独立した保存領域で同じ模擬クラウドを受信します。
  await record(engine,'L14 別端末相当で資料を受信する',async()=>{assert.equal(await second.locator('#detailItems .reference-list li').count(),4);assert.equal(await second.locator('#detailItems .reference-list a').last().getAttribute('href'),links[3]);}); // 実PC・iPhoneの試験とは区別します。
  failure=true;await page.locator('[data-reference-add]').click();await page.locator('#referenceUrl').fill('https://example.com/new.pdf');await page.locator('#referenceApply').click();await page.waitForFunction(()=>document.getElementById('referenceError').textContent.length>0); // 接続確認時の失敗を起こします。
  await record(engine,'L15 接続確認失敗は追加せず入力を残す',async()=>{assert.equal(await page.locator('#referenceUrl').inputValue(),'https://example.com/new.pdf');assert.equal(await page.locator('#items .reference-list li').count(),3);});failure=false;await page.locator('#closeReference').click(); // 再試行用に通信だけを戻します。
  await page.locator('#syncNow').click();await waitTitle('✓ OneDrive同期済み');await add('https://example.com/new.pdf','受入後に切断');await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false});window.dispatchEvent(new Event('offline'));});await page.locator('#savePlan').click();await saved(); // 接続中に受入済みの資料は切断後も保持します。
  await record(engine,'L16 追加後の切断でも計画保存を失わない',async()=>{assert.equal(await page.locator('#items .reference-list li').count(),4);assert.match(await title(),/オフライン/);}); // 追加時と保存時の状態を混同しません。
  await page.evaluate(()=>{delete navigator.onLine;window.dispatchEvent(new Event('online'));});await waitTitle('✓ OneDrive同期済み'); // 完了を確認してから画面を記録します。
  await record(engine,'L17 小さい画面で表示を維持',async()=>{for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));}await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(reports,engine+'-references.png'),fullPage:true});}); // 長いリンクやボタンで横にはみ出さないことを確認します。
 }catch(error){errors.push({engine,message:error.message});await page.screenshot({path:join(reports,engine+'-failure.png'),fullPage:true}).catch(()=>{});}finally{for(const c of extra)await c.close();await context.close();} // 失敗時も証拠と終了処理を残します。
}}finally{if(server){server.closeAllConnections();await new Promise(done=>server.close(done));}const passed=results.length===34&&errors.length===0;await writeFile(join(reports,'results.json'),JSON.stringify({version:'1.2.1',results,errors,passed,realMicrosoft:false,physicalIPhone:false,network:'real SQLite and native fetch; synthetic Auth/Graph/external reference responses',serviceWorkers:'blocked only in Auth fixture suite; original real-SW tests retained'},null,2));if(!passed)process.exitCode=1;} // 未実行や不合格を成功扱いしません。
