import {chromium,webkit} from 'playwright'; // 実ブラウザで新しい検索と接続を検査します。
import assert from 'node:assert/strict'; // 実画面と保存結果を照合します。
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises'; // 人工の検証証拠だけを保存します。
import {join} from 'node:path'; // 保存先を限定します。
import {tmpdir} from 'node:os'; // OSの共有領域も分離します。
import {createServer} from './serve-project.mjs'; // 本番と同じパス構造で配信します。
const live=process.env.SITE_URL,reports=live?'reports/references-live':'reports/references',results=[],errors=[];let server,url=live;await mkdir(reports,{recursive:true}); // 公開前後の証拠を分けます。
if(live)assert.equal(url,'https://yuge-u.github.io/zero-one-practice-lab/');else{server=createServer();await new Promise(done=>server.listen(0,'127.0.0.1',done));url=`http://127.0.0.1:${server.address().port}/zero-one-practice-lab/`;} // 本人のOneDriveへは接続しません。
const fakeMSAL=`globalThis.msal={PublicClientApplication:class{constructor(config){this.config=config;this.store=config.cache.cacheLocation==='localStorage'?localStorage:sessionStorage;}async initialize(){}async handleRedirectPromise(){if(sessionStorage.getItem('test-return')){sessionStorage.removeItem('test-return');return {account:this.getAllAccounts()[0]};}return null;}getAllAccounts(){return this.store.getItem('test-account')?[{homeAccountId:'synthetic-account',username:'synthetic@example.invalid'}]:[];}setActiveAccount(a){this.active=a;}async loginRedirect(args){if(args.prompt)throw Error('Unexpected forced prompt');this.store.setItem('test-account','1');localStorage.setItem('test-login-count',String(Number(localStorage.getItem('test-login-count')||0)+1));sessionStorage.setItem('test-return','1');location.assign(this.config.auth.redirectUri);await new Promise(()=>{});}async acquireTokenSilent(args){return {accessToken:'synthetic-not-a-real-token',account:args.account};}async logoutRedirect(){this.store.removeItem('test-account');location.assign(this.config.auth.postLogoutRedirectUri);}}};`; // 認証クラス本体は実物、Microsoft SDKの外部認証結果だけを合成します。
async function record(engine,name,fn){await fn();results.push({engine,name,status:'pass'});console.log('PASS',engine,name);} // 未実行を合格へ数えません。
async function contextFor(type){const home=await mkdtemp(join(tmpdir(),'practice-catalog-'));return type.launchPersistentContext(join(home,'profile'),{headless:true,serviceWorkers:"block",viewport:{width:390,height:844},hasTouch:true,env:{...process.env,HOME:home,CFFIXED_USER_HOME:home,XDG_DATA_HOME:join(home,'data'),XDG_CACHE_HOME:join(home,'cache'),XDG_CONFIG_HOME:join(home,'config')}});} // 物理iPhoneとは区別します。
const ready=page=>page.waitForFunction(()=>document.getElementById('editorFields')&&!document.getElementById('editorFields').disabled,null,{timeout:30000}); // SQLiteの準備完了を待ちます。
const saved=page=>page.waitForFunction(()=>document.getElementById('saveFeedback').textContent.includes('練習を保存しました'),null,{timeout:20000}); // 書込応答を確認します。
const synced=page=>page.waitForFunction(()=>document.getElementById('storageStatus').textContent.includes('OneDrive同期済み'),null,{timeout:30000}); // クラウドの再読込まで待ちます。
try{for(const [engine,type]of Object.entries({chromium,webkit})){const contexts=[];const files=new Map();let folder=false,cloudFailure=false;const outsideRequests=[];const meta=name=>({id:name,name,file:{},size:Buffer.byteLength(files.get(name)||'')}); // 両端末が同じ合成クラウドを使います。
  async function setup(context){contexts.push(context);await context.route('**/*',async route=>{const req=route.request(),target=new URL(req.url()),local=new URL(url);const reply=(status,value)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value),headers:{'Access-Control-Allow-Origin':'*'}}); // ネイティブfetchの後段にHTTP応答を与えます。
    if(target.origin===local.origin){if(target.pathname.endsWith('/vendor/msal-browser.min.js'))return route.fulfill({status:200,contentType:'text/javascript',body:fakeMSAL});return route.continue();} // 検索・Auth・SQLiteは公開本体を使います。
    if(!['graph.microsoft.com','zero-one-synthetic.1drv.com'].includes(target.hostname)){outsideRequests.push({url:req.url(),headers:req.headers()});return route.fulfill({status:200,contentType:'text/html',body:'<p>外部参照先の合成応答</p>'});}if(cloudFailure)return route.abort();const path=decodeURIComponent(target.pathname); // 個人データの送信先を持ちません。
    if(target.hostname==='zero-one-synthetic.1drv.com'){assert(!req.headers().authorization);const name=path.slice(1);return files.has(name)?route.fulfill({status:200,contentType:'application/json',body:files.get(name),headers:{'Access-Control-Allow-Origin':'*'}}):reply(404,{});} // ダウンロードURLへBearerを送りません。
    assert.equal(req.headers().authorization,'Bearer synthetic-not-a-real-token');if(path.endsWith('/special/approot'))return reply(200,{id:'root',folder:{}}); // 本人トークンではないことを保証します。
    if(path.endsWith('/items/root/children')){if(req.method()==='POST'){folder=true;return reply(201,{id:'folder',folder:{}});}return reply(200,{value:folder?[{id:'folder',name:'ZERO_ONE_PRACTICE_LAB_V02',folder:{}}]:[]});} // 明示した初回接続だけでフォルダーを作ります。
    if(path.endsWith('/items/folder/children'))return reply(200,{value:[...files.keys()].map(meta)});const match=/\/items\/folder:\/(.+?)(:\/content)?$/.exec(path); // 保存済みファイルを返します。
    if(match){const name=match[1];if(match[2]&&req.method()==='PUT'){files.set(name,req.postData());return reply(201,meta(name));}return files.has(name)?reply(200,meta(name)):reply(404,{});} // 保存後に同じ内容を読み戻せます。
    const name=path.split('/items/')[1];return name&&files.has(name)?reply(200,{...meta(name),'@microsoft.graph.downloadUrl':'https://zero-one-synthetic.1drv.com/'+encodeURIComponent(name)}):reply(404,{}); // 不明な要求を成功へ変えません。
  });} // 合成通信の設定を閉じます。
  const context=await contextFor(type);await setup(context);const page=await context.newPage();page.setDefaultTimeout(20000);page.on('dialog',dialog=>dialog.accept());page.on('pageerror',error=>errors.push({engine,error:error.message}));const events=[];page.on('console',message=>events.push({type:message.type(),text:message.text()}));page.on('framenavigated',frame=>{if(frame===page.mainFrame())events.push({navigation:frame.url()});}); // 確認ダイアログもテストで操作します。
  const section=()=>page.locator('#items .reference-section').first(); // 編集中の先頭メニューの参考資料欄です。
  async function openSection(){if(!await section().evaluate(node=>node.open))await section().locator('summary').click();} // 必要な時だけ欄を開きます。
  async function addLink(title,link){await openSection();await page.locator('[data-reference-add]').first().click();await page.locator('[name=referenceTitle]').fill(title);await page.locator('[name=referenceUrl]').fill(link);await page.locator('.reference-dialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('.reference-dialog').open);} // 本番の接続確認と追加処理を実行します。
  async function openPlan(target,name){await target.getByRole('button',{name:'保存した練習',exact:true}).click();await target.locator('.saved-card').filter({has:target.getByRole('heading',{name,exact:true})}).locator('[data-open]').click();await target.waitForFunction(()=>!document.getElementById('detail').hidden);} // 指定した原本・コピーだけを開きます。
  try{await page.goto(url);await ready(page); // 最初はゲストのブラウザです。
    await record(engine,'L01 未接続はリンク追加不可・通常初期値を維持',async()=>{await openSection();assert(await page.locator('[data-reference-add]').isDisabled());assert.equal(await page.locator('#players').inputValue(),'15');assert.equal(await page.locator('#totalMinutes').inputValue(),'180');assert.equal(await page.locator('[type=file][accept*=image]').count(),0);}); // 写真取込用の入力を作っていません。
    await record(engine,'L02 参考資料なしのゲスト保存は継続可能',async()=>{await page.locator('#title').fill('ゲストの通常練習');await page.locator('#goal').fill('ゲストの目標');await page.locator('[data-field=name]').fill('準備運動');await page.locator('#savePlan').click();await saved(page);assert.equal(await page.locator('.saved-card').count(),1);}); // オフライン型の既存利用を維持します。
    await record(engine,'L03 本人OneDrive接続後だけ追加可能',async()=>{await page.locator('#quickConnect').click();await page.waitForFunction(()=>document.getElementById('storageStatus').textContent.includes('✓ OneDrive接続済み'));await openSection();assert(await page.locator('[data-reference-add]').isEnabled());assert.equal(await page.locator('.saved-card').count(),0);}); // ゲストデータは本人領域へ送信しません。
    await page.locator('#title').fill('リンク原本');await page.locator('#goal').fill('資料を見て判断する');await page.locator('[data-field=name]').fill('資料付きステップ');await page.locator('[data-field=category]').fill('フットワーク'); // 合成の新規プランを用意します。
    await record(engine,'L04 実行形式URLを追加しない',async()=>{await page.locator('[data-reference-add]').click();await page.locator('[name=referenceUrl]').fill('javascript:alert(1)');await page.locator('.reference-dialog [type=submit]').click();await page.waitForFunction(()=>document.querySelector('.reference-dialog-error').textContent.length>0);assert.equal(await page.locator('#items .reference-list li').count(),0);await page.locator('[data-reference-cancel]').click();}); // 不正なリンクは保存・遷移しません。
    await record(engine,'L05 YouTubeの参照を追加しても本体を取得しない',async()=>{await addLink('お手本動画','https://youtu.be/coach-demo?t=15');assert.equal(await page.locator('#items .reference-list li').count(),1);assert.equal(outsideRequests.length,0);assert.equal([...files.keys()].filter(k=>k.startsWith('O_')).length,0);}); // 追加と練習の保存を区別します。
    await record(engine,'L06 Google Driveリンクと重複入力を扱う',async()=>{await addLink('説明写真','https://drive.google.com/file/d/practice-demo/view');await page.locator('[data-reference-add]').click();await page.locator('[name=referenceUrl]').fill('https://drive.google.com/file/d/practice-demo/view');await page.locator('.reference-dialog [type=submit]').click();await page.waitForFunction(()=>document.querySelector('.reference-dialog-error').textContent.includes('同じリンク'));await page.locator('[data-reference-cancel]').click();assert.equal(await page.locator('#items .reference-list li').count(),2);}); // 同じ資料を二重登録しません。
    await record(engine,'L07 接続確認に失敗したら新規関連付けを停止',async()=>{cloudFailure=true;await page.locator('[data-reference-add]').click();await page.locator('[name=referenceUrl]').fill('https://example.org/another.pdf');await page.locator('.reference-dialog [type=submit]').click();await page.waitForFunction(()=>document.querySelector('.reference-dialog-error').textContent.length>0);cloudFailure=false;await page.locator('[data-reference-cancel]').click();assert.equal(await page.locator('#items .reference-list li').count(),2);}); // 既に入力した参照や本文は保持します。
    await record(engine,'L08 オフラインでは追加不可・既存入力は保持',async()=>{await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false});window.dispatchEvent(new Event('offline'));});assert(await page.locator('[data-reference-add]').isDisabled());assert.equal(await page.locator('#items .reference-list li').count(),2);await page.evaluate(()=>{delete navigator.onLine;window.dispatchEvent(new Event('online'));});await page.waitForFunction(()=>!document.querySelector('[data-reference-add]').disabled);}); // 物理回線でなく状態イベントの試験です。
    await record(engine,'L09 練習保存で参照メタデータを同期',async()=>{await page.locator('#savePlan').click();await saved(page);await synced(page);const ops=[...files.values()].map(raw=>{try{return JSON.parse(raw);}catch{return {};}}).filter(o=>o.body?.kind==='practice');assert.equal(ops.length,1);assert.equal(ops[0].body.payload.items[0].references.length,2);assert.deepEqual(Object.keys(ops[0].body.payload.items[0].references[0]),['title','url']);assert.equal(outsideRequests.length,0);}); // 写真・動画本体をOneDriveへ送る処理はありません。
    await record(engine,'L10 再読込後に元の参照を表示',async()=>{await page.reload();await ready(page);await synced(page);await openPlan(page,'リンク原本');assert.equal(await page.locator('#detailItems .reference-list li').count(),2);await page.locator('#reflection').fill('原本の振り返り');await page.locator('#saveReflection').click();await page.waitForFunction(()=>document.getElementById('records').textContent.includes('原本の振り返り'));}); // 本人認証と実SQLiteを通します。
    await record(engine,'L11 全体コピー後の参照解除は原本を変えない',async()=>{await page.locator('#copyPlan').click();await page.waitForFunction(()=>document.getElementById('draftMode').textContent.includes('コピーから'));await openSection();assert.equal(await page.locator('#items .reference-list li').count(),2);await page.locator('[data-reference-remove]').first().click();await page.locator('#title').fill('リンクのコピー');await page.locator('[data-field=rule]').fill('コピーだけの条件');await page.locator('#savePlan').click();await saved(page);await synced(page);await openPlan(page,'リンク原本');assert.equal(await page.locator('#detailItems .reference-list li').count(),2);assert.match(await page.locator('#records').innerText(),/原本の振り返り/);}); // コピー側の削除を元資料の削除へ変えません。
    await record(engine,'L12 コピー先に振り返りは持ち込まない',async()=>{await openPlan(page,'リンクのコピー');assert.equal(await page.locator('#detailItems .reference-list li').count(),1);assert.equal(await page.locator('#records').innerText(),'');}); // 元の記録の紐付けを維持します。
    await record(engine,'L13 メニュー単位の再利用にも参照を引き継ぐ',async()=>{await page.getByRole('button',{name:'練習をつくる',exact:true}).click();await page.locator('#newPlan').click();await page.locator('[data-field=category]').fill('フットワーク');await page.locator('[data-menu-picker]').click();await page.locator('#pickerQuery').fill('リンク原本');await page.locator('.picker-option').first().click();await page.waitForFunction(()=>!document.getElementById('searchPicker').open);await openSection();assert.equal(await page.locator('#items .reference-list li').count(),2);}); // 過去の条件とともに資料を再利用します。
    await record(engine,'L14 リンクを開く操作だけで外部タブへ移動',async()=>{const popupWait=context.waitForEvent('page');await page.locator('#items .reference-list a').first().click();const popup=await popupWait;await popup.waitForLoadState();assert.match(popup.url(),/youtu\.be\/coach-demo\?t=15/);assert.equal(await popup.evaluate(()=>window.opener),null);assert.equal(outsideRequests.length,1);assert(!outsideRequests[0].headers.authorization);assert(!outsideRequests[0].headers.referer);await popup.close();}); // 外部応答は合成であり本人の資料を開いていません。
    await record(engine,'L15 別プロファイルにも参照が届く',async()=>{await page.locator('#newPlan').click();const other=await contextFor(type);await setup(other);const second=await other.newPage();await second.goto(url);await ready(second);await second.locator('#quickConnect').click();await synced(second);await openPlan(second,'リンク原本');assert.equal(await second.locator('#detailItems .reference-list li').count(),2);assert.equal(await second.locator('#detailItems .reference-list a').first().getAttribute('href'),'https://youtu.be/coach-demo?t=15');}); // 実OneDriveではなく合成Graph経由の別端末相当です。
    await record(engine,'L16 計画バックアップにリンク情報を保持',async()=>{await page.getByRole('button',{name:'接続・バックアップ',exact:true}).click();const download=page.waitForEvent('download');await page.locator('#backup').click();const file=await download;const raw=await (await import('node:fs/promises')).readFile(await file.path(),'utf8');const backup=JSON.parse(raw);assert(backup.body.operations.some(o=>o.body.kind==='practice'&&o.body.payload.items[0].references?.length===2));assert(!raw.includes('synthetic-not-a-real-token'));}); // 認証情報はバックアップへ混ぜません。
    await record(engine,'L17 既存参照のコピーはオフラインでも保存',async()=>{await openPlan(page,'リンク原本');await page.locator('#copyPlan').click();await page.waitForFunction(()=>document.getElementById('draftMode').textContent.includes('コピーから'));await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false});window.dispatchEvent(new Event('offline'));});await page.locator('#title').fill('オフラインのコピー');await page.locator('#savePlan').click();await saved(page);assert.equal(await page.locator('#items .reference-list li').count(),2);await page.evaluate(()=>{delete navigator.onLine;window.dispatchEvent(new Event('online'));});await synced(page);}); // 新しいURLを許可せず過去参照だけは保全します。
    await record(engine,'L18 折りたたみ表示と小画面の幅を確認',async()=>{await openSection();for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));}await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(reports,engine+'-references.png'),fullPage:true});assert.equal(outsideRequests.length,1);}); // 追加表示だけで元サービスへ通信していないことを再確認します。
  }catch(error){errors.push({engine,error:error.message,events,diagnostic:await page.evaluate(()=>({url:location.href,account:document.getElementById('accountLabel')?.textContent,notice:document.getElementById('notice')?.textContent,loginCount:localStorage.getItem('test-login-count'),testAccount:localStorage.getItem('test-account'),intent:sessionStorage.getItem('zero-one-practice-connect-intent'),returned:sessionStorage.getItem('test-return'),fakeSDK:String(msal?.PublicClientApplication).slice(0,160)})).catch(()=>null)});await page.screenshot({path:join(reports,engine+'-failure.png'),fullPage:true}).catch(()=>{});}finally{for(const context of contexts)await context.close();} // 不合格も証拠を残します。
}}finally{if(server){server.closeAllConnections();await new Promise(done=>server.close(done));}const passed=results.length===36&&errors.length===0;await writeFile(join(reports,'results.json'),JSON.stringify({version:'1.2.1',results,errors,passed,realMicrosoft:false,physicalIPhone:false,auth:'real Auth with simulated MSAL response',cloud:'native fetch with synthetic Graph HTTP',serviceWorkers:'blocked only for SDK-response fixtures; actual SW covered by existing offline/upgrade suites'},null,2));if(!passed)process.exitCode=1;} // 全シナリオ通過時だけ合格とします。
