import test from 'node:test'; // 参照だけの変更を既存保存処理と一緒に検証します。
import assert from 'node:assert/strict'; // 期待した値と実値を照合します。
import {DatabaseSync} from 'node:sqlite'; // メモリ内の実SQLiteを使います。
import {AppService} from '../web/core/service.mjs'; // 実際の保存処理を検査します。
import {makeReference,referenceUrl,validateReferences,referenceAccess,referenceKey} from '../web/reference-links.mjs'; // 参照専用の関数を使います。
import {draftErrors,rowsFromDetail} from '../web/draft.mjs'; // 画面入力と再利用を検査します。
import {NO_TERM,menuChoices} from '../web/catalog.mjs'; // 用語なしの休憩メニューにも対応させます。
import {seal,validateOperation} from '../web/core/model.mjs'; // 同期や復元で受け取るデータも検査します。
const scope='ms-'+'a'.repeat(64),otherScope='ms-'+'b'.repeat(64); // 架空の別アカウントを分離します。
const ref=(url='https://example.com/instruction.pdf',title='参考資料')=>makeReference({url,title}); // 実在の個人ファイルを使用しません。
const input=(references)=>({title:'参考資料テスト',goal:'動きを確認する',team:'U15',players:15,totalMinutes:180,items:[{name:'給水休憩',section:'BODY',category:'給水・休憩',minutes:5,term:NO_TERM,variationName:'',rule:'',...(references===undefined?{}:{references})}]}); // 本番と同じ構造の入力を作ります。
function service(t,account=scope){const app=new AppService(new DatabaseSync(':memory:'),account);t.after(()=>app.repo.close());return app;} // 試験ごとにデータを分けます。
function connect(app,fail=false){let calls=0;app.engine={};app.cloud={check:async()=>{calls++;if(fail)throw new Error('synthetic connection failed');}};return ()=>calls;} // 本人接続の読取確認だけを模擬します。
async function seed(t){const app=service(t);connect(app);const added=await app.run('referenceCheck',{input:ref()});const saved=await app.run('savePlan',{input:input([added.reference])});const detail=await app.run('detail',{revisionId:saved.operation.body.opId});return {app,saved,detail};} // 関連付けを承認してから保存します。
for(const url of ['https://1drv.ms/v/synthetic?e=test','https://onedrive.live.com/?id=TEST&authkey=TEST','https://drive.google.com/file/d/synthetic/view','https://www.dropbox.com/scl/fi/test/example.pdf?dl=0','https://www.icloud.com/iclouddrive/test','https://youtu.be/test?t=32','https://example.com/資料.pdf'])test('HTTPS閲覧リンク: '+url,()=>assert(referenceUrl(url).startsWith('https://'))); // 各サービスの通常リンクはそのまま保持します。
for(const url of ['javascript:alert(1)','data:text/html,test','file:///test','http://example.com','//example.com','https://user:secret@example.com/a','https://localhost/a','https://127.0.0.1/a','https://example.local/a','https://example.com/\nx','https://example.com\\evil','https://example.com/?access_token=secret','https://example.com/#id_token=secret'])test('登録拒否: '+url,()=>assert.throws(()=>referenceUrl(url))); // 実行スキームやローカルパス、認証応答を拒否します。
test('資料名省略はドメイン名になる',()=>assert.equal(ref('https://example.com','').title,'example.com')); // 入力を必要最小限にします。
test('クエリと再生位置を失わない',()=>assert.equal(referenceUrl('https://youtu.be/test?t=32#chapter'),'https://youtu.be/test?t=32#chapter')); // 動画の開始位置を保持します。
test('入力オブジェクトを変更しない',()=>{const a=ref();const before=JSON.stringify(a);validateReferences([a]);assert.equal(JSON.stringify(a),before);}); // コピー元への副作用を防ぎます。
test('古い省略フィールドを許可する',()=>assert.deepEqual(validateReferences(undefined),[])); // 既存の計画をそのまま読みます。
test('上限・重複・余分な項目を拒否する',()=>{assert.throws(()=>validateReferences(Array.from({length:9},(_,i)=>ref('https://example.com/'+i))));const a=ref();assert.throws(()=>validateReferences([a,{...a,id:crypto.randomUUID()}]));assert.throws(()=>validateReferences([{...a,token:'bad'}]));assert.throws(()=>validateReferences([{title:'x',url:a.url}]));}); // 保存データを参照情報に限定します。
const valid={initialized:true,connected:true,online:true,authenticated:true,scope}; // 同期待機中も許可する条件です。
test('本人接続済みなら追加可能',()=>assert.equal(referenceAccess(valid).allowed,true)); // 送受信が動く瞬間だけに限定しません。
for(const changed of [{initialized:false},{connected:false},{online:false},{authenticated:false},{scope:'guest-local'},{needsInteraction:true},{blocked:true},{error:true}])test('接続条件不一致で追加不可 '+JSON.stringify(changed),()=>assert.equal(referenceAccess({...valid,...changed}).allowed,false)); // 不足条件ごとに拒否します。
test('ゲストはUIを経由しなくても新規追加不可',async t=>{const app=service(t,'guest-local');connect(app);await assert.rejects(app.run('referenceCheck',{input:ref()}));await assert.rejects(app.run('savePlan',{input:input([ref()])}));assert.equal(app.repo.operations().length,0);}); // 保存層でも接続条件を守ります。
test('本人認証だけでは追加不可',async t=>{const app=service(t);await assert.rejects(app.run('referenceCheck',{input:ref()}));}); // OneDriveへの実接続と区別します。
test('接続確認失敗は許可を残さない',async t=>{const app=service(t);connect(app,true);const a=ref();await assert.rejects(app.run('referenceCheck',{input:a}));await assert.rejects(app.run('savePlan',{input:input([a])}));assert.equal(app.repo.operations().length,0);}); // 失敗を保存完了にしません。
test('確認済みリンクのみを保存する',async t=>{const {app,saved}=await seed(t);assert.equal(saved.operation.body.payload.items[0].references[0].url,'https://example.com/instruction.pdf');assert.equal(app.repo.state().pending,1);}); // 正常系の保存と送信待ちを確認します。
test('確認前の不正URLは通信しない',async t=>{const app=service(t),calls=connect(app);await assert.rejects(app.run('referenceCheck',{input:{title:'x',url:'file:///x'}}));assert.equal(calls(),0);}); // 貼付先を取得しようとしません。
test('受入後に切断しても保存できる',async t=>{const app=service(t);connect(app);const {reference}=await app.run('referenceCheck',{input:ref()});app.cloud=null;app.engine=null;const saved=await app.run('savePlan',{input:input([reference])});assert.equal(saved.operation.body.payload.items[0].references.length,1);}); // 追加済みの入力を切断で失わせません。
test('許可は別アカウントへ渡らない',async t=>{const {saved}=await seed(t);const other=service(t,otherScope);await assert.rejects(other.run('savePlan',{input:input(saved.operation.body.payload.items[0].references)}));}); // 同じURLでも別人の未確認追加を拒否します。
test('コピー編集解除で原本と振り返りを保持',async t=>{const {app,saved,detail}=await seed(t);await app.run('record',{revisionId:saved.operation.body.opId,kind:'reflection',note:'元の記録'});app.engine=null;app.cloud=null;const rows=rowsFromDetail(detail,true);assert.equal(rows[0].references.length,1);rows[0].references=[];rows[0].pinned=null;rows[0].name='変更した休憩';const copy=await app.run('savePlan',{input:{...detail.operation.body.payload,title:'コピー',items:rows}});assert.equal(copy.operation.body.payload.items[0].references.length,0);assert.deepEqual(app.repo.getOp(saved.operation.body.opId),saved.operation);assert.equal(app.repo.state().records[0].body.payload.note,'元の記録');}); // 元ファイルも削除する処理はありません。
test('資料付きコピーを接続なしで保存できる',async t=>{const {app,detail}=await seed(t);app.engine=null;app.cloud=null;app.referenceApprovals.clear();const rows=rowsFromDetail(detail,true);const copied=await app.run('savePlan',{input:{...detail.operation.body.payload,title:'次回',items:rows}});assert.equal(copied.operation.body.payload.items[0].references[0].url,rows[0].references[0].url);}); // 新規リンク入力と既存の再利用を区別します。
test('資料が違う同名メニューは別候補',async t=>{const {app,detail}=await seed(t);const {reference}=await app.run('referenceCheck',{input:ref('https://example.com/other.pdf')});const rows=rowsFromDetail(detail,true);rows[0].references=[reference];await app.run('savePlan',{input:{...detail.operation.body.payload,title:'条件違い',items:rows}});assert.equal(menuChoices(app.repo.state().practices).length,2);}); // 条件が同じでも資料違いを消しません。
test('同じ資料の複製候補は集約',()=>{const a=ref();assert.equal(referenceKey([a]),referenceKey([{...a,id:crypto.randomUUID()}]));}); // IDの違いだけでは重複候補を増やしません。
test('バックアップ復元でリンクだけを保持',async t=>{const {app,saved}=await seed(t);const backup=await app.run('backup');const restored=service(t);await restored.run('restore',{backup,confirm:true});assert.deepEqual(restored.repo.getOp(saved.operation.body.opId),saved.operation);assert(!JSON.stringify(backup).includes('synthetic connection'));}); // 実体や接続秘密情報は含めません。
test('不正参照を含む同期データを拒否',async t=>{const {saved}=await seed(t);const body=structuredClone(saved.operation.body);body.payload.items[0].references[0].url='javascript:alert(1)';assert.throws(()=>validateOperation(seal(body),scope));}); // ハッシュが正しくても危険なURLを受け入れません。
test('旧計画は無変換で保持し再利用',async t=>{const app=service(t);const saved=await app.run('savePlan',{input:input()});assert.equal('references'in saved.operation.body.payload.items[0],false);const old=JSON.stringify(app.repo.getOp(saved.operation.body.opId));const detail=await app.run('detail',{revisionId:saved.operation.body.opId});assert.deepEqual(rowsFromDetail(detail)[0].references,[]);assert.equal(JSON.stringify(app.repo.getOp(saved.operation.body.opId)),old);}); // 既存操作のハッシュを変えません。
test('休憩の資料なし入力は従来どおり有効',()=>assert.deepEqual(draftErrors(input()),[])); // 新しい必須欄は増やしません。
