import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CanvasPlayback,compileGroup,viewerSnapshot,hasCanvas} from '../web/canvas-playback.mjs';
import {canvasFixture,rawFixture} from '../tools/canvas-fixtures.mjs';

test('V01 保存原文・未知フィールドを変更せず別の表示コピーを作る',()=>{const data=canvasFixture(),before=JSON.stringify(data);const player=new CanvasPlayback(before);player.play();player.advance(30000);assert.equal(JSON.stringify(data),before);assert.deepEqual(player.compat.snapshot.unknownFutureField,{keep:true});});
test('V02 CANVASと同じ動作順・同時グループ・複数ボール',()=>{const player=new CanvasPlayback(rawFixture());const groups=player.compat.groups(player.step);assert.deepEqual(groups.map(g=>g.order),[1,2,3]);assert.equal(groups[0].items.length,3);const plan=compileGroup(player.compat,player.step,0),middle=plan.at(300);assert(middle.players.o1.y<690);assert(middle.balls.ball.x>350);assert(middle.balls['ball-two'].x<730);const end=plan.at(plan.duration);assert.deepEqual(end.players.o1,{x:430,y:550});assert.deepEqual(end.balls.ball,{x:710,y:600});assert.deepEqual(end.balls['ball-two'],{x:540,y:500});});
test('V03 ドリブルに対応するボールだけ追従する',()=>{const p=new CanvasPlayback(rawFixture());p.completed=1;const plan=compileGroup(p.compat,p.step,1),end=plan.at(plan.duration);assert.deepEqual(end.players.o2,{x:710,y:580});assert.deepEqual(end.balls.ball,{x:728,y:566});assert.deepEqual(end.balls['ball-two'],{x:540,y:500});});
test('V04 同一ボールの同じ動作番号も描画順で連続する',()=>{const p=new CanvasPlayback(rawFixture());p.select(1);const plan=compileGroup(p.compat,p.step,0);assert.deepEqual(plan.at(0).balls.ball,{x:450,y:520});const a=p.compat.duration(p.step.lines[0],p.compat.path({x:450,y:520},p.step.lines[0]));assert.deepEqual(plan.at(a+50).balls.ball,{x:525,y:350});assert.deepEqual(plan.at(plan.duration).balls.ball,{x:640,y:400});});
test('V05 一時停止は途中位置を保持し再開時も飛ばない',()=>{const p=new CanvasPlayback(rawFixture());p.play();p.advance(200);const pos=p.positions;p.pause();p.advance(5000);assert.deepEqual(p.positions,pos);assert.equal(p.elapsed,200);p.play();p.advance(100);assert.equal(p.elapsed,300);});
test('V06 コマ送りは1動作ずつ停止し前へ戻れる',()=>{const p=new CanvasPlayback(rawFixture());p.next();p.advance(10000);assert.equal(p.completed,1);assert.equal(p.running,false);p.previous();assert.equal(p.completed,0);assert.deepEqual(p.positions.players.o1,{x:330,y:690});});
test('V07 STEP境界のコマ送り・コマ戻し',()=>{const p=new CanvasPlayback(rawFixture());for(let i=0;i<3;i++){p.next();p.advance(10000);}p.next();assert.equal(p.stepIndex,1);assert.equal(p.completed,0);p.previous();assert.equal(p.stepIndex,0);assert.equal(p.completed,3);});
test('V08 連続再生は静的STEPも含め最後で止まる',()=>{const p=new CanvasPlayback(rawFixture());p.play();p.advance(30000);assert.equal(p.ended,true);assert.equal(p.running,false);assert.equal(p.stepIndex,2);p.play();assert.equal(p.stepIndex,0);assert.equal(p.completed,0);});
test('V09 繰り返し・速度変更・任意STEP選択',()=>{const p=new CanvasPlayback(rawFixture());p.loop=true;p.play();p.advance(30000);assert.equal(p.running,true);p.select(1);assert.equal(p.running,false);assert.equal(p.stepIndex,1);p.rate=2;p.play();p.advance(100);assert.equal(p.elapsed,200);p.reset();assert.equal(p.stepIndex,0);assert.equal(p.elapsed,0);});
test('V10 旧単一ボールとv7コート寸法を表示時のみ移行',()=>{const data={schemaVersion:7,courtMode:'half',steps:[{id:'s',players:[{id:'o1',side:'offense',x:640,y:380}],ball:{id:'ball',x:640,y:380},lines:[]}]};const p=new CanvasPlayback(JSON.stringify(data));assert.deepEqual(p.positions.players.o1,{x:525,y:490});assert.equal(p.step.balls.length,1);assert.equal(data.steps[0].players[0].x,640);});
test('V11 回転方向・オールコートの寸法を保持',()=>{const p=new CanvasPlayback(JSON.stringify(canvasFixture(90)));assert.deepEqual(p.compat.dimensions(),{width:1100,height:1170});const data=canvasFixture();data.snapshot.courtMode='full';const full=new CanvasPlayback(JSON.stringify(data));assert.deepEqual(full.compat.dimensions(),{width:1240,height:720});});
test('V12 動作順未設定の旧線をCANVASの初期順へ補完',()=>{const data=canvasFixture();for(const line of data.snapshot.steps[0].lines)delete line.playOrder;const p=new CanvasPlayback(JSON.stringify(data));assert.equal(p.compat.groups(p.step)[0].items.length,4);});
test('V13 CANVAS未取込・新形式・危険な座標は保存を変更せず表示だけを止める',()=>{assert.equal(hasCanvas(JSON.stringify({zeroOneNoDiagram:true})),false);assert.throws(()=>new CanvasPlayback(JSON.stringify({zeroOneNoDiagram:true})),/CANVASデータ/);const data=canvasFixture();data.snapshot.schemaVersion=99;assert.throws(()=>new CanvasPlayback(JSON.stringify(data)),/新しい形式/);data.snapshot.schemaVersion=18;data.snapshot.steps[0].lines[0].end.x=1e20;assert.throws(()=>new CanvasPlayback(JSON.stringify(data)),/表示データ/);});
test('V14 識別子重複・不正な点列・prototype名を拒否',()=>{for(const change of [d=>d.snapshot.steps[0].players[0].id='__proto__',d=>d.snapshot.steps[1].id='step-one',d=>d.snapshot.steps[0].lines[0].points=[null]]){const data=canvasFixture();change(data);assert.throws(()=>viewerSnapshot(JSON.stringify(data)));}});
test('V15 CANVAS添付を自動取得せず動きの確認に限定する',()=>{const data=canvasFixture();data.snapshot.steps[0].media=[{src:'https://example.invalid/private.jpg'}];const p=new CanvasPlayback(JSON.stringify(data));assert.equal(p.mediaCount,1);assert.deepEqual(p.step.media,[]);assert.equal(data.snapshot.steps[0].media.length,1);});

// Captured from CANVAS 207c9417acf9fca7050b1f7cfd1d30fd8812cf93:
// default board -> native pass pointer handlers -> createSnapshot(). No personal data.
const nativeRaw=await readFile(new URL('../tools/canvas.native-export.json',import.meta.url),'utf8');
test('V16 CANVASの実際の書出しを読込・連続再生・コマ送りする',()=>{for(const action of ['play','next']){const p=new CanvasPlayback(nativeRaw);assert.equal(p.step.lines[0].playerId,null);p[action]();p.advance(30000);assert.equal(p.running,false);assert.deepEqual(p.positions.balls.ball,{x:500,y:400});assert.deepEqual(p.positions.players.o1,{x:525,y:764.4});assert.equal(p.completed,1);}});
test('V17 旧形式のnull点列・任意配列と未関連の線を表示する',()=>{const data=JSON.parse(nativeRaw),step=data.snapshot.steps[0];step.lines[0].points=null;step.cones=step.texts=step.media=null;step.lines.push({...step.lines[0],id:'unassociated-move',type:'move',ballId:null,playerId:null,playOrder:2});const raw=JSON.stringify(data),p=new CanvasPlayback(raw);p.play();p.advance(30000);assert.deepEqual(p.positions.balls.ball,{x:500,y:400});assert.deepEqual(Object.keys(p.positions.players),['o1','o2','o3','o4','o5']);assert.equal(JSON.stringify(data),raw);});
test('V18 null対応後も不正な選手識別子・点列・選手配列を拒否',()=>{for(const change of [s=>s.lines[0].playerId='__proto__',s=>s.lines[0].playerId=7,s=>s.lines[0].points='invalid',s=>s.players=null]){const data=JSON.parse(nativeRaw);change(data.snapshot.steps[0]);assert.throws(()=>viewerSnapshot(JSON.stringify(data)));}});
