import test from 'node:test'; // 接続と保存の回帰試験を実行します。
import assert from 'node:assert/strict'; // 実際の結果と期待条件を比較します。
import {DatabaseSync} from 'node:sqlite'; // 実SQLiteでローカル保存を確認します。
import {GraphClient,OneDriveCloud} from '../web/core/graph.mjs'; // 公開候補の通信処理を直接検査します。
import {AppService} from '../web/core/service.mjs'; // 通信待機と保存の分離を検査します。
import {SyncEngine} from '../web/core/sync.mjs'; // 実同期ロジックを使います。
import {Auth} from '../web/auth.mjs'; // 認証の一時障害と期限切れを区別します。
import {WorkerBridge} from '../web/worker-bridge.mjs'; // Workerの通信失敗を確認します。
import {buildPlan} from '../web/core/planner.mjs'; // 既存形式の練習を作ります。
import {canonical,objectKey,LabError} from '../web/core/model.mjs'; // データの同一性を検証します。
import {NO_TERM} from '../web/catalog.mjs'; // 個人情報を含まない標準用語を使用します。
const scope='ms-'+'a'.repeat(64),path='/me/drive/special/approot'; // 合成の本人とGraph経路です。
const json=(value,status=200,headers={})=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json',...headers}}); // ネットワーク応答だけを合成します。
const client=fetcher=>new GraphClient({getToken:async()=>'synthetic-token',fetcher,sleep:async()=>{},random:()=>0}); // 本物のMicrosoft認証は使用しません。
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}; // 遅いネットワークを決定的に再現します。
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)); // 実行順序だけを整えます。
const input=(title='合成練習')=>({title,goal:'判断を観察する',team:'U15',players:15,totalMinutes:180,items:[{name:'合成2対1',minutes:10,section:'BODY',category:'判断',term:NO_TERM,variationName:'基本条件',rule:'2ドリブル'}]}); // 実データと無関係な練習です。
const service=()=>new AppService(new DatabaseSync(':memory:'),scope); // 各試験で新しいDBを使用します。
test('N01 一時的なGET通信失敗は有限回で復旧',async()=>{let calls=0;const g=client(async()=>{if(++calls===1)throw new TypeError('offline');return json({id:'root'});});assert.equal((await g.request(path)).id,'root');assert.equal(calls,2);assert.equal(g.retries,1);}); // 再ログインを強制せず回復します。
test('N02 通信が戻らない場合は三回で停止',async()=>{let calls=0;const g=client(async()=>{calls++;throw new TypeError('offline');});await assert.rejects(g.request(path),{code:'NETWORK'});assert.equal(calls,3);}); // 無限再試行を防ぎます。
test('N03 POST応答不明時は盲目的に再送しない',async()=>{let calls=0;const g=client(async()=>{calls++;throw new TypeError('lost response');});await assert.rejects(g.request('/me/drive/items/root/children',{method:'POST',body:'{}'}),{code:'NETWORK'});assert.equal(calls,1);}); // 同名フォルダーの重複作成を避けます。
test('N04 401後は同じ本人のトークンを一回だけ更新',async()=>{const tokens=[],sent=[];const g=new GraphClient({getToken:async options=>{tokens.push(options.forceRefresh);return options.forceRefresh?'fresh':'cached';},fetcher:async(_,options)=>{sent.push(options.headers.Authorization);return options.headers.Authorization==='Bearer cached'?json({},401):json({id:'root'});}});assert.equal((await g.request(path)).id,'root');assert.deepEqual(tokens,[false,true]);assert.deepEqual(sent,['Bearer cached','Bearer fresh']);}); // 期限切れのキャッシュを何度も送りません。
test('N05 更新しても401ならAUTHで停止',async()=>{let calls=0;const g=client(async()=>{calls++;return json({},401);});await assert.rejects(g.request(path),{code:'AUTH'});assert.equal(calls,2);}); // 認証エラーをネットワークの無限再試行へ回しません。
test('N06 認証側の通信失敗はNETWORKを保持',async()=>{const g=new GraphClient({getToken:async()=>{throw Object.assign(new Error('network'),{code:'NETWORK'});},fetcher:async()=>assert.fail(),sleep:async()=>{}});await assert.rejects(g.request(path),{code:'NETWORK'});}); // Workerを介しても分類を保持します。
for(const [status,code]of [[403,'PERMISSION'],[507,'QUOTA'],[409,'CONFLICT'],[412,'CONFLICT']])test('N07 '+status+'は再送しない',async()=>{let calls=0;const g=client(async()=>{calls++;return json({},status);});await assert.rejects(g.request(path),{code});assert.equal(calls,1);}); // 権限や容量を通信不良で隠しません。
test('N08 Retry-Afterを待って再試行',async()=>{let calls=0;const delays=[];const g=new GraphClient({getToken:async()=>'synthetic',fetcher:async()=>++calls<3?json({},429,{'Retry-After':'7'}):json({ok:true}),sleep:async ms=>delays.push(ms)});assert((await g.request(path)).ok);assert.deepEqual(delays,[7000,7000]);}); // Microsoftの指定より早く再送しません。
test('N09 長い混雑待ちはUIへ伝えて停止',async()=>{let calls=0;const g=client(async()=>{calls++;return json({},429,{'Retry-After':'120'});});await assert.rejects(g.request(path),error=>error.code==='RATE_LIMIT'&&error.retryAfterMs===120000);assert.equal(calls,1);}); // Workerを長時間占有しません。
for(const status of [408,423,500,502,503,504,509])test('N10 一時HTTP '+status+'から復旧',async()=>{let calls=0;const g=client(async()=>++calls===1?json({},status):json({ok:true}));assert((await g.request(path)).ok);assert.equal(calls,2);}); // 一時障害の範囲を明示して検査します。
test('N11 JSON本文の受信切断も再試行',async()=>{let calls=0;const g=client(async()=>++calls===1?{ok:true,status:200,text:async()=>{throw new TypeError('body interrupted');}}:json({ok:true}));assert((await g.request(path)).ok);assert.equal(calls,2);}); // ヘッダー受信後の失敗も対象です。
test('N12 不正JSONはCORRUPTとして停止',async()=>{let calls=0;const g=client(async()=>{calls++;return new Response('broken');});await assert.rejects(g.request(path),{code:'CORRUPT'});assert.equal(calls,1);}); // 内容破損は再送で隠しません。
test('N13 同期期限超過後も次の接続と端末保存を利用可能',async()=>{let blocked=true;const g=client(async()=>{if(blocked)await pause(50);return json({ok:true});});await assert.rejects(g.withTask(()=>g.request(path),10),{code:'TIMEOUT'});blocked=false;assert((await g.withTask(()=>g.request(path),100)).ok);assert.equal(g.controller.signal.aborted,false);}); // 一回の通信失敗でクライアントを壊しません。
test('N14 明示中断後はGraphへ新しい通信を送らない',async()=>{const g=client(async()=>assert.fail());g.close();await assert.rejects(g.request(path),{code:'CANCELLED'});}); // サインアウト境界を維持します。
test('N15 不許可のGraph宛先は認証前に拒否',async()=>{const g=new GraphClient({getToken:async()=>assert.fail(),fetcher:async()=>assert.fail()});await assert.rejects(g.request('https://outside.example.invalid/v1.0/me/drive/root'),{code:'PATH'});}); // 秘密情報の流出を防ぐ既存境界です。
test('N16 期限切れの本文URLを再取得しBearerを送らない',async()=>{const seen=[];let renewed=0;const g=client(async(url,options)=>{seen.push(options);return url.endsWith('/old')?json({},403):new Response('saved');});const blob=await g.download({id:'file','@microsoft.graph.downloadUrl':'https://download.example.invalid/old'},{refresh:async()=>{renewed++;return {id:'file','@microsoft.graph.downloadUrl':'https://download.example.invalid/new'};}});assert.equal(await blob.text(),'saved');assert.equal(renewed,1);assert(seen.every(o=>!o.headers?.Authorization&&o.credentials==='omit'&&o.referrerPolicy==='no-referrer'));}); // 一時URLの期限切れを本人のログアウトと混同しません。
test('N17 受信途中で切れた本文を破棄して取り直す',async()=>{let calls=0;const g=client(async()=>++calls===1?new Response(new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode('partial'));controller.error(new TypeError('broken'));}})):new Response('complete'));const blob=await g.download({id:'file','@microsoft.graph.downloadUrl':'https://download.example.invalid/file'});assert.equal(await blob.text(),'complete');assert.equal(calls,2);}); // 部分データを保存済みの内容にしません。
test('N18 本文のサイズ超過は再試行せず拒否',async()=>{let calls=0;const g=client(async()=>{calls++;return new Response('oversize');});await assert.rejects(g.download({id:'file','@microsoft.graph.downloadUrl':'https://download.example.invalid/file'},{limit:2}),{code:'LIMIT'});assert.equal(calls,1);}); // 無制限にメモリへ読み込みません。
function cloudFixture(){const values=new Map(),counts={body:0,meta:0,puts:0};let lost=false;const g=client(async(url,options={})=>{const u=new URL(url);if(u.hostname==='download.example.invalid'){counts.body++;const item=values.get(decodeURIComponent(u.pathname.slice(1)));return item?new Response(item.raw):json({},404);}const match=/\/items\/folder:\/(.+?)(:\/content)?$/.exec(decodeURIComponent(u.pathname));if(!match)return json({},404);const name=match[1];let item=values.get(name);if(options.method==='PUT'){assert.equal(u.searchParams.get('@microsoft.graph.conflictBehavior'),'fail');counts.puts++;if(item)return json({},409);item={raw:String(options.body),tag:'"v1"'};values.set(name,item);if(lost){lost=false;throw new TypeError('response lost');}return json({id:name});}counts.meta++;if(!item)return json({},404);if(options.headers?.['If-None-Match']===item.tag)return new Response(null,{status:304});return json({id:name,name,eTag:item.tag,file:{},size:Buffer.byteLength(item.raw),'@microsoft.graph.downloadUrl':'https://download.example.invalid/'+encodeURIComponent(name)});});const cloud=new OneDriveCloud(g,scope,{meta:()=>null,setMeta:()=>{}});cloud.folderId='folder';cloud.check=async()=>{};return {cloud,g,values,counts,loseResponse(){lost=true;}};} // アプリ専用領域のサーバー応答だけを合成します。
test('C01 eTagが同じ本文は一度だけ取得し毎回メタ情報を確認',async()=>{const f=cloudFixture(),wire=buildPlan(input()).objects[0],key=objectKey(wire.hash);f.values.set(key,{raw:canonical(wire),tag:'"v1"'});assert.deepEqual(await f.cloud.get(key),wire);assert.deepEqual(await f.cloud.get(key),wire);assert.equal(f.counts.body,1);assert.equal(f.counts.meta,2);}); // 読み込み回数を実測します。
test('C02 キャッシュ済みファイルの消失を検出',async()=>{const f=cloudFixture(),wire=buildPlan(input()).objects[0],key=objectKey(wire.hash);f.values.set(key,{raw:canonical(wire),tag:'"v1"'});await f.cloud.get(key);f.values.delete(key);assert.equal(await f.cloud.get(key),null);assert.equal(f.cloud.verified.has(key),false);}); // 古いキャッシュを最新のクラウドと偽りません。
test('C03 eTag変更で本文を再検証し改変を拒否',async()=>{const f=cloudFixture(),wire=buildPlan(input()).objects[0],key=objectKey(wire.hash);f.values.set(key,{raw:canonical(wire),tag:'"v1"'});await f.cloud.get(key);f.values.set(key,{raw:'{}',tag:'"v2"'});await assert.rejects(f.cloud.get(key));assert.equal(f.counts.body,2);}); // 内容ハッシュの検査を省略しません。
test('C04 eTagがない場合は本文の再取得を省略しない',async()=>{const f=cloudFixture(),wire=buildPlan(input()).objects[0],key=objectKey(wire.hash);f.values.set(key,{raw:canonical(wire),tag:''});await f.cloud.get(key);await f.cloud.get(key);assert.equal(f.counts.body,2);}); // 変更確認の根拠がないときは安全側へ戻します。
test('C05 保存成功後に応答だけ消えても同じ実体を確認',async()=>{const f=cloudFixture(),wire=buildPlan(input()).objects[0],key=objectKey(wire.hash);f.loseResponse();assert.deepEqual(await f.cloud.put(key,wire),wire);assert.equal(f.values.size,1);assert(f.counts.puts<=2);assert.deepEqual(JSON.parse(f.values.get(key).raw),wire);}); // 同じ練習の新しいUUIDを勝手に作り直しません。
test('Q01 同期待機中も練習をSQLiteへ保存して読み直せる',async()=>{const s=service(),hold=deferred(),started=deferred();s.cloud={check:async()=>{}};s.engine={sync:async()=>{started.resolve();await hold.promise;return {state:s.repo.state()};}};const sync=s.run('sync');await started.promise;const result=await Promise.race([s.run('savePlan',{input:input()}),pause(200).then(()=>assert.fail('local save blocked by network'))]);assert.equal(result.state.pending,1);assert.equal((await s.run('detail',{revisionId:result.operation.body.opId})).operation.body.payload.title,'合成練習');assert.equal((await s.run('state')).pending,1);hold.resolve();await sync;await s.run('close');}); // 接続不良で端末保存まで止めないことを検査します。
test('Q02 同期中に保存した次の計画を次回同期で送信',async()=>{const s=service(),hold=deferred(),started=deferred(),files=new Map();let delayed=true;s.cloud={scope,check:async()=>{},list:async()=>[...files.keys()],get:async key=>files.get(key)||null,put:async(key,value)=>{if(delayed){delayed=false;started.resolve();await hold.promise;}files.set(key,structuredClone(value));}};s.engine=new SyncEngine(s.repo,s.cloud);await s.run('savePlan',{input:input('先の保存')});const first=s.run('sync');await started.promise;await s.run('savePlan',{input:input('同期中の保存')});hold.resolve();await first;assert.equal(s.repo.pending().length,1);await s.run('sync');assert.equal(s.repo.pending().length,0);assert.equal(s.repo.operations().length,2);assert.equal([...files.keys()].filter(key=>key.startsWith('O_')).length,2);await s.run('close');}); // 送信中の変更を消さず次回へ残します。
test('Q03 同期失敗後もローカル保存を継続できる',async()=>{const s=service();s.cloud={check:async()=>{throw new LabError('NETWORK','synthetic failure');}};s.engine={};await assert.rejects(s.run('sync'),{code:'NETWORK'});assert.equal((await s.run('savePlan',{input:input()})).state.pending,1);await s.run('close');}); // 通信失敗をDBの故障と混同しません。
test('Q04 クラウド要求同士は直列に処理',async()=>{const s=service(),hold=deferred(),started=deferred();let calls=0;s.cloud={check:async()=>{}};s.engine={sync:async()=>{calls++;if(calls===1){started.resolve();await hold.promise;}return {state:s.repo.state()};}};const a=s.run('sync');await started.promise;const b=s.run('sync');await pause(10);assert.equal(calls,1);hold.resolve();await Promise.all([a,b]);assert.equal(calls,2);await s.run('close');}); // 並列書込による同期衝突を増やしません。
test('Q05 終了後の要求を拒否',async()=>{const s=service();await s.run('close');await assert.rejects(s.run('savePlan',{input:input()}),{code:'CLOSED'});}); // 別アカウントへの誤登録を防ぎます。
function authFixture(fail=null){const data=new Map(),storage={getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)};const auth=new Auth({msal:{},storage,session:storage,location:{href:'https://example.invalid/practice/'}});auth.account={homeAccountId:'synthetic-user',username:'synthetic@example.invalid'};auth.client={acquireTokenSilent:async options=>{if(fail)throw fail;return {accessToken:options.forceRefresh?'fresh':'cached',account:auth.account};}};return auth;} // 実認証情報は使用しません。
test('A01 MSALの一時通信失敗で再ログイン扱いしない',async()=>{const a=authFixture(Object.assign(new Error('offline'),{errorCode:'no_network_connectivity'}));await assert.rejects(a.token(),{code:'NETWORK'});assert.equal(a.needsInteraction,false);}); // 通信復帰だけで再試行できる状態を維持します。
test('A02 本当に対話が必要な認証は再接続を表示',async()=>{const a=authFixture(Object.assign(new Error('login needed'),{errorCode:'interaction_required'}));await assert.rejects(a.token(),{code:'AUTH'});assert.equal(a.needsInteraction,true);}); // 期限切れを無視して同期成功にしません。
test('A03 401更新フラグをMSALへ伝える',async()=>{const a=authFixture();assert.equal(await a.token(),'cached');assert.equal(await a.token({forceRefresh:true}),'fresh');}); // キャッシュの再利用と更新を分けます。
test('A04 遅い認証結果が別人へ切り替わったら拒否',async()=>{const a=authFixture(),hold=deferred(),old=a.account;a.client.acquireTokenSilent=()=>hold.promise;const token=a.token();a.account={homeAccountId:'other'};hold.resolve({accessToken:'synthetic',account:old});await assert.rejects(token,{code:'SCOPE'});}); // 本人境界の検査を強化します。
test('W01 同期の橋渡し時間切れでも端末保存を停止しない',async()=>{const timers=new Map();let serial=0;const sent=[],worker={postMessage:value=>sent.push(value),terminate(){}};const b=new WorkerBridge(worker,{timers:{setTimeout:fn=>{timers.set(++serial,fn);return serial;},clearTimeout:id=>timers.delete(id)},onFatal:()=>assert.fail('network timeout must not stop local storage')});const sync=b.call('sync');timers.get(1)();await assert.rejects(sync,{code:'TIMEOUT'});assert.equal(b.failed,false);const save=b.call('savePlan',{});await b.receive({type:'result',id:sent.at(-1).id,value:{saved:true}});assert.deepEqual(await save,{saved:true});b.shutdown();}); // 不明なのはネットワークの結果であり端末保存の結果ではありません。
test('W02 本当の端末保存の応答不明は従来どおり保護停止',async()=>{const timers=new Map();let serial=0,failed=0;const b=new WorkerBridge({postMessage(){},terminate(){}},{timers:{setTimeout:fn=>{timers.set(++serial,fn);return serial;},clearTimeout:id=>timers.delete(id)},onFatal:()=>failed++});const save=b.call('savePlan');timers.get(1)();await assert.rejects(save);assert.equal(failed,1);assert.equal(b.failed,true);b.shutdown();}); // 保存の不確かな自動再送は行いません。
test('W03 認証再取得フラグと通信分類を橋渡し',async()=>{let options;const sent=[];const b=new WorkerBridge({postMessage:value=>sent.push(value),terminate(){}},{getToken:async value=>{options=value;throw Object.assign(new Error('offline'),{code:'NETWORK'});}});await b.receive({type:'token',id:'synthetic',forceRefresh:true});assert.equal(options.forceRefresh,true);assert.equal(sent[0].code,'NETWORK');b.shutdown();}); // 秘密情報をエラーへ含めず再接続判定を保ちます。
test('Q06 別端末の同時編集と端末保存の両方を競合として残す',async()=>{const a=service(),b=service(),files=new Map(),hold=deferred(),started=deferred();let wait=false;const cloud=()=>({scope,check:async()=>{},list:async()=>{if(wait){wait=false;started.resolve();await hold.promise;}return [...files.keys()];},get:async key=>structuredClone(files.get(key)||null),put:async(key,value)=>{files.set(key,structuredClone(value));}});a.cloud=cloud();b.cloud=cloud();a.engine=new SyncEngine(a.repo,a.cloud);b.engine=new SyncEngine(b.repo,b.cloud);const first=await a.run('savePlan',{input:input('原本')});await a.run('sync');await b.run('sync');await b.run('savePlan',{revisionId:first.operation.body.opId,input:input('別端末の編集')});await b.run('sync');wait=true;const sync=a.run('sync');await started.promise;await a.run('savePlan',{revisionId:first.operation.body.opId,input:input('この端末の編集')});hold.resolve();await sync;assert.deepEqual(a.repo.heads(first.operation.body.entityId).map(o=>o.body.payload.title).sort(),['この端末の編集','別端末の編集'].sort());assert.equal(a.repo.operations().length,3);assert.equal(a.repo.pending().length,0);await a.run('close');await b.run('close');}); // どちらかの内容を黙って上書きしません。
test('Q07 終了時は応答しない通信を中断してからDBを閉じる',async()=>{const started=deferred();const graph=client(async()=>{started.resolve();return new Promise(()=>{});});const s=new AppService(new DatabaseSync(':memory:'),scope,{graph});s.cloud={check:async()=>{await graph.request(path);}};s.engine={};const sync=s.run('sync');const rejected=assert.rejects(sync,{code:'CANCELLED'});await started.promise;assert.deepEqual(await s.run('close'),{closed:true});await rejected;assert.equal(s.closed,true);}); // 古い本人の遅い通信で別領域を変更しません。
