import { chromium, webkit } from 'playwright'; // 実際のブラウザエンジンを使用します。
import assert from 'node:assert/strict'; // 合否を実際の保存結果で判定します。
import { verifyAppleTouchIcon } from './icon-contract.mjs'; // 更新番号ではなく正しい画像本体を確認します。
import { readFile, writeFile, mkdir, mkdtemp } from 'node:fs/promises'; // 合成記録と証拠だけを扱います。
import { join, resolve } from 'node:path'; // 証拠とプロファイルを分離します。
import { tmpdir } from 'node:os'; // 試験専用OSホームを用意します。
import { createServer } from './serve-project.mjs'; // 既存の専用サブパス配信を使用します。
const live = process.env.SITE_URL; const reports = resolve(live?'reports/production-live':'reports/production'); await mkdir(reports,{recursive:true}); // 公開前後の証拠を別保存します。
const results=[],errors=[]; let server; let url=live; // 実行した結果だけを記録します。
if(live)assert.equal(live,'https://yuge-u.github.io/zero-one-practice-lab/'); // 別のサイトへ試験データを送信しません。
else{server=createServer();await new Promise(done=>server.listen(0,'127.0.0.1',done));url=`http://127.0.0.1:${server.address().port}/zero-one-practice-lab/`;} // 個人のOneDriveを使わないローカル配信です。
async function isolated(engine){const root=await mkdtemp(join(tmpdir(),'zero-one-production-'));const home=join(root,'home');await mkdir(home);return engine.launchPersistentContext(join(root,'profile'),{headless:true,viewport:{width:390,height:844},hasTouch:true,env:{...process.env,HOME:home,CFFIXED_USER_HOME:home,XDG_DATA_HOME:join(home,'data'),XDG_CACHE_HOME:join(home,'cache'),XDG_CONFIG_HOME:join(home,'config')}});} // WebKitのOS共有領域も合成端末ごとに分離します。
async function ready(page){await page.waitForFunction(()=>document.getElementById('editorFields')&&!document.getElementById('editorFields').disabled,null,{timeout:30000});} // 本物のSQLite初期化完了を待ちます。
async function saved(page){await page.waitForFunction(()=>document.getElementById('saveFeedback').textContent.includes('端末に保存しました'),null,{timeout:20000});} // 永続保存の応答を確認します。
async function library(page){await page.getByRole('button',{name:'保存した練習',exact:true}).click();} // 一覧画面を実操作で開きます。
async function open(page,title){await library(page);await page.locator('.saved-card').filter({has:page.getByRole('heading',{name:title,exact:true})}).locator('[data-open]').click();await page.waitForFunction(()=>document.getElementById('detail').hidden===false);} // 名前が一致する計画だけを選びます。
async function check(engine,name,fn){try{await fn();results.push({engine,name,status:'passed'});console.log('PASS',engine,name);}catch(error){results.push({engine,name,status:'failed',error:error.message});throw error;}} // スキップや自動再試行を合格に数えません。
try{ // 片方のブラウザの失敗も記録して検証します。
  for(const [name,engine]of Object.entries({chromium,webkit})){ // 両方のエンジンで同じ保存・コピーを実行します。
    const context=await isolated(engine);const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push({engine:name,message:error.message})); // 未捕捉の画面エラーも不合格にします。
    try{ // 各エンジンの実画面を検査します。
      await page.goto(url);await ready(page); // 公開対象アプリを通常どおり起動します。
      await check(name,'R01 本番表示・承認済みアイコン・保存準備',async()=>{assert.match(await page.locator('footer').innerText(),/1\.0\.0/);assert.match(await page.locator('#environment').innerText(),/SQLite.*OPFS/);assert(!await page.locator('body').innerText().then(text=>text.includes('検証版・本番とは別保存')));assert.match(await page.locator('.brand img').getAttribute('src'),/^\.\/icons\/icon-512\.webp\?v=20261007d$/);assert.match(await page.locator('.zeroone-splash img').getAttribute('src'),/^\.\/icons\/icon-512\.webp\?v=20261007d$/);await page.locator('.brand img').evaluate(img=>img.decode());await page.locator('.zeroone-splash img').evaluate(img=>img.decode());await verifyAppleTouchIcon(page);}); // 実際のPNGとブラウザでの復号も確認します。
      await check(name,'R02 必須未入力は保存ボタン付近に理由を表示',async()=>{await page.locator('#savePlan').click();assert.match(await page.locator('#saveFeedback').innerText(),/練習名を入力/);assert.equal(await page.locator('#title').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('.saved-card').count(),0);}); // 無反応ではなく具体的な理由を返します。
      await check(name,'R03 時間超過で入力を失わず停止',async()=>{await page.locator('#title').fill('本番受入・原本');await page.locator('#goal').fill('ヘルプを見る');await page.locator('[data-field="name"]').first().fill('2対2');await page.locator('[data-field="rule"]').first().fill('2ドリブル');await page.locator('#totalMinutes').fill('5');await page.locator('#savePlan').click();assert.match(await page.locator('#saveFeedback').innerText(),/合計は10分/);assert.equal(await page.locator('#title').inputValue(),'本番受入・原本');assert.equal(await page.locator('.saved-card').count(),0);}); // 失敗後にそのまま修正できることを確認します。
      await check(name,'R04 空のVariation・二項目を保存し連打は重複なし',async()=>{await page.locator('#totalMinutes').fill('60');await page.locator('[data-field="variationName"]').first().fill('');await page.locator('#addItem').click();await page.locator('[data-field="name"]').nth(1).fill('3対3');await page.locator('#savePlan').click();await saved(page);await page.locator('#savePlan').click();assert.match(await page.locator('#saveFeedback').innerText(),/保存済み/);await library(page);assert.equal(await page.locator('.saved-card').count(),1);}); // 保存確認後の連打を新規登録しません。
      await check(name,'R05 コピー元の実績・振り返りを保存',async()=>{await open(page,'本番受入・原本');await page.locator('#reflection').fill('原本にだけ残す学び');await page.locator('#saveReflection').click();await page.waitForFunction(()=>document.getElementById('records').textContent.includes('原本にだけ残す学び'));await page.locator('#startTimer').click();await page.waitForTimeout(1100);await page.locator('#pauseTimer').click();}); // コピーしない記録を事前に作成します。
      await check(name,'R06 全体コピー・一部変更・独立した計画IDで保存',async()=>{await page.locator('#copyPlan').click();assert.match(await page.locator('#draftMode').innerText(),/元の練習/);assert.equal(await page.locator('[data-field="name"]').count(),2);assert.equal(await page.locator('#title').inputValue(),'本番受入・原本（コピー）');await page.locator('#title').fill('本番受入・コピー');await page.locator('[data-field="minutes"]').first().fill('17');await page.locator('[data-field="rule"]').first().fill('1ドリブル');await page.locator('#savePlan').click();await saved(page);await library(page);assert.equal(await page.locator('.saved-card').count(),2);const ids=await page.locator('.saved-card').evaluateAll(nodes=>nodes.map(node=>node.dataset.practiceId));assert.equal(new Set(ids).size,2);}); // 元の計画を更新する編集と区別します。
      await check(name,'R07 コピー先の履歴とタイマーは空・元の内容は不変',async()=>{await open(page,'本番受入・コピー');assert.equal(await page.locator('#records').innerText(),'');assert.equal(await page.locator('#timer').innerText(),'00:00');assert.match(await page.locator('#detailItems').innerText(),/17分/);assert.match(await page.locator('#detailItems').innerText(),/1ドリブル/);await open(page,'本番受入・原本');assert.match(await page.locator('#records').innerText(),/原本にだけ残す学び/);assert.match(await page.locator('#detailItems').innerText(),/2ドリブル/);assert(!await page.locator('#detailItems').innerText().then(text=>text.includes('17分')));}); // 過去の練習履歴を保護します。
      await check(name,'R08 再読込後も原本とコピーを保持',async()=>{await page.reload();await ready(page);await library(page);assert.equal(await page.locator('.saved-card').count(),2);await open(page,'本番受入・コピー');assert.match(await page.locator('#detailItems').innerText(),/17分/);}); // 実OPFSへの永続保存を確認します。
      await check(name,'R09 一覧からコピー・保存前キャンセルで原本を保護',async()=>{await library(page);await page.locator('.saved-card').filter({has:page.getByRole('heading',{name:'本番受入・コピー',exact:true})}).locator('[data-copy]').click();await page.waitForFunction(()=>document.getElementById('editor').hidden===false&&document.getElementById('draftMode').textContent.includes('コピーから新規作成'));assert.equal(await page.locator('#title').inputValue(),'本番受入・コピー（コピー）');page.once('dialog',dialog=>dialog.accept());await page.locator('#newPlan').click();assert.equal(await page.locator('.saved-card').count(),2);}); // Workerからコピー元が戻り画面が切り替わってから内容と原本保護を検査します。
      await check(name,'R10 明細の再利用で初期空白項目を残さない',async()=>{await open(page,'本番受入・原本');await page.locator('[data-reuse]').first().click();assert.equal(await page.locator('[data-field="name"]').count(),1);await page.locator('#title').fill('本番受入・再利用');await page.locator('#goal').fill('次の判断');await page.locator('#savePlan').click();await saved(page);await library(page);assert.equal(await page.locator('.saved-card').count(),3);}); // 既存の部分再利用でも保存しやすくします。
      await check(name,'R11 バックアップに元計画とコピーを両方保持',async()=>{await page.getByRole('button',{name:'接続・バックアップ',exact:true}).click();const download=page.waitForEvent('download');await page.locator('#backup').click();const file=await download;const backup=await readFile(await file.path(),'utf8');assert(backup.includes('本番受入・原本'));assert(backup.includes('本番受入・コピー'));assert(!backup.includes('access_token'));}); // 本番化に伴うデータ保全を確認します。
      await check(name,'R12 第二タブからの二重書込を停止',async()=>{const other=await context.newPage();try{await other.goto(url);await other.waitForFunction(()=>document.getElementById('notice').textContent.includes('別のタブ'));assert.equal(await other.locator('#title').isDisabled(),true);}finally{await other.close();}}); // 既存の保存排他を維持します。
      if(!live)await check(name,'R13 通信先停止中にもコピーして保存・再読込',async()=>{await page.waitForFunction(()=>document.getElementById('offlineStatus').textContent.includes('事前取得済み'));const port=server.address().port;await new Promise(done=>{server.close(done);server.closeAllConnections();});try{assert.equal(server.listening,false);await assert.rejects(fetch(url+'not-cached',{signal:AbortSignal.timeout(3000)}));const response=await page.reload();assert.equal(response.fromServiceWorker(),true);await ready(page);await open(page,'本番受入・原本');await page.locator('#copyPlan').click();await page.locator('#title').fill('通信断のコピー');await page.locator('#savePlan').click();await saved(page);await page.reload();await ready(page);await library(page);assert.match(await page.locator('#savedPlans').innerText(),/通信断のコピー/);}finally{await new Promise(done=>server.listen(port,'127.0.0.1',done));}}); // 機内モードではなくサーバー到達不能を測ります。
      await check(name,'R14 320px・390px・PC幅で横にはみ出さない',async()=>{await page.getByRole('button',{name:'練習をつくる',exact:true}).click();for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});const value=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert(value.scroll<=value.client+1);}}); // 入力画面もスマートフォン幅で確認します。
      await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(reports,name+'-mobile.png'),fullPage:true}); // 実際の表示を証拠に残します。
    }catch(error){errors.push({engine:name,message:error.message,notice:await page.locator('#notice').textContent().catch(()=>null)});await page.screenshot({path:join(reports,name+'-failure.png'),fullPage:true}).catch(()=>{});}finally{await context.close();} // 不合格を隠して公開しません。
  } // 全エンジンの検査を閉じます。
}finally{if(server)await new Promise(done=>{server.close(done);server.closeAllConnections();});const expected=live?26:28;const passed=results.filter(result=>result.status==='passed').length;const ok=results.length===expected&&passed===expected&&errors.length===0;await writeFile(join(reports,'results.json'),JSON.stringify({version:'1.0.0',environment:process.platform,url,physicalIPhone:false,realMicrosoft:false,networkMethod:live?'public-HTTPS':'origin-server-stopped',expected,executed:results.length,passed,errors,results,status:ok?'passed':'failed'},null,2));if(!ok)process.exitCode=1;} // 未実行のシナリオも不合格と区別して記録します。
