import test from 'node:test'; // 個人データを使わない単体試験です。
import assert from 'node:assert/strict'; // 期待値を厳密に照合します。
import {DatabaseSync} from 'node:sqlite'; // 実際のSQLiteへ保存します。
import {AppService} from '../web/core/service.mjs'; // 公開版の保存処理を使用します。
import {Auth} from '../web/auth.mjs'; // 実際の認証クラスを検査します。
import {DEFAULT_CATEGORIES,NO_TERM,categoryName,categoryChoices,menuChoices,termChoices,matches,searchKey} from '../web/catalog.mjs'; // 検索の本体を使用します。
import {draftErrors,rowsFromDetail} from '../web/draft.mjs'; // コピー時の固定版を読みます。
import {seal,validateOperation,sha} from '../web/core/model.mjs'; // 保存内容の完全性を確認します。
import {CLIENT_ID,SCOPES} from '../web/config.mjs'; // 既存の認証設定を使います。
const input=()=>({title:'元のプラン',goal:'相手を見る',team:'U15',players:8,totalMinutes:40,items:[{name:'スライド',section:'BODY',category:'フットワーク',minutes:10,term:NO_TERM,variationName:'合図に反応',rule:'相手の合図で方向を変える',canvasRaw:''}]}); // 人工の練習です。
function service(t,scope='guest-local'){const app=new AppService(new DatabaseSync(':memory:'),scope);t.after(()=>app.repo.close());return app;} // 試験ごとの領域を分離します。
test('C01 大項目43件にウォームアップ・フットワーク等を含む',()=>{assert.equal(DEFAULT_CATEGORIES.length,43);assert(DEFAULT_CATEGORIES.some(c=>c.name==='ウォーミングアップ'));assert(DEFAULT_CATEGORIES.some(c=>c.name==='フットワーク'));assert(!DEFAULT_CATEGORIES.some(c=>['OPENING','BODY','CLOSING'].includes(c.name)));}); // コーチングの進行区分と混同しません。
test('C02 日本語かな・英語大小・全半角を検索できる',()=>{assert(matches('Footwork フットワーク','FOOT ふっと'));assert.equal(searchKey('ＳＨＯＯＴ'),'shoot');assert(matches('パス・キャッチ','ぱす'));}); // iPhone入力の揺れを吸収します。
test('C03 自由カテゴリーを重複なく候補へ追加',()=>{const list=categoryChoices([], [{category:'  朝練  '},{category:'朝練'}]);assert.equal(list.filter(c=>c.name==='朝練').length,1);assert.equal(categoryName('  '),'未分類');}); // 空白だけの分類は作りません。
test('C04 カテゴリーは保存と再読込で保持',async t=>{const app=service(t);const saved=await app.run('savePlan',{input:input()});assert.equal(saved.operation.body.payload.items[0].category,'フットワーク');assert.equal(menuChoices(saved.state.practices,'フットワーク').length,1);assert.equal(menuChoices(saved.state.practices,'シュート').length,0);}); // 大項目に対応するメニューだけを選びます。
test('C05 条件とプラン名でもメニュー検索',async t=>{const app=service(t),r=await app.run('savePlan',{input:input()});assert.equal(menuChoices(r.state.practices,'','合図 元の').length,1);assert.equal(menuChoices(r.state.practices,'','存在しない').length,0);}); // メニュー名だけに検索を限定しません。
test('C06 選択したメニューは全関連版付きでコピー',async t=>{const app=service(t);const r=await app.run('savePlan',{input:input()});const d=await app.run('detail',{revisionId:r.operation.body.opId});const row=rowsFromDetail(d,true)[0];assert.notEqual(row.id,r.operation.body.payload.items[0].id);assert.equal(row.category,'フットワーク');assert.equal(row.rule,input().items[0].rule);assert.equal(row.variationName,'合図に反応');const next=await app.run('savePlan',{input:{...input(),title:'次回',items:[row]}});assert.notEqual(next.operation.body.entityId,r.operation.body.entityId);for(const k of ['termHash','canvasHash','drillHash','variationHash'])assert.equal(next.operation.body.payload.items[0][k],r.operation.body.payload.items[0][k]);}); // 実績・振り返りは複製しません。
test('C07 コピー後の変更で元のメニューを変えない',async t=>{const app=service(t);const r=await app.run('savePlan',{input:input()});const snapshot=JSON.stringify(r.operation);const row=rowsFromDetail(await app.run('detail',{revisionId:r.operation.body.opId}),true)[0];row.name='新しいメニュー';row.category='朝練';row.rule='新条件';row.pinned=null;await app.run('savePlan',{input:{...input(),items:[row]}});assert.deepEqual(app.repo.getOp(r.operation.body.opId),JSON.parse(snapshot));assert(categoryChoices(app.repo.state().practices).some(c=>c.name==='朝練'));}); // 新しい名前と条件を保存できます。
test('C08 分類変更だけなら固定版を維持',async t=>{const app=service(t);const r=await app.run('savePlan',{input:input()});const row=rowsFromDetail(await app.run('detail',{revisionId:r.operation.body.opId}),false)[0];row.category='守備の準備';const next=await app.run('savePlan',{revisionId:r.operation.body.opId,input:{...input(),items:[row]}});assert.equal(next.operation.body.payload.items[0].category,'守備の準備');assert.equal(next.operation.body.payload.items[0].variationHash,r.operation.body.payload.items[0].variationHash);}); // カテゴリー変更で条件違いを作りません。
test('C09 旧データに分類を推測して書き込まない',async t=>{const app=service(t);const r=await app.run('savePlan',{input:input()});const body=structuredClone(r.operation.body);delete body.payload.items[0].category;body.payload.items[0].section='OPENING';const old=seal(body);validateOperation(old,'guest-local');const target=service(t);target.repo.ingest([old],app.repo.objects());const before=JSON.stringify(target.repo.getOp(old.body.opId));assert.equal(menuChoices(target.repo.state().practices,'未分類').length,1);const row=rowsFromDetail(await target.run('detail',{revisionId:old.body.opId}),true)[0];assert.equal(row.section,'OPENING');assert.equal(row.category,'');assert.equal(JSON.stringify(target.repo.getOp(old.body.opId)),before);}); // 旧OPENINGと新カテゴリーは独立です。
test('C10 新しい分類を他端末へ取り込み、バックアップ復元',async t=>{const a=service(t),b=service(t),c=service(t);const data=input();data.items[0].category='チーム独自';await a.run('savePlan',{input:data});b.repo.ingest(a.repo.operations(),a.repo.objects());assert(categoryChoices(b.repo.state().practices).some(x=>x.name==='チーム独自'));await c.run('restore',{backup:await b.run('backup'),confirm:true});assert.equal(menuChoices(c.repo.state().practices,'チーム独自').length,1);}); // カテゴリーを端末だけの管理にしません。
test('C11 アーカイブ・競合・関連不足は候補へ出さない',async t=>{const app=service(t);const r=await app.run('savePlan',{input:input()});const practice=r.state.practices[0];assert.equal(menuChoices([{...practice,heads:[...practice.heads,...practice.heads]}]).length,0);assert.equal(menuChoices([{...practice,heads:[{...practice.heads[0],readiness:{ready:false}}]}]).length,0);await app.run('archive',{revisionId:r.operation.body.opId});assert.equal(menuChoices(app.repo.state().practices).length,0);}); // 不完全な固定版を自動採用しません。
test('C12 同一内容は集約し条件違いは別候補',async t=>{const app=service(t);await app.run('savePlan',{input:input()});await app.run('savePlan',{input:input()});assert.equal(menuChoices(app.repo.state().practices).length,1);const data=input();data.items[0].rule='別条件';await app.run('savePlan',{input:data});assert.equal(menuChoices(app.repo.state().practices).length,2);}); // 保存回数で候補が膨らみ過ぎるのを防ぎます。
test('C13 過長・非文字列カテゴリーを拒否',async t=>{const app=service(t);for(const value of ['a'.repeat(81),{}]){const data=input();data.items[0].category=value;assert(draftErrors(data).some(e=>e.field==='category'));await assert.rejects(app.run('savePlan',{input:data}));}}); // 画面外からの入力も制限します。
test('C14 用語は日本語・英語・略語・定義で検索',()=>{const terms=[{ID:'A','正式/標準用語':'Pick and Roll','日本語推奨表記':'ピック＆ロール',略語:'PNR',定義:'ボールスクリーン'}];for(const q of ['pick','ぴっく','ｐｎｒ','スクリーン'])assert.equal(termChoices(terms,q)[0].ID,'A');assert.equal(termChoices(terms,'未指定')[0].ID,NO_TERM.ID);}); // 独自の未指定を公式用語と混同しません。
test('C15 関連用語なしも有効に保存',async t=>{const app=service(t);assert.deepEqual(draftErrors(input()),[]);const r=await app.run('savePlan',{input:input()});assert.equal(app.repo.getObject(r.operation.body.payload.items[0].termHash).body.payload.record.zeroOneNoTerm,true);}); // 給水などに無関係な用語を強制しません。
test('C16 別アカウントの候補を混ぜない',async t=>{const a=service(t,'ms-A'),b=service(t,'ms-B');await a.run('savePlan',{input:input()});assert.equal(menuChoices(b.repo.state().practices).length,0);assert.throws(()=>b.repo.ingest(a.repo.operations(),a.repo.objects()));}); // 個人の記録を越境させません。
const A={homeAccountId:'account-A',username:'a@example.invalid'},B={homeAccountId:'account-B',username:'b@example.invalid'},scope=a=>'ms-'+sha(CLIENT_ID+'|'+a.homeAccountId); // 実在しない認証情報です。
function storage(values={}){const map=new Map(Object.entries(values));return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k),map};} // 標準Storageの最小形です。
function authFixture({local=[],sessionAccounts=[],values={},redirect=null,resultAccount=null,failToken=false}={}){const localStore=storage(values),session=storage(),calls=[];class PCA{constructor(config){this.config=config;calls.push(['config',config]);}async initialize(){}async handleRedirectPromise(){return redirect;}getAllAccounts(){return this.config.cache.cacheLocation==='localStorage'?local:sessionAccounts;}setActiveAccount(a){this.active=a;}async loginRedirect(args){calls.push(['login',args]);}async acquireTokenSilent(args){calls.push(['token',args]);if(failToken)throw Error('expired');return {accessToken:'SYNTHETIC',account:resultAccount||args.account};}async logoutRedirect(args){calls.push(['logout',args]);}}const auth=new Auth({msal:{PublicClientApplication:PCA},storage:localStore,session,location:{href:'https://yuge-u.github.io/zero-one-practice-lab/'}});return {auth,calls,localStore,session};} // Microsoftへ通信しません。
test('A01 標準のlocalStorageキャッシュを使う',async()=>{const f=authFixture({local:[A]});await f.auth.init();assert.equal(f.auth.account,A);assert.equal(f.calls[0][1].cache.cacheLocation,'localStorage');}); // 新規タブでも認証状態を再利用します。
test('A02 共有端末設定はsessionStorage',async()=>{const f=authFixture({sessionAccounts:[A],values:{'zero-one-practice-remember':'0'}});await f.auth.init();assert.equal(f.auth.cacheMode,'sessionStorage');}); // 保持を利用者が無効にできます。
test('A03 旧タブの認証もトークンをコピーせず使用',async()=>{const f=authFixture({sessionAccounts:[A]});await f.auth.init();assert.equal(f.auth.account,A);assert.equal(f.auth.cacheMode,'sessionStorage');assert(![...f.localStore.map.keys()].some(k=>k.includes('token')));}); // 旧版更新で本人DBを見失わないようにします。
test('A04 前回の本人を優先し他アプリのアカウントへ移らない',async()=>{const f=authFixture({local:[B,A],values:{'zero-one-browser-lab-v02-last-scope':scope(A)}});await f.auth.init();assert.equal(f.auth.account,A);}); // 共有クライアントIDでも保存境界を維持します。
test('A05 前回の本人が不在なら別人を自動採用しない',async()=>{const f=authFixture({local:[B],values:{'zero-one-browser-lab-v02-last-scope':scope(A)}});await f.auth.init();assert.equal(f.auth.account,null);assert.equal(f.auth.scope(),'guest-local');}); // 未認証の本人DBは明示操作でのみ開きます。
test('A06 複数候補を勝手に選ばない',async()=>{const f=authFixture({local:[A,B]});await f.auth.init();assert.equal(f.auth.account,null);}); // 本人による選択を必要とします。
test('A07 通常接続でアカウント選択を強制しない',async()=>{const f=authFixture();await f.auth.init();await f.auth.signIn();const args=f.calls.find(c=>c[0]==='login')[1];assert.equal(args.prompt,undefined);assert.deepEqual(args.scopes,SCOPES);}); // 許可範囲を広げず操作を減らします。
test('A08 選び直し操作だけアカウント選択を要求',async()=>{const f=authFixture();await f.auth.init();await f.auth.signIn({chooseAccount:true});assert.equal(f.calls.find(c=>c[0]==='login')[1].prompt,'select_account');}); // 共有端末でも切替できます。
test('A09 トークンは無言で再取得し本人一致を確認',async()=>{const f=authFixture({local:[A]});await f.auth.init();assert.equal(await f.auth.token(),'SYNTHETIC');assert.equal(f.calls.filter(c=>c[0]==='login').length,0);const bad=authFixture({local:[A],resultAccount:B});await bad.auth.init();await assert.rejects(bad.auth.token());assert.equal(bad.auth.needsInteraction,true);}); // 別アカウントのトークンをWorkerへ渡しません。
test('A10 期限切れで自動リダイレクトを繰り返さない',async()=>{const f=authFixture({local:[A],failToken:true});await f.auth.init();await assert.rejects(f.auth.token(),/再認証/);assert.equal(f.calls.filter(c=>c[0]==='login').length,0);}); // 未保存の入力中に画面遷移しません。
test('A11 接続の意思は一回だけ消費',async()=>{const f=authFixture({local:[A]});await f.auth.init();f.auth.armConnection();assert.equal(f.auth.consumeConnectionIntent(),true);assert.equal(f.auth.consumeConnectionIntent(),false);}); // 再読込だけでフォルダーを再作成しません。
test('A12 期限切れ・別アカウントの接続意思を拒否',async()=>{const f=authFixture({local:[A]});await f.auth.init();for(const data of [{at:0,scope:null},{at:Date.now(),scope:scope(B)}]){f.session.setItem('zero-one-practice-connect-intent',JSON.stringify(data));assert.equal(f.auth.consumeConnectionIntent(),false);}}); // 古い認証遷移を悪用しません。
test('A13 サインアウトはデータを消さない',async()=>{const f=authFixture({local:[A],values:{'test-record':'preserve'}});await f.auth.init();await f.auth.signOut();assert.equal(f.localStore.getItem('test-record'),'preserve');assert.equal(f.calls.find(c=>c[0]==='logout')[1].account,A);}); // 消す範囲は本人の認証だけです。
test('A14 認証の保存領域と戻り先を維持',async()=>{const f=authFixture({local:[A]});await f.auth.init();assert.equal(f.auth.scope(),scope(A));assert.equal(f.auth.redirectUri,'https://yuge-u.github.io/zero-one-practice-lab/');}); // Azure再設定を要求しません。
