import {chromium,webkit} from 'playwright'; // 実ブラウザで新しい検索と接続を検査します。
import assert from 'node:assert/strict'; // 実画面と保存結果を照合します。
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises'; // 人工の検証証拠だけを保存します。
import {join} from 'node:path'; // 保存先を限定します。
import {tmpdir} from 'node:os'; // OSの共有領域も分離します。
import {createServer} from './serve-project.mjs'; // 本番と同じパス構造で配信します。
const live=process.env.SITE_URL,reports=live?'reports/catalog-live':'reports/catalog',results=[],errors=[];let server,url=live;await mkdir(reports,{recursive:true}); // 公開前後の証拠を分けます。
if(live)assert.equal(url,'https://yuge-u.github.io/zero-one-practice-lab/');else{server=createServer();await new Promise(done=>server.listen(0,'127.0.0.1',done));url=`http://127.0.0.1:${server.address().port}/zero-one-practice-lab/`;} // 本人のOneDriveへは接続しません。
const fakeMSAL=`globalThis.msal={PublicClientApplication:class{constructor(config){this.config=config;this.store=config.cache.cacheLocation==='localStorage'?localStorage:sessionStorage;}async initialize(){}async handleRedirectPromise(){if(sessionStorage.getItem('test-return')){sessionStorage.removeItem('test-return');return {account:this.getAllAccounts()[0]};}return null;}getAllAccounts(){return this.store.getItem('test-account')?[{homeAccountId:'synthetic-account',username:'synthetic@example.invalid'}]:[];}setActiveAccount(a){this.active=a;}async loginRedirect(args){if(args.prompt)throw Error('Unexpected forced prompt');this.store.setItem('test-account','1');localStorage.setItem('test-login-count',String(Number(localStorage.getItem('test-login-count')||0)+1));sessionStorage.setItem('test-return','1');location.assign(this.config.auth.redirectUri);await new Promise(()=>{});}async acquireTokenSilent(args){return {accessToken:'synthetic-not-a-real-token',account:args.account};}async logoutRedirect(){this.store.removeItem('test-account');location.assign(this.config.auth.postLogoutRedirectUri);}}};`; // 認証クラス本体は実物、Microsoft SDKの外部認証結果だけを合成します。
async function record(engine,name,fn){await fn();results.push({engine,name,status:'pass'});console.log('PASS',engine,name);} // 未実行を合格へ数えません。
async function contextFor(type){const home=await mkdtemp(join(tmpdir(),'practice-catalog-'));return type.launchPersistentContext(join(home,'profile'),{headless:true,viewport:{width:390,height:844},hasTouch:true,env:{...process.env,HOME:home,CFFIXED_USER_HOME:home,XDG_DATA_HOME:join(home,'data'),XDG_CACHE_HOME:join(home,'cache'),XDG_CONFIG_HOME:join(home,'config')}});} // 物理iPhoneとは区別します。
const ready=page=>page.waitForFunction(()=>document.getElementById('editorFields')&&!document.getElementById('editorFields').disabled,null,{timeout:30000}); // SQLiteの準備完了を待ちます。
const saved=page=>page.waitForFunction(()=>document.getElementById('saveFeedback').textContent.includes('練習を保存しました'),null,{timeout:20000}); // 書込応答を確認します。
const synced=page=>page.waitForFunction(()=>document.getElementById('storageStatus').textContent.includes('OneDrive同期済み'),null,{timeout:30000}); // クラウドの再読込まで待ちます。
try{for(const [engine,type]of Object.entries({chromium,webkit})){const contexts=[];const files=new Map();let folder=false;const meta=name=>({id:name,name,file:{},size:Buffer.byteLength(files.get(name)||'')}); // 両端末が同じ合成クラウドを使います。
  async function setup(context){contexts.push(context);await context.route('**/*',async route=>{const req=route.request(),target=new URL(req.url()),local=new URL(url);const reply=(status,value)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value),headers:{'Access-Control-Allow-Origin':'*'}}); // ネイティブfetchの後段にHTTP応答を与えます。
    if(target.origin===local.origin){if(target.pathname.endsWith('/vendor/msal-browser.min.js'))return route.fulfill({status:200,contentType:'text/javascript',body:fakeMSAL});return route.continue();} // 検索・Auth・SQLiteは公開本体を使います。
    if(!['graph.microsoft.com','zero-one-synthetic.1drv.com'].includes(target.hostname))return route.abort();const path=decodeURIComponent(target.pathname); // 個人データの送信先を持ちません。
    if(target.hostname==='zero-one-synthetic.1drv.com'){assert(!req.headers().authorization);const name=path.slice(1);return files.has(name)?route.fulfill({status:200,contentType:'application/json',body:files.get(name),headers:{'Access-Control-Allow-Origin':'*'}}):reply(404,{});} // ダウンロードURLへBearerを送りません。
    assert.equal(req.headers().authorization,'Bearer synthetic-not-a-real-token');if(path.endsWith('/special/approot'))return reply(200,{id:'root',folder:{}}); // 本人トークンではないことを保証します。
    if(path.endsWith('/items/root/children')){if(req.method()==='POST'){folder=true;return reply(201,{id:'folder',folder:{}});}return reply(200,{value:folder?[{id:'folder',name:'ZERO_ONE_PRACTICE_LAB_V02',folder:{}}]:[]});} // 明示した初回接続だけでフォルダーを作ります。
    if(path.endsWith('/items/folder/children'))return reply(200,{value:[...files.keys()].map(meta)});const match=/\/items\/folder:\/(.+?)(:\/content)?$/.exec(path); // 保存済みファイルを返します。
    if(match){const name=match[1];if(match[2]&&req.method()==='PUT'){files.set(name,req.postData());return reply(201,meta(name));}return files.has(name)?reply(200,meta(name)):reply(404,{});} // 保存後に同じ内容を読み戻せます。
    const name=path.split('/items/')[1];return name&&files.has(name)?reply(200,{...meta(name),'@microsoft.graph.downloadUrl':'https://zero-one-synthetic.1drv.com/'+encodeURIComponent(name)}):reply(404,{}); // 不明な要求を成功へ変えません。
  });} // 合成通信の設定を閉じます。
  const context=await contextFor(type);await setup(context);const page=await context.newPage();page.setDefaultTimeout(20000);page.on('dialog',dialog=>dialog.accept());page.on('pageerror',error=>errors.push({engine,error:error.message})); // 確認ダイアログもテストで操作します。
  try{await page.goto(url);await ready(page); // 実SQLiteでゲストの練習を作ります。
    await record(engine,'N01 大項目とVariationの表示',async()=>{assert.equal(await page.getByLabel('カテゴリー',{exact:true}).count(),1);assert.equal(await page.locator('[data-field="section"]').count(),0);assert.equal(await page.getByLabel('Variation',{exact:true}).count(),1);assert.equal(await page.locator('[data-field="termId"]').inputValue(),'ZEROONE_INTERNAL_NO_TERM');}); // 旧区分を大項目へ置き換えます。
    await page.locator('[data-category-picker]').click();await page.locator('#pickerQuery').fill('foot');await page.getByRole('button',{name:/^フットワーク/}).click(); // 英語でカテゴリーを検索します。
    await record(engine,'N02 カテゴリーを検索選択',async()=>assert.equal(await page.locator('[data-field="category"]').inputValue(),'フットワーク')); // 選択内容を入力欄に反映します。
    await page.locator('#title').fill('元のプラン');await page.locator('#goal').fill('相手の合図を見る');await page.locator('[data-field="name"]').fill('スライド');await page.locator('[data-field="variationName"]').fill('反応する');await page.locator('[data-field="rule"]').fill('相手を見て方向を変える');await page.locator('[data-term-picker]').click();await page.locator('#pickerQuery').fill('screen away');await page.locator('[data-picker-key="GBT-0291"]').check();await page.locator('#pickerApply').click();await page.locator('#searchPicker').waitFor({state:'hidden'}); // 実カタログから用語を検索します。
    await record(engine,'N03 関連用語を英語で検索選択',async()=>assert.equal(await page.locator('[data-field="termId"]').inputValue(),'GBT-0291')); // 既存用語IDを維持します。
    await page.locator('#savePlan').click();await saved(page);await page.reload();await ready(page);await record(engine,'N04 保存後の再読込でも残る',async()=>assert.equal(await page.locator('.saved-card').count(),1)); // 元の計画を永続化します。
    await page.locator('#title').fill('コピーしたプラン');await page.locator('#goal').fill('次回の判断');await page.locator('[data-field="category"]').fill('シュート');await page.locator('[data-menu-picker]').click();await record(engine,'N05 別カテゴリーのメニューは混ざらない',async()=>assert.equal(await page.locator('.picker-option').count(),0)); // 選択中の大項目で絞ります。
    await page.locator('#pickerFilter').selectOption('フットワーク');await page.locator('#pickerQuery').fill('スライド');await page.getByRole('button',{name:/^スライド/}).click(); // 保存済みメニューをコピーします。
    await record(engine,'N06 名前以降の内容もコピー',async()=>{assert.equal(await page.locator('[data-field="category"]').inputValue(),'フットワーク');assert.equal(await page.locator('[data-field="rule"]').inputValue(),'相手を見て方向を変える');assert.equal(await page.locator('[data-field="variationName"]').inputValue(),'反応する');assert.equal(await page.locator('[data-field="minutes"]').inputValue(),'10');assert.equal(await page.locator('[data-field="termId"]').inputValue(),'GBT-0291');}); // 時間・用語・条件を引き継ぎます。
    await page.locator('[data-field="name"]').fill('スライド応用');await page.locator('[data-field="rule"]').fill('2人の合図を見る');await page.locator('#savePlan').click();await saved(page);await page.getByRole('button',{name:'保存した練習',exact:true}).click();await page.locator('.saved-card').filter({has:page.getByRole('heading',{name:'元のプラン',exact:true})}).locator('[data-open]').click();await page.waitForFunction(()=>!document.getElementById('detail').hidden); // コピー元を読み戻します。
    await record(engine,'N07 変更後も元の内容を維持',async()=>{assert.match(await page.locator('#detailItems').innerText(),/相手を見て方向を変える/);assert(!await page.locator('#detailItems').innerText().then(t=>t.includes('2人の合図を見る')));assert.equal(await page.locator('.saved-card').count(),2);}); // 同じ名前の上書きを防ぎます。
    await page.getByRole('button',{name:'練習をつくる',exact:true}).click();await page.locator('#newPlan').click();await page.locator('[data-category-picker]').click();await page.locator('#pickerQuery').fill('朝練オリジナル');await page.locator('#pickerNew').click();await page.locator('#title').fill('独自分類のプラン');await page.locator('#goal').fill('準備を揃える');await page.locator('[data-field="name"]').fill('新規メニュー');await page.locator('#savePlan').click();await saved(page);await page.reload();await ready(page);await page.locator('[data-category-picker]').click();await page.locator('#pickerQuery').fill('朝練'); // 新しいカテゴリーを保存します。
    await record(engine,'N08 自由カテゴリーを次回も選べる',async()=>{assert.equal(await page.getByRole('button',{name:/^朝練オリジナル/}).count(),1);});await page.locator('#pickerClose').click(); // 未保存だけの一時候補ではないことを確認します。
    await page.getByRole('button',{name:'接続・バックアップ',exact:true}).click();await record(engine,'N09 認証詳細は折りたたみ',async()=>{assert.equal(await page.locator('#redirectUri').isVisible(),false);assert.equal(await page.locator('#signOut').isVisible(),false);assert((await page.locator('.connection-panel').boundingBox()).height<280);}); // ログインが画面を占有しません。
    await page.locator('#connectCloud').click();await page.waitForFunction(()=>document.getElementById('storageStatus')?.textContent.includes('✓ OneDrive接続済み'),null,{timeout:30000}); // 一操作で認証復帰後の初回接続まで進めます。
    await record(engine,'N10 認証から戻ると自動接続しゲスト記録は送らない',async()=>{assert.equal(await page.evaluate(()=>localStorage.getItem('test-login-count')),'1');assert.equal([...files.keys()].filter(k=>k.startsWith('O_')).length,0);assert.equal(await page.locator('.saved-card').count(),0);}); // アカウント境界を維持します。
    await page.locator('#title').fill('本人のプラン');await page.locator('#goal').fill('端末間で引き継ぐ');await page.locator('[data-field="name"]').fill('本人のメニュー');await page.locator('[data-field="category"]').fill('独自同期カテゴリー');await page.locator('#savePlan').click();await saved(page);await synced(page); // 保存後に自動同期します。
    await record(engine,'N11 分類付きでクラウド保存',async()=>{const operations=[...files.values()].map(raw=>{try{return JSON.parse(raw);}catch{return null;}}).filter(x=>x?.body?.kind==='practice');assert.equal(operations.length,1);assert.equal(operations[0].body.payload.items[0].category,'独自同期カテゴリー');}); // 端末だけのカテゴリーではありません。
    await page.reload();await ready(page);await synced(page);await record(engine,'N12 認証状態を再利用して自動再接続',async()=>{assert.equal(await page.evaluate(()=>localStorage.getItem('test-login-count')),'1');assert.equal(await page.locator('.saved-card').count(),1);}); // 再読み込みで毎回のログインを要求しません。
    const other=await contextFor(type);await setup(other);const second=await other.newPage();second.on('pageerror',error=>errors.push({engine,error:error.message}));await second.goto(url);await ready(second);await second.locator('#quickConnect').click();await synced(second);await second.locator('[data-category-picker]').click();await second.locator('#pickerQuery').fill('独自同期');await second.getByRole('button',{name:/^独自同期カテゴリー/}).click();await second.locator('[data-menu-picker]').click(); // 別プロファイルでも候補を受信します。
    await record(engine,'N13 別端末相当でカテゴリーとメニューを再利用',async()=>assert.equal(await second.getByRole('button',{name:/^本人のメニュー/}).count(),1));await second.locator('#pickerClose').click(); // 物理iPhone／PCの試験とは区別します。
    await page.getByRole('button',{name:'練習をつくる',exact:true}).click();await record(engine,'N14 小画面ではみ出さない',async()=>{for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));}await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(reports,engine+'-catalog.png'),fullPage:true});}); // 画面を目視できるよう保存します。
  }catch(error){errors.push({engine,error:error.message});await page.screenshot({path:join(reports,engine+'-failure.png'),fullPage:true}).catch(()=>{});}finally{for(const context of contexts)await context.close();} // 不合格も証拠を残します。
}}finally{if(server){server.closeAllConnections();await new Promise(done=>server.close(done));}const passed=results.length===28&&errors.length===0;await writeFile(join(reports,'results.json'),JSON.stringify({version:'1.1.0',results,errors,passed,realMicrosoft:false,physicalIPhone:false,auth:'real Auth with simulated MSAL response',cloud:'native fetch with synthetic Graph HTTP'},null,2));if(!passed)process.exitCode=1;} // 全シナリオ通過時だけ合格とします。
