import test from 'node:test'; // 必須項目と休憩の保存を個別に検証します。
import assert from 'node:assert/strict'; // 成功条件を厳密に照合します。
import {DatabaseSync} from 'node:sqlite'; // 本人データではなくメモリ内のSQLiteを使います。
import {AppService} from '../web/core/service.mjs'; // 配信する保存処理と同じコードを使います。
import {draftErrors,rowsFromDetail} from '../web/draft.mjs'; // フォームの確認とコピー読込を検査します。
import {NO_TERM} from '../web/catalog.mjs'; // 既存の関連用語なしを選択します。
const input=()=>({title:'休憩確認プラン',team:'U15',players:15,totalMinutes:180,goal:'給水時間を確保する',items:[{section:'BODY',category:'給水・休憩',name:'給水休憩',minutes:5,term:NO_TERM,variationName:'',rule:'',canvasRaw:''}]}); // 任意欄を空にした休憩メニューを作ります。
function service(t){const app=new AppService(new DatabaseSync(':memory:'),'guest-local');t.after(()=>app.repo.close());return app;} // 試験ごとに保存領域を分離します。
test('C01 休憩の任意欄が空でも保存前検査に合格',()=>{assert.deepEqual(draftErrors(input()),[]);}); // メニュー名と時間だけでよいことを確認します。
test('C02 休憩でもメニュー名は必須',()=>{const data=input();data.items[0].name='';assert(draftErrors(data).some(e=>e.field==='name'&&e.index===0));}); // 名前の必須条件は勝手に緩和しません。
test('C03 休憩でも正の整数の時間が必須',()=>{for(const value of ['',0,-1,1.5]){const data=input();data.items[0].minutes=value;assert(draftErrors(data).some(e=>e.field==='minutes'&&e.index===0));}}); // 空欄・ゼロ・小数を拒否します。
test('C04 プラン全体の名前・対象・ゴールは別途必須',()=>{for(const field of ['title','team','goal']){const data=input();data[field]='';assert(draftErrors(data).some(e=>e.field===field&&e.index===null));}}); // メニューの任意欄と計画全体の必須欄を区別します。
test('C05 休憩時間も全体時間に算入する',()=>{const data=input();data.totalMinutes=4;assert(draftErrors(data).some(e=>e.field==='totalMinutes'&&e.message.includes('5分')));}); // 休憩を含めた合計時間の制約を維持します。
test('C06 実SQLiteで休憩を保存できる',async t=>{const app=service(t);const result=await app.run('savePlan',{input:input()});const p=result.operation.body.payload;assert.equal(p.players,15);assert.equal(p.totalMinutes,180);assert.equal(p.items[0].category,'給水・休憩');assert.equal(p.items[0].resolved.variationName,'基本条件');assert.equal(p.items[0].resolved.rule,'条件の追加なし');assert.equal(app.repo.getObject(p.items[0].termHash).body.payload.id,NO_TERM.ID);assert.equal(JSON.parse(app.repo.getObject(p.items[0].canvasHash).body.payload.raw).zeroOneNoDiagram,true);}); // 用語や図を入力せず既定の空内容として保存します。
test('C07 8人120分の既存プランは編集用読込とコピーで不変',async t=>{const app=service(t);const data=input();data.players=8;data.totalMinutes=120;const original=await app.run('savePlan',{input:data});const detail=await app.run('detail',{revisionId:original.operation.body.opId});const copy={...detail.operation.body.payload,title:'コピー',items:rowsFromDetail(detail,true)};const saved=await app.run('savePlan',{input:copy});assert.equal(saved.operation.body.payload.players,8);assert.equal(saved.operation.body.payload.totalMinutes,120);assert.notEqual(saved.operation.body.entityId,original.operation.body.entityId);assert.deepEqual(app.repo.getOp(original.operation.body.opId),original.operation);}); // 新規初期値を過去の値へ上書きしません。
test('C08 休憩を含むバックアップを復元できる',async t=>{const original=service(t);await original.run('savePlan',{input:input()});const backup=await original.run('backup');const other=service(t);await other.run('restore',{backup,confirm:true});assert.equal(other.repo.state().practices.length,1);assert.equal(other.repo.state().pending,1);const row=other.repo.state().practices[0].heads[0].body.payload.items[0];assert.equal(row.name,'給水休憩');assert.equal(row.minutes,5);}); // 送信待ちと休憩の情報を一緒に保持します。
