import test from 'node:test'; // 回帰シナリオを省略せず実行します。
import assert from 'node:assert/strict'; // 実結果を期待値と照合します。
import {Auth} from '../web/auth.mjs'; // 配信する認証本体を検証します。
import {GraphClient} from '../web/core/graph.mjs'; // 配信する通信本体を検証します。
import {WorkerBridge} from '../web/worker-bridge.mjs'; // WindowとWorkerの受渡しも対象です。
import {connectionDiagnostics,recordConnection} from '../web/core/connection.mjs'; // 診断情報に個人情報が入らないことを検証します。
const account={homeAccountId:'synthetic-account',username:'private@example.invalid'},secret='synthetic-secret-never-log'; // 実資格情報を使わず漏洩検出用の値を用意します。
function fixture(sequence=[]){let calls=0,logins=0;const waits=[],requests=[];const auth=new Auth({location:{href:'https://example.invalid/practice/'},sleep:async ms=>waits.push(ms)});auth.account=account;auth.client={acquireTokenSilent:async options=>{requests.push(options);const value=sequence[calls++];if(value instanceof Error)throw value;return value||{accessToken:secret,account};},loginRedirect:async()=>{logins++;}};auth.cacheMode='localStorage';auth.msal={PublicClientApplication:class{}};auth.storage={getItem:()=>null};return {auth,waits,requests,calls:()=>calls,logins:()=>logins};} // 認証SDKの応答だけを合成します。
const failure=errorCode=>Object.assign(new Error(secret),{errorCode}); // SDKの機械判定コードを再現します。
test('R01 通信断は最大3回で止まり再認証を求めない',async()=>{const f=fixture(Array(3).fill(failure('no_network_connectivity')));await assert.rejects(f.auth.token(),{code:'NETWORK'});assert.equal(f.calls(),3);assert.deepEqual(f.waits,[500,1000]);assert.equal(f.auth.needsInteraction,false);assert.equal(f.logins(),0);}); // 回数と本人操作の判定を両方確認します。
test('R02 一時失敗後の認証成功と20件の同時要求を一本化',async()=>{const f=fixture([failure('post_request_failed')]);assert.deepEqual(await Promise.all(Array.from({length:20},()=>f.auth.token())),Array(20).fill(secret));assert.equal(f.calls(),2);}); // 添付と同期による認証更新の重複を防ぎます。
test('R03 本人操作待ちは自動更新・リダイレクトを繰り返さない',async()=>{const f=fixture([failure('login_required')]);await assert.rejects(f.auth.token(),{code:'AUTH'});await assert.rejects(f.auth.token(),{code:'AUTH'});assert.equal(f.calls(),1);assert.equal(f.auth.needsInteraction,true);assert.equal(f.logins(),0);await Promise.all([f.auth.signIn(),f.auth.signIn()]);assert.equal(f.logins(),1);}); // 明示サインインも一回だけ実行します。
test('R04 権限不足・進行中・不明な失敗を再認証と区別',async()=>{for(const [code,expected]of [['consent_required','PERMISSION'],['access_denied','PERMISSION'],['interaction_in_progress','BUSY'],['monitor_window_timeout','AUTH_UNKNOWN'],['unexpected','AUTH_UNKNOWN']]){const f=fixture([failure(code)]);await assert.rejects(f.auth.token(),{code:expected});assert.equal(f.auth.needsInteraction,false);assert.equal(f.calls(),1);}}); // 期限切れを示さないエラーから再認証を推測しません。
test('R05 通常更新の途中に401更新が来ても並行実行しない',async()=>{const f=fixture();const normal=f.auth.token(),forced=f.auth.token({forceRefresh:true});await Promise.all([normal,forced]);assert.deepEqual(f.requests.map(r=>r.forceRefresh),[false,true]);}); // 必要な強制更新だけを順番に実行します。
test('R06 Worker受渡しで通信分類を保持し例外の秘密を除去',async()=>{const messages=[],worker={postMessage:value=>messages.push(value)},bridge=new WorkerBridge(worker,{getToken:async()=>{throw Object.assign(new Error(secret),{code:'NETWORK'});}});await bridge.receive({type:'token',id:1});assert.equal(messages[0].code,'NETWORK');assert(!JSON.stringify(messages).includes(secret));}); // UIでの正しい分類が途中でAUTHへ変わらないことを確認します。
test('R07 Graphの401は一回の強制更新で復帰',async()=>{const f=fixture();let calls=0;const g=new GraphClient({getToken:options=>f.auth.token(options),fetcher:async()=>++calls===1?new Response('',{status:401}):Response.json({id:'root'})});assert.deepEqual(await g.request('/me/drive/special/approot'),{id:'root'});assert.deepEqual(f.requests.map(r=>r.forceRefresh),[false,true]);assert.equal(f.auth.needsInteraction,false);}); // 有効期限の更新だけなら利用者に操作を求めません。
test('R08 更新後も401なら2要求で停止し明示再認証待ち',async()=>{const f=fixture();let calls=0;const g=new GraphClient({getToken:options=>f.auth.token(options),fetcher:async()=>{calls++;return new Response('',{status:401});}});await assert.rejects(g.request('/me/drive/special/approot'),{code:'AUTH'});assert.equal(calls,2);assert.equal(f.auth.needsInteraction,true);assert.equal(f.logins(),0);}); // 401で再接続ループを作りません。
test('R09 403は再試行・認証更新をしない',async()=>{const f=fixture();const g=new GraphClient({getToken:options=>f.auth.token(options),fetcher:async()=>new Response('',{status:403})});await assert.rejects(g.request('/me/drive/special/approot'),{code:'PERMISSION'});assert.equal(f.calls(),1);assert.equal(f.auth.needsInteraction,false);}); // 権限と期限切れを分離します。
test('R10 応答不明のPUTを同じ名前・同じ本文で再試行',async()=>{const sent=[],waits=[];const g=new GraphClient({getToken:async()=>secret,sleep:async ms=>waits.push(ms),fetcher:async(url,options)=>{sent.push({url,body:options.body});if(sent.length===1)throw new TypeError('offline');return Response.json({id:'same-file'});}});await g.request('/me/drive/items/folder:/fixed.data:/content',{method:'PUT',body:'fixed-content'});assert.equal(sent.length,2);assert.deepEqual(sent[0],sent[1]);assert.equal(waits.length,1);}); // 送信再試行から新しい練習IDやファイル名を生成しません。
test('R11 POST通信断は結果不明の作成を繰り返さない',async()=>{let calls=0;const g=new GraphClient({getToken:async()=>secret,fetcher:async()=>{calls++;throw new TypeError('offline');}});await assert.rejects(g.request('/me/drive/items/root/children',{method:'POST',body:'{}'}),{code:'NETWORK'});assert.equal(calls,1);}); // フォルダー作成結果は次の明示接続で一覧確認します。
test('R12 Retry-Afterと上限・503の最終分類',async()=>{const waits=[];let calls=0;const g=new GraphClient({getToken:async()=>secret,sleep:async ms=>waits.push(ms),fetcher:async()=>{calls++;return new Response('',{status:503,headers:{'Retry-After':'2'}});}});await assert.rejects(g.request('/me/drive/special/approot'),{code:'NETWORK'});assert.equal(calls,3);assert.deepEqual(waits,[2000,2000]);g.fetcher=async()=>new Response('',{status:429,headers:{'Retry-After':'61'}});await assert.rejects(g.request('/me/drive/special/approot'),{code:'RATE_LIMIT'});assert.equal(waits.length,2);}); // 待機時間を縮めてサーバー制限を破りません。
test('R13 認証通信失敗をGraphで再認証へ変換しない',async()=>{const g=new GraphClient({getToken:async()=>{throw Object.assign(new Error(secret),{code:'NETWORK'});},fetcher:async()=>assert.fail('HTTP must not start')});await assert.rejects(g.request('/me/drive/special/approot'),{code:'NETWORK'});}); // 認証層で失敗した通信を二重に再試行しません。
test('R14 ダウンロード本文切断を再試行しBearerを送らない',async()=>{let downloads=0;const g=new GraphClient({getToken:async()=>secret,sleep:async()=>{},fetcher:async(url,options)=>{if(url.startsWith('https://graph.microsoft.com'))return Response.json({id:'file',size:2,'@microsoft.graph.downloadUrl':'https://synthetic.1drv.com/file'});assert.equal(options.headers,undefined);if(++downloads===1)return {ok:true,status:200,text:async()=>{throw new TypeError('stream interrupted');}};return new Response('{}');}});assert.equal(await g.readText({id:'file'}),'{}');assert.equal(downloads,2);}); // レスポンスヘッダー後の切断も読込成功にしません。
test('R15 診断は上限付き・許可項目だけで秘密と個人データを含まない',()=>{recordConnection(secret,secret,999,999);for(let i=0;i<120;i++)recordConnection('token','NETWORK',1);const entries=connectionDiagnostics();assert.equal(entries.length,100);assert(entries.every(e=>Object.keys(e).join(',')==='at,stage,code,attempt,status'));assert(!JSON.stringify(entries).includes(secret));assert(!JSON.stringify(entries).includes(account.username));}); // リクエストURLや生の例外も記録対象にしません。
import {AppService} from '../web/core/service.mjs'; // 同期の重複防止を実サービスで検査します。
import {DatabaseSync} from 'node:sqlite'; // 個人DBへ接続せず合成データを保存します。
test('R16 同時同期は事前確認と送信を一回だけ共有',async t=>{const service=new AppService(new DatabaseSync(':memory:'),'guest-local');t.after(()=>service.repo.close());let checks=0,syncs=0;service.cloud={check:async()=>{checks++;await Promise.resolve();}};service.engine={sync:async()=>{syncs++;return {synthetic:true};}};const results=await Promise.all(Array.from({length:10},()=>service.run('sync')));assert.equal(checks,1);assert.equal(syncs,1);assert(results.every(value=>value.synthetic));await service.run('sync');assert.equal(syncs,2);}); // 完了後の明示再同期は許可します。
test('R17 強制更新の後に503が来ても認証強制更新は一回',async()=>{const f=fixture();let calls=0;const g=new GraphClient({getToken:options=>f.auth.token(options),sleep:async()=>{},fetcher:async()=>new Response('{}',{status:[401,503,200][calls++]})});await g.request('/me/drive/special/approot');assert.deepEqual(f.requests.map(r=>r.forceRefresh),[false,true,false]);assert.equal(calls,3);}); // 通信再試行と認証更新の回数を別々に抑制します。
test('R18 別本人に切り替わった更新結果を外へ渡さない',async()=>{const f=fixture();let done;f.auth.client.acquireTokenSilent=()=>new Promise(resolve=>{done=resolve;});const pending=f.auth.token();f.auth.account={homeAccountId:'another-person'};done({accessToken:secret,account});await assert.rejects(pending,{code:'AUTH'});}); // 更新中の本人境界も維持します。
test('R19 同期の間の保存要求を後続同期が追い越さない',async t=>{const service=new AppService(new DatabaseSync(':memory:'),'guest-local');t.after(()=>service.repo.close());const order=[];service.execute=async name=>{order.push(name);};await Promise.all([service.run('sync'),service.run('savePlan'),service.run('sync')]);assert.deepEqual(order,['sync','savePlan','sync']);}); // 重複抑止で新しい保存の同期を落としません。
test('R20 並行要求の401で再認証待ちになった後の古い成功を拒否',async()=>{const f=fixture();let done;f.auth.client.acquireTokenSilent=()=>new Promise(resolve=>{done=resolve;});const pending=f.auth.token();await assert.rejects(f.auth.token({interactionRequired:true}),{code:'AUTH'});done({accessToken:secret,account});await assert.rejects(pending,{code:'AUTH'});assert.equal(f.auth.needsInteraction,true);}); // 遅れて完了した要求が再認証待ちを解除しません。
