import test from 'node:test'; // 追加したコピーと入力確認を検証します。
import assert from 'node:assert/strict'; // 実結果を厳密に照合します。
import { DatabaseSync } from 'node:sqlite'; // メモリ内の実SQLiteで保存処理を動かします。
import { AppService } from '../web/core/service.mjs'; // 本番と同じ保存処理を使います。
import { draftErrors, rowsFromDetail, copyTitle } from '../web/draft.mjs'; // 今回追加した入力とコピー処理を対象にします。
const term = { ID:'GBT-test', '正式/標準用語':'Paint Touch', 定義:'合成テスト用の用語' }; // 個人データではない人工用語を使用します。
const input = () => ({title:'元の計画',goal:'ヘルプを見る',team:'U15',players:8,totalMinutes:40,items:[{name:'2対2',section:'BODY',minutes:15,term,variationName:'基本',rule:'2ドリブル',canvasRaw:''}]}); // 余裕時間を含む人工の練習を定義します。
function service(t) { const app = new AppService(new DatabaseSync(':memory:'),'guest-local'); t.after(()=>app.repo.close()); return app; } // 試験ごとに保存領域を分離します。
async function seed(t) { const app=service(t); const result=await app.run('savePlan',{input:input()}); const detail=await app.run('detail',{revisionId:result.operation.body.opId}); return {app,original:result.operation,detail}; } // コピー元を本番の保存関数で作成します。
function duplicate(detail) { return {...structuredClone(detail.operation.body.payload),title:copyTitle(detail.operation.body.payload.title),items:rowsFromDetail(detail,true)}; } // 新しい明細IDを持つフォーム入力に変換します。
test('D01 有効な計画には保存前エラーがない',()=>{assert.deepEqual(draftErrors(input()),[]);}); // 正常系を不要に止めません。
test('D02 空白だけの名前と未入力ゴールを特定する',()=>{const data=input();data.title='　 ';data.goal='';const errors=draftErrors(data);assert(errors.some(e=>e.field==='title'));assert(errors.some(e=>e.field==='goal'));}); // 必須欄の場所を返します。
test('D03 最初の空白明細に番号付き理由を返す',()=>{const data=input();data.items[0].name='';assert(draftErrors(data).some(e=>e.index===0&&e.field==='name'&&e.message.includes('1番目')));}); // スマートフォンの下部にある未入力も説明します。
test('D04 時間超過を実際の合計付きで示す',()=>{const data=input();data.totalMinutes=10;assert(draftErrors(data).some(e=>e.message.includes('15分')));}); // 一見無反応になる時間超過を説明します。
test('D05 小数と空欄の数値を保存前に拒否する',()=>{const data=input();data.players='';data.items[0].minutes=1.5;assert.equal(draftErrors(data).filter(e=>['players','minutes'].includes(e.field)).length,2);}); // Workerと同じ整数条件を採用します。
test('D06 コピーは新しい計画IDと新しい明細IDを持つ',async t=>{const {app,original,detail}=await seed(t);const next=await app.run('savePlan',{input:duplicate(detail)});assert.notEqual(next.operation.body.entityId,original.body.entityId);assert.notEqual(next.operation.body.payload.items[0].id,original.body.payload.items[0].id);assert.deepEqual(next.operation.body.parents,[]);assert.equal(app.repo.state().practices.length,2);}); // 元の更新操作と区別します。
test('D07 コピーで固定用語・作戦・条件を変更しない',async t=>{const {app,original,detail}=await seed(t);const snapshot=JSON.stringify(detail);const next=await app.run('savePlan',{input:duplicate(detail)});for(const key of ['termHash','canvasHash','drillHash','variationHash'])assert.equal(next.operation.body.payload.items[0][key],original.body.payload.items[0][key]);assert.equal(JSON.stringify(detail),snapshot);}); // 参照版を保持し元オブジェクトに副作用を与えません。
test('D08 コピーで実績・振り返り・タイマーを複製しない',async t=>{const {app,original,detail}=await seed(t);await app.run('record',{revisionId:original.body.opId,kind:'reflection',note:'原本のみの振り返り'});await app.run('record',{revisionId:original.body.opId,kind:'session',actualMinutes:18});await app.run('timer',{revisionId:original.body.opId,action:'start'});const next=await app.run('savePlan',{input:duplicate(detail)});assert.equal(app.repo.state().records.length,2);assert(app.repo.state().records.every(r=>r.body.payload.practiceRevision===original.body.opId));const timer=await app.run('timer',{revisionId:next.operation.body.opId,action:'read'});assert.equal(timer.elapsedMs,0);assert.equal(timer.running,false);}); // 新しい練習の実施履歴を空から始めます。
test('D09 条件だけ変えたコピーは同じドリルのVariationになる',async t=>{const {app,original,detail}=await seed(t);const draft=duplicate(detail);draft.items[0].pinned=null;draft.items[0].rule='1ドリブル';draft.items[0].variationName='判断を速める';const next=await app.run('savePlan',{input:draft});const before=original.body.payload.items[0],after=next.operation.body.payload.items[0];assert.equal(before.drillHash,after.drillHash);assert.notEqual(before.variationHash,after.variationHash);assert.equal(app.repo.getObject(before.variationHash).body.payload.rule,'2ドリブル');}); // 原本は残して条件差だけ新しく記録します。
test('D10 コピー先の時間変更で元の時間を変えない',async t=>{const {app,original,detail}=await seed(t);const draft=duplicate(detail);draft.items[0].minutes=20;const next=await app.run('savePlan',{input:draft});assert.equal(next.operation.body.payload.items[0].minutes,20);assert.equal(app.repo.getOp(original.body.opId).body.payload.items[0].minutes,15);}); // 次回の予定と過去計画を分離します。
test('D11 固定版が欠ける計画はコピーを停止する',async t=>{const {detail}=await seed(t);detail.objects=[];assert.throws(()=>rowsFromDetail(detail,true),/揃っていません/);}); // 空の関連データを勝手に作りません。
test('D12 編集では元の明細IDを保持する',async t=>{const {original,detail}=await seed(t);assert.equal(rowsFromDetail(detail,false)[0].id,original.body.payload.items[0].id);}); // コピーと編集の意味を分けます。
test('D13 コピーを含むバックアップを空のDBへ復元できる',async t=>{const {app,detail}=await seed(t);await app.run('savePlan',{input:duplicate(detail)});const backup=await app.run('backup');const other=service(t);await other.run('restore',{backup,confirm:true});assert.equal(other.repo.state().practices.length,2);assert.equal(other.repo.state().pending,2);}); // 保存済みと未送信分の両方を保全します。
test('D14 コピー名は絵文字を含めて文字数上限を守る',()=>{for(const value of ['a'.repeat(120),'🏀'.repeat(60)]){const copy=copyTitle(value);assert(copy.length<=120);assert(copy.endsWith('（コピー）'));}}); // 長い元名でも登録可能にします。
test('D15 Variation空欄は基本条件として保存可能',async t=>{const app=service(t);const data=input();data.items[0].variationName='';assert.deepEqual(draftErrors(data),[]);const result=await app.run('savePlan',{input:data});assert.equal(result.operation.body.payload.items[0].resolved.variationName,'基本条件');}); // 任意欄の空白で保存を止めません。
