import {readFile,writeFile,copyFile} from 'node:fs/promises'; // 添付の実ブラウザ試験だけを整えます。
import {join,resolve} from 'node:path'; // 検証コードの位置を固定します。
import assert from 'node:assert/strict'; // 既知の試験にだけ差分を適用します。
const root=resolve(process.argv[2]),file=join(root,'tools/media-browser.mjs');let text=await readFile(file,'utf8'); // 公開ランタイムは変更しません。
function change(before,after){assert.equal(text.split(before).length,2,before);text=text.replace(before,after);} // 該当箇所を一つだけ置き換えます。
change("await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.readyState>=2);await video.evaluate(async v=>{v.muted=true;await v.play();});","await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.readyState>=1);await video.evaluate(async v=>{v.muted=true;await Promise.race([v.play(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('VIDEO_PLAY_TIMEOUT')),10000))]);});await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.readyState>=2);"); // metadata先読みではフレーム取得を再生要求の前提にせず、実再生後のデコードを検査します。
change("const contexts=[];const files=new Map(),binaries=new Map();","const contexts=[],mediaWire=[];const files=new Map(),binaries=new Map();"); // 模擬HTTPのバイナリ受信状態を記録します。
change("mediaPuts++;binaries.set(name,request.postDataBuffer());","mediaPuts++;const body=request.postDataBuffer();mediaWire.push({name,bytes:body?.length??null,type:request.headers()['content-type']});binaries.set(name,body);"); // 認証トークンは記録せず、サイズと種類だけを診断します。
change("}catch(error){errors.push({engine,message:error.message});if(page)","}catch(error){const diagnostics=page?await page.evaluate(()=>{const v=document.querySelector('#mediaPreviewBody video');return {notice:document.getElementById('notice')?.textContent,save:document.getElementById('saveFeedback')?.textContent,media:document.getElementById('mediaSyncStatus')?.textContent,mediaDetail:document.getElementById('mediaSyncDetail')?.textContent,preview:document.getElementById('mediaPreviewMessage')?.textContent,video:v?{readyState:v.readyState,networkState:v.networkState,error:v.error?.code,currentTime:v.currentTime,duration:v.duration,paused:v.paused,videoWidth:v.videoWidth}:null};}).catch(()=>null):null;errors.push({engine,message:error.message,diagnostics,mediaWire});if(page)"); // 失敗原因を推測せず、実画面と模擬通信の診断を残します。
await copyFile('production/media/native-media-receiver.mjs',join(root,'tools/native-media-receiver.mjs')); // 受信確認用のコードは公開物とは分けます。
text="import {nativeMediaReceiver} from './native-media-receiver.mjs'; // バイナリを本当のTLSソケットで受信する試験補助です。\nimport {createHash} from 'node:crypto'; // 受信バイトとファイル名のSHA-256を照合します。\n"+text; // 本体コードのfetchやBlobは差し替えません。
change("  async function browser(cloud=false){", "  const receiver=await nativeMediaReceiver(async(name,body)=>{mediaWire.push({name,receivedBytes:body.length});assert.equal(name,'M_'+createHash('sha256').update(body).digest('hex')+'.bin');if(holdMedia)await heldPromise;if(failMedia)return {status:503,body:{}};if(binaries.has(name))return {status:409,body:{}};mediaPuts++;binaries.set(name,body);return {status:201,body:binaryMeta(name)};}); // 実際に届いたファイル本体だけを合成クラウドへ保管します。\n  async function browser(cloud=false){"); // 空のpostDataを実体と誤認する検証側の問題を解消します。
change("{headless:true,viewport:{width:390,height:844},hasTouch:true,serviceWorkers:'block'", "{headless:true,ignoreHTTPSErrors:true,proxy:receiver.proxy,viewport:{width:390,height:844},hasTouch:true,serviceWorkers:'block'"); // 合成コンテキストだけで短期証明書とループバック受信先を使用します。本番のTLSやCSPは変えません。
change("if(holdMedia)await heldPromise;if(failMedia)return reply(503,{});if(binaries.has(name))return reply(409,{});mediaPuts++;const body=request.postDataBuffer();mediaWire.push({name,bytes:body?.length??null,type:request.headers()['content-type']});binaries.set(name,body);return reply(201,binaryMeta(name));", "mediaWire.push({name,inspectorBytes:request.postDataBuffer()?.length??null});return route.continue();"); // URL・本文を変えず、元のGraphオリジン宛ての通信をテスト用受信先へ届けます。
change("assert.equal(binaries.size,2);assert.equal(mediaPuts,2);","assert.equal(binaries.size,2);assert.equal(mediaPuts,2);assert([...binaries.values()].some(body=>body.equals(png)));assert([...binaries.values()].some(body=>body.equals(mp4)));"); // 実受信したPNGとMP4が元の合成ファイルに完全一致することを要求します。
change("for(const context of contexts)await context.close();", "for(const context of contexts)await context.close();await receiver.close();for(const message of receiver.errors)errors.push({engine,message});await writeFile(join(reports,engine+'-transport.json'),JSON.stringify({events:receiver.events,errors:receiver.errors},null,2));"); // 失敗時も受信診断を残し、合成サーバーエラーを隠しません。
change("await page.screenshot({path:join(reports,engine+'-media.png'),fullPage:true});", "await page.screenshot({path:join(reports,engine+'-media.png'),fullPage:true});await writeFile(join(reports,engine+'-wire.json'),JSON.stringify(mediaWire,null,2));"); // 合格時もインスペクタ表示と実受信の違いを証拠に残します。
await writeFile(file,text); // 既存の36ケースと全合格条件を維持します。
