import {readFile,writeFile} from 'node:fs/promises'; // 添付の実ブラウザ試験だけを整えます。
import {join,resolve} from 'node:path'; // 検証コードの位置を固定します。
import assert from 'node:assert/strict'; // 既知の試験にだけ差分を適用します。
const file=join(resolve(process.argv[2]),'tools/media-browser.mjs');let text=await readFile(file,'utf8'); // 公開ランタイムは変更しません。
function change(before,after){assert.equal(text.split(before).length,2,before);text=text.replace(before,after);} // 該当箇所を一つだけ置き換えます。
change("await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.readyState>=2);await video.evaluate(async v=>{v.muted=true;await v.play();});","await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.readyState>=1);await video.evaluate(async v=>{v.muted=true;await Promise.race([v.play(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('VIDEO_PLAY_TIMEOUT')),10000))]);});await page.waitForFunction(()=>document.querySelector('#mediaPreviewBody video')?.readyState>=2);"); // metadata先読みではフレーム取得を再生要求の前提にせず、実再生後のデコードを検査します。
change("const contexts=[];const files=new Map(),binaries=new Map();","const contexts=[],mediaWire=[];const files=new Map(),binaries=new Map();"); // 模擬HTTPのバイナリ受信状態を記録します。
change("mediaPuts++;binaries.set(name,request.postDataBuffer());","mediaPuts++;const body=request.postDataBuffer();mediaWire.push({name,bytes:body?.length??null,type:request.headers()['content-type']});binaries.set(name,body);"); // 認証トークンは記録せず、サイズと種類だけを診断します。
change("}catch(error){errors.push({engine,message:error.message});if(page)","}catch(error){const diagnostics=page?await page.evaluate(()=>{const v=document.querySelector('#mediaPreviewBody video');return {notice:document.getElementById('notice')?.textContent,save:document.getElementById('saveFeedback')?.textContent,media:document.getElementById('mediaSyncStatus')?.textContent,mediaDetail:document.getElementById('mediaSyncDetail')?.textContent,preview:document.getElementById('mediaPreviewMessage')?.textContent,video:v?{readyState:v.readyState,networkState:v.networkState,error:v.error?.code,currentTime:v.currentTime,duration:v.duration,paused:v.paused,videoWidth:v.videoWidth}:null};}).catch(()=>null):null;errors.push({engine,message:error.message,diagnostics,mediaWire});if(page)"); // 失敗原因を推測せず、実画面と模擬通信の診断を残します。
await writeFile(file,text); // 既存の36ケースと全合格条件を維持します。
