import {categoryName,matches} from './catalog.mjs';
export function createPicker(){
  const dialog=document.createElement('dialog');dialog.className='search-picker';dialog.id='searchPicker';dialog.setAttribute('aria-labelledby','pickerTitle');
  dialog.innerHTML='<div class="section-head"><h2 id="pickerTitle"></h2><button type="button" id="pickerClose">閉じる</button></div><p id="pickerHelp" class="subtle"></p><label id="pickerFilterLabel" hidden>カテゴリーで絞る<select id="pickerFilter"></select></label><label>検索<input id="pickerQuery" type="search" autocomplete="off" placeholder="文字を入力して絞り込み"></label><div id="pickerSelection" hidden><p id="pickerSelectedCount" role="status" aria-live="polite"></p><div id="pickerSelected"></div><button type="button" id="pickerClear">選択をすべて外す</button></div><p id="pickerCount" role="status" class="subtle"></p><div id="pickerResults" class="picker-results"></div><button type="button" id="pickerNew" class="primary" hidden></button><button type="button" id="pickerApply" class="primary" hidden>選択した用語を反映</button><p id="pickerError" role="alert"></p>';
  document.body.append(dialog);const get=id=>dialog.querySelector('#'+id);let options=null,origin=null,filter='',busy=false,selected=new Map();
  const key=value=>options.key(value);
  function toggle(value){if(busy)return;const id=key(value);if(selected.has(id))selected.delete(id);else{if(selected.size>=options.maxSelections){get('pickerError').textContent='関連用語は'+options.maxSelections+'語まで選択できます。';draw();return;}selected.set(id,value);}get('pickerError').textContent='';draw();}
  function draw(){if(!options)return;const activeKey=document.activeElement?.dataset.pickerKey,query=get('pickerQuery').value,all=options.items(filter,query),result=get('pickerResults'),scroll=result.scrollTop;result.replaceChildren();let previousGroup;
    for(const item of all.slice(0,100)){
      if(options.groupBy&&item.group!==previousGroup){const heading=document.createElement('h3');heading.className='picker-group';heading.textContent=item.group;result.append(heading);previousGroup=item.group;}
      const option=document.createElement(options.multiple?'label':'button');option.className='picker-option';
      if(options.multiple){const input=document.createElement('input');input.type='checkbox';input.dataset.pickerKey=key(item.value);input.checked=selected.has(key(item.value));input.onchange=()=>toggle(item.value);input.setAttribute('aria-label',item.label);option.append(input);}else{option.type='button';option.onclick=()=>choose(item.value);}
      const label=document.createElement('strong');label.textContent=item.label;option.append(label);if(item.detail){const detail=document.createElement('small');detail.textContent=item.detail;option.append(detail);}result.append(option);
    }
    result.scrollTop=scroll;if(activeKey)[...result.querySelectorAll('input')].find(input=>input.dataset.pickerKey===activeKey)?.focus({preventScroll:true});
    get('pickerCount').textContent=all.length?`${all.length}件${all.length>100?'（先頭100件。検索で絞ってください）':''}`:(options.emptyText||'候補がありません。新規入力するか、検索条件を変えてください。');
    const value=categoryName(query);get('pickerNew').hidden=!(options.allowCreate&&query.trim()&&value.length<=options.maxLength&&!all.some(item=>matches(item.label,query)&&item.label===value));get('pickerNew').textContent=options.allowCreate?`＋ 「${query.trim()}」を${options.createLabel||'使う'}`:'';
    if(options.multiple){get('pickerSelectedCount').textContent='選択中 '+selected.size+'語';get('pickerSelected').replaceChildren();for(const [id,value]of selected){const button=document.createElement('button');button.type='button';button.className='term-chip';button.textContent=options.label(value)+' ×';button.setAttribute('aria-label',options.label(value)+'を選択から外す');button.onclick=()=>{selected.delete(id);draw();};get('pickerSelected').append(button);}get('pickerApply').textContent=selected.size?'選択した'+selected.size+'語を反映':'関連用語なしで反映';}
  }
  async function choose(value){if(busy||!options)return;busy=true;get('pickerError').textContent='';get('pickerResults').setAttribute('aria-busy','true');try{await options.onChoose(value);dialog.close();}catch(error){get('pickerError').textContent=error.message||'読み込めませんでした。';}finally{busy=false;get('pickerResults').removeAttribute('aria-busy');}}
  get('pickerClose').onclick=()=>{if(!busy)dialog.close();};get('pickerQuery').oninput=draw;get('pickerQuery').onkeydown=event=>{if(event.key==='Enter')event.preventDefault();};get('pickerFilter').onchange=()=>{filter=get('pickerFilter').value;draw();};get('pickerNew').onclick=()=>choose(get('pickerQuery').value.trim());get('pickerApply').onclick=()=>choose([...selected.values()]);get('pickerClear').onclick=()=>{if(!busy){selected.clear();draw();}};
  dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',()=>{const restore=options?.restoreFocus;options=null;selected.clear();if(origin?.isConnected)origin.focus({preventScroll:true});else restore?.();});
  return {open(config){options=config;origin=document.activeElement;filter=config.filter||'';busy=false;selected=new Map((config.selected||[]).map(value=>[config.key(value),value]));dialog.classList.toggle('picker-multiple',Boolean(config.multiple));get('pickerSelection').hidden=!config.multiple;get('pickerApply').hidden=!config.multiple;get('pickerError').textContent='';get('pickerTitle').textContent=config.title;get('pickerHelp').textContent=config.help||'';get('pickerQuery').value=config.query||'';get('pickerQuery').maxLength=config.maxLength||160;get('pickerFilterLabel').hidden=!config.categories;get('pickerFilter').replaceChildren();
    if(config.categories)for(const name of ['',...config.categories]){const option=document.createElement('option');option.value=name;option.textContent=name||'すべてのカテゴリー';get('pickerFilter').append(option);}get('pickerFilter').value=filter;draw();dialog.showModal();get('pickerQuery').focus();
  }};
}
