import { readFile, writeFile, copyFile, mkdir } from 'node:fs/promises'; // 今回の公開版だけに修正を適用します。
import { resolve, join } from 'node:path'; // 明示された作業領域を指定します。
import { fileURLToPath } from 'node:url'; // 同梱ファイルの位置を確定します。
import assert from 'node:assert/strict'; // 想定外の旧ソースへ適用しません。
const root = resolve(process.argv[2]); const web = join(root, 'web'); const here = fileURLToPath(new URL('./', import.meta.url)); // 旧データ領域ではなく公開ソースを対象にします。
function replace(text, before, after) { assert.equal(text.split(before).length, 2, 'Patch target mismatch: ' + before.slice(0, 80)); return text.replace(before, after); } // 各修正は一意の旧コードが見つかった時だけ実施します。
function line(text, prefix, after) { const found = text.split('\n').filter(value => value.startsWith(prefix)); assert.equal(found.length, 1, 'Line target mismatch: ' + prefix); return text.replace(found[0], after); } // コメント除去版でも同じ実行行を置換します。
let app = await readFile(join(web, 'app.mjs'), 'utf8'); // 検査済み0.3.2の画面制御を読みます。
app = "import { draftErrors, rowsFromDetail, copyTitle } from './draft.mjs'; // 入力確認と原本を変えないコピーを共用します。\nlet saving = false; // 保存処理を重複して開始させません。\n" + app; // 新機能を既存ロジックから分離して追加します。
app = line(app, 'function message(', "function message(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);if(error&&$('editor').hidden===false)saveFeedback(text,'error');} // エラーを画面上部と保存ボタンの近くへ表示します。"); // スクロール先で保存失敗が見えなくなる問題を改善します。
app = line(app, 'function rowFromItem(', "function rowFromItem(item,objects){const row=rowsFromDetail({operation:{body:{payload:{items:[item],goal:''}}},objects})[0];if(row.term&&!terms.some(t=>t.ID===row.termId))terms.push(row.term);return row;} // 作戦原文とドリルの目的をコピー時も保持します。"); // 旧画面の個別再利用にも同じ読戻しを適用します。
app = line(app, 'function resetDraft(', "function resetDraft(){editRevision=null;rows=[newRow()];$('title').value='';$('goal').value='';$('team').value='U15';$('players').value='8';$('totalMinutes').value='120';renderRows();dirty=false;$('draftMode').textContent='新規作成 · 新しい練習として保存します。';saveFeedback('練習名・ゴール・練習項目を入力して保存してください。');page('editor');} // 既存の記録を変えず新しい計画を用意します。"); // 新しい計画であることを明示します。
app = replace(app, "function requireDraftSafe(){return", "function requireDraftSafe(){if(saving){message('保存中です。完了してから操作してください。');return false;}return"); // 保存中の新規作成で入力を消しません。
app = replace(app, "if(!b)return;guard(async()=>{", "if(!b||saving)return;guard(async()=>{"); // 保存中に新規作成や画面切替で入力を変えません。
app = replace(app, "if(b.dataset.open)await openDetail(b.dataset.open);", "if(b.dataset.open)await openDetail(b.dataset.open);if(b.dataset.copy){if(!requireDraftSafe())return;loadDraft(await request('detail',{revisionId:b.dataset.copy}),true);}"); // 一覧から計画全体のコピーを作れます。
app = replace(app, "rows.push({...rowFromItem(item,currentDetail.objects),id:uuid()});", "if(rows.length===1&&!rows[0].name&&!rows[0].rule&&!rows[0].canvasRaw)rows=[];rows.push({...rowFromItem(item,currentDetail.objects),id:uuid()});"); // 個別再利用時に最初の空白明細が残るのを防ぎます。
app = replace(app, "variationName\" value=\"${e(r.variationName)}\" maxlength=\"160\" required", "variationName\" value=\"${e(r.variationName)}\" maxlength=\"160\" placeholder=\"基本条件\""); // Variationの空欄を既存の基本条件として扱える表示にします。
app = replace(app, "value=\"${Number(r.minutes)}\" required", "value=\"${Number(r.minutes)}\" inputmode=\"numeric\" required"); // iPhoneで数値の入力をしやすくします。
app = line(app, "$('planForm').addEventListener('input'", "$('planForm').addEventListener('input',event=>{dirty=true;event.target.removeAttribute('aria-invalid');totals();saveFeedback('未保存の変更があります。');}); // 入力が変わった後は保存済みと表示しません。"); // 保存状態を入力ごとに更新します。
app = line(app, "$('planForm').addEventListener('submit'", `$('planForm').addEventListener('submit',event=>{event.preventDefault();if(saving)return;guard(async()=>{ // ブラウザの無言の必須チェックではなく明示した保存処理を使用します。
  if(!initialized||$('editorFields').disabled)throw new Error('端末保存の準備ができていません。別のタブや保存エラーを確認してください。'); // 準備失敗を保存成功と扱いません。
  if(editRevision&&!dirty){saveFeedback('✓ この計画は保存済みです。','success');return;} // 保存直後の連打で不要な改訂を増やしません。
  document.activeElement?.blur();gather();const input={title:$('title').value.trim(),goal:$('goal').value.trim(),team:$('team').value.trim(),players:$('players').value,totalMinutes:$('totalMinutes').value,items:structuredClone(rows)}; // 入力確定後のスナップショットを取得します。
  for(const row of input.items){row.name=String(row.name||'').trim();row.variationName=String(row.variationName||'').trim()||'基本条件';} // 名称の空白と基本条件を統一します。
  document.querySelectorAll('[aria-invalid]').forEach(node=>node.removeAttribute('aria-invalid'));const issues=draftErrors(input); // 必須項目と時間超過の理由を集めます。
  if(issues.length){saveFeedback('保存できません。\\n'+issues.map(issue=>issue.message).join('\\n'),'error');message('保存前に入力内容を確認してください。保存ボタンの近くに理由を表示しています。',true);saveFeedback('保存できません。\\n'+issues.map(issue=>issue.message).join('\\n'),'error');for(const issue of issues){const node=issue.index===null?$(issue.field):$('items').children[issue.index]?.querySelector('[data-field="'+issue.field+'"]');node?.setAttribute('aria-invalid','true');}const first=issues[0];const target=first.index===null?$(first.field):$('items').children[first.index]?.querySelector('[data-field="'+first.field+'"]');target?.focus({preventScroll:true});target?.scrollIntoView({block:'center',behavior:'smooth'});return;} // 問題箇所を強調し入力を消しません。
  saving=true;$('editorFields').disabled=true;saveFeedback('端末に保存しています…'); // 二重タップ中は新しい書込を受け付けません。
  try{const result=await request('savePlan',{revisionId:editRevision,input});editRevision=result.operation.body.opId;rows=input.items;dirty=false;refreshState(result.state);const detail=await request('detail',{revisionId:editRevision});rows=rowsFromDetail(detail);renderRows();$('draftMode').textContent='保存済みの計画を編集中 · 次の保存はこの計画の新しい版になります。';message('この端末への保存が完了しました。'+(cloudReady?'続けてOneDriveへ反映します。':'端末のみの保存です。他の端末へはまだ同期されていません。'));saveFeedback('✓ 端末に保存しました。'+new Date().toLocaleTimeString('ja-JP'),'success');scheduleSync();} // 保存確定後にだけ成功を表示します。
  catch(error){saveFeedback(error.message||'保存に失敗しました。入力内容は残しています。','error');throw error;} // 応答不明でも自動で再保存しません。
  finally{saving=false;$('editorFields').disabled=!initialized||Boolean(state?.blocked);} // 書込停止の状態を保持しながら操作を戻します。
});}); // 保存イベントを閉じます。`); // 保存失敗の表示と二重送信防止を追加します。
app = line(app, "$('editPlan').onclick", "$('editPlan').onclick=()=>guard(async()=>{if(saving||!requireDraftSafe())return;loadDraft(currentDetail,false);}); // 明示した時だけ元の計画を改訂します。\n$('copyPlan').onclick=()=>guard(async()=>{if(saving||!requireDraftSafe())return;loadDraft(currentDetail,true);}); // 実績と振り返りを持ち込まず別計画を作ります。"); // 編集とコピーを別操作にします。
app = replace(app, "const detail=await request('detail',{revisionId:id});currentDetail=detail;", "const detail=await request('detail',{revisionId:id});if(selected!==id)$('reflection').value='';currentDetail=detail;"); // 他の計画の振り返り入力を持ち越しません。
app = replace(app, "$('handoff').disabled=!ready||!cloudReady;", "$('copyPlan').disabled=!detail.objects.length;$('handoff').disabled=!ready||!cloudReady;"); // 必要な版が揃っている場合だけコピーできます。
app = replace(app, "端末保存の準備ができました。最初に検証用の練習を保存してください。", "端末保存の準備ができました。練習名・ゴール・練習項目を入力して保存してください。"); // 日常利用向けの案内へ変更します。
app = app.replaceAll('本人のOneDrive検証領域', '本人のOneDrive保存領域').replaceAll('検証フォルダを接続', '保存フォルダを接続').replaceAll('新規検証フォルダを作る確認', '保存フォルダを使用する確認').replaceAll('すべての検証タブ', 'このアプリのすべてのタブ'); // 保存先自体を変えず案内を整えます。
app += `\nfunction saveFeedback(text,kind=''){const node=$('saveFeedback');node.textContent=text;node.className=kind;node.setAttribute('role',kind==='error'?'alert':'status');} // 保存の結果をボタン直上で確認できます。
function loadDraft(detail,copy){const payload=detail.operation.body.payload;const next=rowsFromDetail(detail,copy);for(const row of next)if(!terms.some(term=>term.ID===row.termId))terms.push(row.term);for(const key of ['title','goal','team','players','totalMinutes'])$(key).value=payload[key];if(copy)$('title').value=copyTitle(payload.title);rows=next;editRevision=copy?null:detail.operation.body.opId;dirty=copy;renderRows();$('draftMode').textContent=copy?'コピーから新規作成 · 元の練習と実績・振り返りは変更しません。':'編集モード · この計画の新しい版として保存します。';saveFeedback(copy?'コピーを用意しました。内容を変えて「端末に保存」を押してください。':'変更内容を確認して保存してください。');page('editor');$('title').focus({preventScroll:true});$('editor').scrollIntoView({block:'start',behavior:'smooth'});} // コピーは保存するまで新しいDBレコードを作りません。
`; // 純粋なコピーと表示機能を追加します。
await writeFile(join(web, 'app.mjs'), app); // 確認した画面制御を書き出します。
let html = await readFile(join(web, 'index.html'), 'utf8'); // 公開画面の構造を更新します。
html = html.replace('<body>', '<body><div class="zeroone-splash" aria-hidden="true"><img src="./icons/icon-512.webp?v=20261007d" alt=""><strong>ZERO ONE</strong><span>PRACTICE</span></div>'); // ZERO ONEシリーズ共通の起動画面を追加します。
html = html.replaceAll('0.3.2', '1.0.0').replace('ZERO ONE PRACTICE · 検証版1.0.0', 'ZERO ONE PRACTICE').replace('BROWSER LAB / 1.0.0', 'PLAN · PRACTICE · REFLECT / 1.0.0').replace('検証版・本番とは別保存', '端末保存 · AIなしでも利用可').replace('ZERO ONE PRACTICE · Browser Lab 1.0.0', 'ZERO ONE PRACTICE · 1.0.0'); // 本番の機能範囲とバージョンを表示します。
html = replace(html, '<div class="brand">ZERO<br>ONE<span>PRACTICE</span></div>', '<div class="brand"><img src="./icons/icon-512.webp?v=20261007d" width="58" height="58" alt="ZERO ONE"><div class="wordmark">ZERO ONE<span class="product">PRACTICE</span></div></div>'); // 承認済みアイコンとZERO ONEの組版を使います。
html = replace(html, '<link rel="stylesheet" href="./style.css">', '<link rel="icon" href="./favicon-practice-20261007f.ico" type="image/x-icon" sizes="16x16 32x32 48x48"><link rel="alternate icon" href="./favicon-practice-32-20261007f.png" type="image/png" sizes="32x32">\n<link rel="apple-touch-icon" sizes="180x180" href="./icons/apple-touch-icon.png?v=20261007d">\n<meta name="apple-mobile-web-app-title" content="PRACTICE">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<link rel="stylesheet" href="./style.css">\n<link rel="stylesheet" href="./series.css?v=20261007d">'); // ホーム画面とブラウザタブのアイコンを揃えます。
html = replace(html, '<form id="planForm">', '<p class="draft-mode" id="draftMode">新規作成</p><p class="form-hint">練習名・対象・人数・全体時間・ゴール・各項目名と時間は必須です。作戦図は任意です。</p><form id="planForm" novalidate>'); // 自前の入力チェックが必ず実行されるようにします。
html = replace(html, '<fieldset id="editorFields" disabled><div', '<fieldset id="editorFields" disabled><div class="plan-basics"><div'); // 練習の全体設定をまとめます。
html = replace(html, '</textarea></label><div class="section-head"><h2>練習の流れ</h2>', '</textarea></label></div><div class="section-head"><h2>練習の流れ</h2>'); // 基本設定のカードを閉じます。
html = replace(html, '<div class="actions"><button type="button" id="addItem">＋ 練習を追加</button><button type="submit" class="primary">端末に保存</button></div>', '<div class="actions"><button type="button" id="addItem">＋ 練習を追加</button></div><div class="save-dock"><div class="save-info"><p id="saveFeedback" role="status" aria-live="polite">入力して保存してください。</p><small>「端末保存」と「OneDriveへの同期」は別です。</small></div><button type="submit" id="savePlan" class="primary">端末に保存</button></div>'); // 保存結果をスクロール位置に関係なく確認できる場所へ置きます。
html = replace(html, '<button id="editPlan">この計画を編集</button>', '<button id="copyPlan" class="copy-button">コピーして新規作成</button><button id="editPlan">この計画を編集</button>'); // 原本の更新と複製を分けます。
html = html.replaceAll('新規検証フォルダ', '保存フォルダ').replace('を作成することを確認しました。', 'を使用することを確認しました（既存データを引き継ぐため名前は変更しません）。').replace('検証領域を接続', 'OneDriveに接続').replace('検証フォルダ内', '保存フォルダ内'); // クラウドの既存パスは変えず本人の確認を維持します。
html = replace(html, '<h3>本人のOneDriveに接続</h3>', '<h3>本人のOneDriveに接続</h3><p class="privacy-note">PCとiPhoneの同期には本人のMicrosoft設定とサインインが必要です。この端末での接続・同期結果を確認するまでは、同期済みとして扱いません。</p>'); // 未認証の同期を完成済みと見せません。
html = replace(html, '<span id="environment"></span></footer>', '<span id="environment"></span><span><a href="https://yuge-u.github.io/basketball-tactics-board/" target="_blank" rel="noopener noreferrer">CANVAS ↗</a><a href="https://yuge-u.github.io/zero-one-terminology/" target="_blank" rel="noopener noreferrer">TERMINOLOGY ↗</a></span></footer>'); // 既存シリーズを変更せず行き来できます。
html = html.replaceAll('type="number" min=', 'type="number" inputmode="numeric" min='); // 数字を入力しやすいキーボードにします。
await writeFile(join(web, 'index.html'), html); // 更新した画面を書き出します。
let ui = await readFile(join(web, 'ui.mjs'), 'utf8'); // 保存済み一覧へコピー入口を追加します。
ui = replace(ui, '<article class="saved-card">', '<article class="saved-card" data-practice-id="${o.body.entityId}" data-revision="${o.body.opId}">'); // 明示的な計画IDを表示試験でも照合します。
ui = replace(ui, '<button data-open="${o.body.opId}">開く</button>', '<button data-open="${o.body.opId}">開く</button><button class="copy-button" data-copy="${o.body.opId}">コピーして新規作成</button>'); // 一覧から一操作でコピーを開始できます。
await writeFile(join(web, 'ui.mjs'), ui); // 一覧の既存表示と競合選択を保ちます。
for (const name of ['config.mjs','sw.js']) { let text = await readFile(join(web,name),'utf8'); assert(text.includes('0.3.2')); text=text.replaceAll('0.3.2','1.0.0'); if(name==='sw.js')text=replace(text,"'./style.css',", "'./style.css','./series.css','./draft.mjs','./icons/icon-192.webp','./icons/icon-512.webp','./icons/apple-touch-icon.png',"); await writeFile(join(web,name),text); } // DB名やOSロックを変えず版と事前取得を更新します。
let service = await readFile(join(web, 'core/service.mjs'), 'utf8'); service=replace(service,"appVersion:'0.3.0'","appVersion:'1.0.0'"); await writeFile(join(web,'core/service.mjs'),service); // 診断の版表示だけを実行版に合わせます。
const manifest = JSON.parse(await readFile(join(web,'manifest.webmanifest'),'utf8')); Object.assign(manifest,{name:'ZERO ONE PRACTICE',short_name:'PRACTICE',background_color:'#f6f8fb',theme_color:'#09111c',icons:[{src:'./icons/icon-192.webp?v=20261007d',sizes:'192x192',type:'image/webp',purpose:'any'},{src:'./icons/icon-512.webp?v=20261007d',sizes:'512x512',type:'image/webp',purpose:'any'}]}); await writeFile(join(web,'manifest.webmanifest'),JSON.stringify(manifest,null,2)+'\n'); // id・start_url・scopeは既存値を維持します。
await copyFile(join(here,'draft.mjs'),join(web,'draft.mjs')); await copyFile(join(here,'series.css'),join(web,'series.css')); // 共通機能とシリーズの外観を配置します。
const icons=JSON.parse(await readFile(join(here,'icons.json'),'utf8')); await mkdir(join(web,'icons'),{recursive:true}); for(const [name,data] of Object.entries(icons)){assert(['icon-192.webp','icon-512.webp','apple-touch-icon.png'].includes(name));await writeFile(join(web,'icons',name),Buffer.from(data,'base64'));} // 承認済み画像のリサイズ済みバイトだけを書き出します。
for(const name of ['tools/serve.mjs','tools/serve-project.mjs']){let text=await readFile(join(root,name),'utf8');text=text.replace("'.wasm':'application/wasm'","'.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.wasm':'application/wasm'");await writeFile(join(root,name),text);} // 検証サーバーにもアイコンの正しいMIMEを追加します。
console.log('Applied v1.0.0: visible save validation, safe plan copy and approved series artwork. Data paths unchanged.'); // 実行した変更を記録します。
