import {categoryName,matches} from './catalog.mjs'; // 検索の表記を画面全体で揃えます。
export function createPicker(){ // iPhoneでも検索と選択を使える共通ダイアログです。
  const dialog=document.createElement('dialog');dialog.className='search-picker';dialog.id='searchPicker';dialog.setAttribute('aria-labelledby','pickerTitle'); // 選択対象を読み上げでも示します。
  dialog.innerHTML='<div class="section-head"><h2 id="pickerTitle"></h2><button type="button" id="pickerClose">閉じる</button></div><p id="pickerHelp" class="subtle"></p><label id="pickerFilterLabel" hidden>カテゴリーで絞る<select id="pickerFilter"></select></label><label>検索<input id="pickerQuery" type="search" autocomplete="off" placeholder="文字を入力して絞り込み"></label><p id="pickerCount" role="status" class="subtle"></p><div id="pickerResults" class="picker-results"></div><button type="button" id="pickerNew" class="primary" hidden></button><p id="pickerError" role="alert"></p>'; // 動的な個人データはこのHTMLへ埋め込みません。
  document.body.append(dialog);const get=id=>dialog.querySelector('#'+id);let options=null,origin=null,filter='',busy=false; // 選択中の状態をダイアログ内で保持します。
  function draw(){if(!options)return;const query=get('pickerQuery').value;const all=options.items(filter,query);const result=get('pickerResults');result.replaceChildren(); // 最新の条件で候補を描き直します。
    for(const item of all.slice(0,100)){const button=document.createElement('button');button.type='button';button.className='picker-option';const label=document.createElement('strong');label.textContent=item.label;button.append(label);if(item.detail){const detail=document.createElement('small');detail.textContent=item.detail;button.append(detail);}button.onclick=()=>choose(item.value);result.append(button);} // ユーザー文字列はtextContentで表示します。
    get('pickerCount').textContent=all.length?`${all.length}件${all.length>100?'（先頭100件。検索で絞ってください）':''}`:'候補がありません。新規入力するか、検索条件を変えてください。'; // 空結果と表示件数を説明します。
    const value=categoryName(query);const canCreate=options.allowCreate&&query.trim()&&value.length<=options.maxLength&&!all.some(item=>matches(item.label,query)&&item.label===value);get('pickerNew').hidden=!canCreate;get('pickerNew').textContent=options.allowCreate?`＋ 「${query.trim()}」を${options.createLabel||'使う'}`:''; // 自由入力の追加を明示します。
  } // 検索描画を閉じます。
  async function choose(value){if(busy||!options)return;busy=true;get('pickerError').textContent='';get('pickerResults').setAttribute('aria-busy','true');try{await options.onChoose(value);dialog.close();}catch(error){get('pickerError').textContent=error.message||'読み込めませんでした。';}finally{busy=false;get('pickerResults').removeAttribute('aria-busy');}} // 読込失敗時はフォームを消しません。
  get('pickerClose').onclick=()=>{if(!busy)dialog.close();};get('pickerQuery').oninput=draw;get('pickerQuery').onkeydown=event=>{if(event.key==='Enter')event.preventDefault();}; // Enterで計画を誤保存させません。
  get('pickerFilter').onchange=()=>{filter=get('pickerFilter').value;draw();};get('pickerNew').onclick=()=>choose(get('pickerQuery').value.trim()); // 追加は選択と同じ安全な経路を使います。
  dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',()=>{options=null;if(origin?.isConnected)origin.focus({preventScroll:true});}); // 選択終了後は元の操作へ戻します。
  return {open(config){options=config;origin=document.activeElement;filter=config.filter||'';busy=false;get('pickerError').textContent='';get('pickerTitle').textContent=config.title;get('pickerHelp').textContent=config.help||'';get('pickerQuery').value=config.query||'';get('pickerQuery').maxLength=config.maxLength||160;get('pickerFilterLabel').hidden=!config.categories;get('pickerFilter').replaceChildren(); // 用途に合わせて検索欄を準備します。
    if(config.categories)for(const name of ['',...config.categories]){const option=document.createElement('option');option.value=name;option.textContent=name||'すべてのカテゴリー';get('pickerFilter').append(option);}get('pickerFilter').value=filter;draw();dialog.showModal();get('pickerQuery').focus(); // 選択中のカテゴリーと検索条件を適用します。
  }}; // 公開操作はダイアログを開く関数だけです。
} // 共通検索ダイアログを閉じます。
