import {readFile,writeFile,copyFile,mkdir} from 'node:fs/promises'; // 検証用の作業コピーだけを変更します。
import {join,resolve} from 'node:path'; // 対象のパスを固定します。
import assert from 'node:assert/strict'; // 想定外のソースへ適用しません。
const root=resolve(process.argv[2]),web=join(root,'web'); // 公開済み1.1.1を出発点にします。
function replace(text,before,after,count=1){assert.equal(text.split(before).length-1,count,'Reference patch mismatch: '+before.slice(0,90));return text.replaceAll(before,after);} // 置換位置が一致した場合だけ進みます。
async function patch(name,replacements){let text=await readFile(join(web,name),'utf8');for(const [from,to,count]of replacements)text=replace(text,from,to,count);await writeFile(join(web,name),text);} // 定義した差分だけを適用します。
await copyFile('production/references/reference-links.mjs',join(web,'reference-links.mjs')); // ファイル取得をしない参照専用モジュールを追加します。
await patch('core/model.mjs',[["import { sha256Text }", "import {validateReferences} from '../reference-links.mjs'; // 同期した閲覧リンクも検証します。\nimport { sha256Text }"],["itemIds.add(item.id); if(item.category", "itemIds.add(item.id); validateReferences(item.references); if(item.category"]]); // 旧版の任意フィールド欠如を許可しハッシュを書き換えません。
await patch('core/planner.mjs',[["import {categoryName}","import {validateReferences} from '../reference-links.mjs'; // 参考資料は任意のメニュー情報として保存します。\nimport {categoryName}"],["const id = row.id || uuid();", "const referenceFields=row.references!==undefined?{references:validateReferences(row.references)}:row.pinned?.references?{references:validateReferences(row.pinned.references)}:{}; const id = row.id || uuid();"],["section: row.section, category };", "section: row.section, category, ...referenceFields };"],["resolved:{variationName,goal:purpose,rule} };", "resolved:{variationName,goal:purpose,rule}, ...referenceFields };"]]); // 新規と固定版コピーの両方で参照を保持します。
await patch('draft.mjs',[["import { uuid }", "import {validateReferences} from './reference-links.mjs'; // 入力確認とコピーに参照情報を含めます。\nimport { uuid }"],["required(item.name, 'name',", "try{validateReferences(item.references);}catch(error){add('references',`${index+1}番目: ${error.message}`,index);}required(item.name, 'name',"],["category:item.category||'', name:", "category:item.category||'', references:validateReferences(item.references), name:"]]); // 編集後に固定版を外しても資料を落としません。
const serviceImport="import {makeReference,validateReferences} from '../reference-links.mjs'; // 参照先へ通信せず本人の保存領域だけを確認します。\n"; // 既存Graphの送信先制限を維持します。
let service=serviceImport+await readFile(join(web,'core/service.mjs'),'utf8'); // 同期エンジンは変更しません。
service=replace(service,"if(name==='savePlan')", "if(name==='referenceCheck'){const reference=makeReference(args.input,args.input?.id);ensure(this.cloud&&this.engine&&r.scope.startsWith('ms-'),'AUTH','OneDriveに接続してからリンクを追加してください。');const state=r.state();ensure(!state.blocked&&!state.lastError,'NOT_READY','OneDriveの同期状態を確認してください。');await this.cloud.check();this.referenceApprovals??=new Set();this.referenceApprovals.add(reference.url);return {reference,scope:r.scope};} // 新しい関連付けには本人接続の実確認を要求します。\n    if(name==='savePlan')"); // 許可はこのアカウントのWorker内だけで保持します。
service=replace(service,"const o=r.save({...p,", "const urls=p.payload.items.flatMap(item=>validateReferences(item.references).map(ref=>ref.url));if(urls.length){const known=new Set(r.operations().filter(op=>op.body.kind==='practice').flatMap(op=>op.body.payload.items.flatMap(item=>validateReferences(item.references).map(ref=>ref.url))));ensure(urls.every(url=>known.has(url)||this.referenceApprovals?.has(url)),'AUTH','新しい参考資料はOneDrive接続中に「リンクを追加」から登録してください。');}const o=r.save({...p,"); // 既存の参照コピーと解除はオフラインでも保存できます。
await writeFile(join(web,'core/service.mjs'),service); // 保存前に追加経路を検査し既存記録を保護します。
await patch('catalog.mjs',[["// カテゴリーは", "import {referenceKey} from './reference-links.mjs'; // 資料が異なるメニューも選択できます。\n// カテゴリーは"],["item.drillHash,item.variationHash])", "item.drillHash,item.variationHash,referenceKey(item.references)])"]]); // 内容違いの候補を誤って集約しません。
let app="import {MAX_REFERENCES,makeReference,validateReferences,referenceAccess} from './reference-links.mjs'; // 閲覧リンクだけを扱います。\n"+await readFile(join(web,'app.mjs'),'utf8'); // 保存先と認証設定はそのままです。
app=replace(app,"category:'',name:''","category:'',references:[],name:''"); // 新規メニューは資料なしで開始します。
app=replace(app,'<div class="item-foot">','${referenceMarkup(r,index,true)}<div class="item-foot">'); // メニューごとに折りたたみ欄を設けます。
app=replace(app,'<button data-reuse="${index}">','<button data-reuse="${index}">'); // 既存の再利用操作があることを確認します。
app=replace(app,'<div class="actions"><button data-reuse=', '${referenceMarkup(item,index,false)}<div class="actions"><button data-reuse='); // 保存した詳細でもリンクを開けるようにします。
app=replace(app,"!rows[0].canvasRaw)rows=[];", "!rows[0].canvasRaw&&!(rows[0].references||[]).length)rows=[];"); // 名前未入力でも追加済みの資料を勝手に捨てません。
app=replace(app,"));accountStatus(); // 入力前の固定パネル", "));accountStatus();refreshReferenceControls(); // 入力前の固定パネル"); // 切断・再認証・保存中にボタンを更新します。
app=replace(app,'時間・関連用語・Variation・条件・作戦をコピーします。','時間・関連用語・Variation・条件・作戦・参考資料をコピーします。'); // 再利用で引き継ぐ範囲を示します。
app+='\n'+await readFile('production/references/reference-ui.fragment.mjs','utf8'); // URL追加・解除のUI処理を追加します。
await writeFile(join(web,'app.mjs'),app); // ファイルのアップロードや外部プレビューは追加しません。
const dialog='<dialog id="referenceDialog" aria-labelledby="referenceHeading"><div class="section-head"><h2 id="referenceHeading">参考資料のリンク</h2><button id="closeReference" type="button">閉じる</button></div><p class="reference-help">OneDrive・Google Drive・Dropbox・iCloud Drive・YouTubeなどの閲覧用リンクを貼り付けます。写真・動画・PDFの本体は元の場所に残ります。</p><form id="referenceForm" novalidate><label>HTTPSリンク<input id="referenceUrl" type="url" inputmode="url" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="2048" placeholder="https://…" required></label><label>資料名（任意）<input id="referenceTitle" maxlength="160" placeholder="例：フットワークのお手本動画"></label><p id="referenceError" role="alert"></p><button id="referenceApply" type="submit" class="primary">このメニューに反映</button></form><p class="reference-help">OneDrive接続時のみ追加・変更できます。反映後に「練習を保存」を押してください。リンク先の閲覧権限は自動で付与されません。</p></dialog>'; // 外部選択画面を実装済みと表示しません。
await patch('index.html',[["<noscript>",dialog+'\n<noscript>'],['作戦図は任意です。','作戦図・参考資料は任意です。'],['APIキーやMicrosoftトークンは含めません。','APIキーやMicrosoftトークンは含めません。参考資料はリンク情報だけを含み、写真・動画・PDFの本体は含みません。']]); // バックアップの対象を明記します。
await writeFile(join(web,'series.css'),await readFile(join(web,'series.css'),'utf8')+'\n'+await readFile('production/references/reference.css','utf8')); // 承認済みの配色と小さい同期枠を維持します。
await patch('sw.js',[["'./picker.mjs',","'./picker.mjs','./reference-links.mjs',"]]); // オフラインの既存参照読込に必要なコードだけを取得します。
for(const name of ['config.mjs','index.html','sw.js','core/service.mjs'])await patch(name,[['1.1.1','1.2.1',(await readFile(join(web,name),'utf8')).split('1.1.1').length-1]]); // 未公開の直接添付候補とは違う版として識別します。
for(const name of ['production-scenarios.mjs','upgrade-check.mjs','save-status-browser.mjs','catalog-browser.mjs']){const file=join(root,'tools',name);let text=await readFile(file,'utf8');text=text.replaceAll('1.1.1','1.2.1').replaceAll('1\\.1\\.1','1\\.2\\.1');await writeFile(file,text);} // 元の回帰試験は残して版だけを更新します。
await mkdir(join(root,'tests'),{recursive:true});await copyFile('production/references/reference.test.mjs',join(root,'tests/reference.test.mjs')); // 新しい保存・境界・互換性の単体試験を組み込みます。
await copyFile('production/references/reference-browser.mjs',join(root,'tools/reference-browser.mjs')); // 実画面試験を独立して追加します。
console.log('Reference links only: no binary import, upload, external preview, or permission expansion.'); // 直接添付候補を配信しないことを示します。
