import {readFile,writeFile,copyFile,mkdir,cp} from 'node:fs/promises'; // 既知の1.1.1配信候補だけを更新します。
import {join,resolve} from 'node:path'; // 個人のファイルとは別のビルド領域です。
import assert from 'node:assert/strict'; // 差分の前提が崩れたら配信を止めます。
const root=resolve(process.argv[2]),web=join(root,'web'); // ローカル再構成先を固定します。
function replace(text,before,after,count=1){assert.equal(text.split(before).length-1,count,'Reference patch mismatch: '+before.slice(0,80));return text.replaceAll(before,after);} // 曖昧な一括置換をしません。
async function patch(name,changes,prefix=''){let text=await readFile(join(web,name),'utf8');for(const [before,after,count]of changes)text=replace(text,before,after,count);await writeFile(join(web,name),prefix+text);} // 表示と任意メタデータだけを変更します。
await cp(web,join(root,'reference-baseline-web'),{recursive:true}); // 直前1.1.1からの実更新試験の基準を残します。
for(const name of ['references.mjs','references-ui.mjs'])await copyFile('production/references/'+name,join(web,name)); // ファイル本体を扱わない専用部品です。
await patch('core/model.mjs',[["itemIds.add(item.id); if(item.category", "itemIds.add(item.id); normalizeReferences(item.references); if(item.category"]],"import {normalizeReferences} from '../references.mjs'; // 従来レコードは変更せず任意リンクを検査します。\n"); // 同期・復元でも危険なURLを受け入れません。
await patch('core/planner.mjs',[["const id = row.id || uuid();", "const references=normalizeReferences(row.references??row.pinned?.references);const id = row.id || uuid();"],["section: row.section, category };","section: row.section, category, references };"],["section:row.section, category, minutes:","section:row.section, category, references, minutes:"]],"import {normalizeReferences} from '../references.mjs'; // コピー先も独立したリンク配列を保持します。\n"); // 名前・条件・図を変更しても参考資料を落としません。
await patch('draft.mjs',[["required(item.name, 'name',","try{normalizeReferences(item.references??item.pinned?.references);}catch(error){add('references',`${index+1}番目：${error.message}`,index);}required(item.name, 'name',"],["category:item.category||'', name:","category:item.category||'', references:normalizeReferences(item.references), name:"]],"import {normalizeReferences} from './references.mjs'; // フォームと固定版読戻しに同じ検査を使います。\n"); // 過去のリンクを改変しません。
await patch('core/service.mjs',[["if(name==='savePlan') {const prior=","if(name==='referenceConnection'){ensure(this.graph&&this.engine&&this.cloud&&/^ms-[a-f0-9]{64}$/.test(r.scope),'AUTH','リンクの追加にはOneDriveへの接続が必要です。');ensure(globalThis.navigator?.onLine!==false&&!r.meta('blocked')&&!r.meta('lastError'),'AUTH','同期の問題を解消してからリンクを追加してください。');await this.cloud.check();return {scope:r.scope};} // 本人の専用フォルダーの読取確認だけを行います。\n    if(name==='savePlan') {if(hasNewReferences(args.input,r.operations()))await this.execute('referenceConnection',{});const prior="]],"import {hasNewReferences} from '../references.mjs'; // 新規URLの保存も接続確認なしには通しません。\n"); // 通常プランと既存リンクのコピーはオフラインでも扱えます。
await patch('catalog.mjs',[["item.drillHash,item.variationHash])","item.drillHash,item.variationHash,item.references||[]])"]]); // 参考資料だけ違うメニューを重複として隠しません。
await patch('app.mjs',[["category:'',name:'',minutes:10","category:'',references:[],name:'',minutes:10"],["</div></div></article>`).join('');for(const [index,r]of rows.entries())","</div></div>${referenceEditor(r,index)}</article>`).join('');for(const [index,r]of rows.entries())"],["作戦JSONを書出し</button></div></article>","作戦JSONを書出し</button></div>${referenceDetail(item)}</article>"],["accountStatus(); // 入力前の固定パネルでフォームを隠しません。","accountStatus();refreshReferenceControls(); // 同期状態に応じてリンク追加を制御します。"],["時間・関連用語・Variation・条件・作戦をコピーします。","時間・関連用語・Variation・条件・作戦・参考資料をコピーします。"]],"import {normalizeReferences,referenceAccess,MAX_REFERENCES} from './references.mjs'; // 添付実体でなくHTTPS参照を扱います。\nimport {referenceEditor,referenceDetail,createReferenceDialog} from './references-ui.mjs'; // プレビューを自動取得しない画面です。\n"); // その他の画面・認証は維持します。
const fragment=await readFile('production/references/reference-app.fragment.mjs','utf8');await writeFile(join(web,'app.mjs'),(await readFile(join(web,'app.mjs'),'utf8'))+'\n'+fragment); // アカウント条件と追加・解除操作を結合します。
await patch('index.html',[["APIキーやMicrosoftトークンは含めません。","APIキーやMicrosoftトークンは含めません。参考資料のリンク情報は含みますが、写真・動画・資料の本体は含みません。共有リンクの取扱いにも注意してください。"]]); // バックアップ範囲を正確に知らせます。
await writeFile(join(web,'series.css'),(await readFile(join(web,'series.css'),'utf8'))+'\n'+await readFile('production/references/references.css','utf8')); // 折りたたみの参考資料欄を小さく追加します。
await patch('sw.js',[["'./catalog.mjs','./picker.mjs',","'./catalog.mjs','./picker.mjs','./references.mjs','./references-ui.mjs',"]]); // 未取得の新部品がオフライン起動を妨げないよう事前取得します。
for(const name of ['web/config.mjs','web/index.html','web/sw.js','web/core/service.mjs','tools/production-scenarios.mjs','tools/upgrade-check.mjs','tools/save-status-browser.mjs','tools/catalog-browser.mjs']){const file=join(root,name);const text=await readFile(file,'utf8');assert(text.includes('1.1.1'),name);await writeFile(file,text.replaceAll('1.1.1','1.2.1'));} // 未公開のファイル添付候補とは別の版を配信します。
for(const name of ['tools/production-scenarios.mjs','tools/upgrade-check.mjs']){const file=join(root,name);await writeFile(file,replace(await readFile(file,'utf8'),'1\\.1\\.1','1\\.2\\.1'));} // 既存試験は版の期待値だけ更新します。
await mkdir(join(root,'tests'),{recursive:true});await copyFile('production/references/references.test.mjs',join(root,'tests/references.test.mjs')); // 保存層とURLの試験を必須化します。
await copyFile('production/references/references-browser.mjs',join(root,'tools/references-browser.mjs')); // 実画面の受入試験を配置します。
console.log('PRACTICE 1.2.1 reference links candidate; no file upload, new API scope, or automatic external fetch.'); // 本人の実機確認済みとは言いません。
let latest=await readFile(join(root,'tools/upgrade-check.mjs'),'utf8');latest=replace(latest,"resolve('baseline-web')","resolve('reference-baseline-web')");latest=replace(latest,"resolve('reports/upgrade')","resolve('reports/reference-upgrade')");latest=replace(latest,'/0\\.3\\.2/','/1\\.1\\.1/');latest=replace(latest,"name:'端末に保存',exact:true","name:'練習を保存',exact:true");latest=replace(latest,"from:'0.3.2'","from:'1.1.1'");await writeFile(join(root,'tools/reference-upgrade.mjs'),latest); // 直前1.1.1から同一ブラウザ・同一URLでのデータ保持も確認します。
