import test from 'node:test'; // 同期待機と保存継続の回帰試験を追加します。
import assert from 'node:assert/strict'; // 結果と回数を厳密に検証します。
import {DatabaseSync} from 'node:sqlite'; // 実SQLiteのトランザクションで確認します。
import {AppService} from '../web/core/service.mjs'; // 配信する実サービスを使用します。
import {WorkerBridge} from '../web/worker-bridge.mjs'; // 保存結果不明と通信タイムアウトを区別します。
import {SyncEngine} from '../web/core/sync.mjs'; // 履歴の内容検証を確認します。
import {GraphClient,OneDriveCloud} from '../web/core/graph.mjs'; // 重複メタデータ要求の削減を確認します。
const input=()=>({title:'合成練習',goal:'判断する',team:'U15',players:8,totalMinutes:40,items:[{name:'2対2',section:'BODY',minutes:15,term:{ID:'GBT-test','正式/標準用語':'Paint Touch',定義:'合成用語'},variationName:'基本',rule:'2ドリブル',canvasRaw:''}]}); // 個人データを使用しません。
const tick=()=>new Promise(done=>setTimeout(done,10)); // 通信解放前にローカル処理が進むか観測します。
function fixture(t){const service=new AppService(new DatabaseSync(':memory:'),'guest-local');t.after(()=>service.repo.close());return service;} // DBを試験ごとに分離します。
test('L01 同期の応答がなくても端末保存と読出しが完了する',async t=>{const s=fixture(t);let release;const held=new Promise(done=>release=done);s.cloud={check:()=>held};s.engine={sync:async()=>({done:true})};const sync=s.run('sync');let saved;const task=s.run('savePlan',{input:input()}).then(value=>saved=value);await tick();try{assert(saved);assert.equal((await s.run('state')).pending,1);assert.equal((await s.run('detail',{revisionId:saved.operation.body.opId})).operation.hash,saved.operation.hash);}finally{release();await Promise.all([sync,task]);}}); // ネットワークの待機解除を保存成功の条件にしません。
test('L02 通信中の振り返り保存も未送信のまま保持する',async t=>{const s=fixture(t),first=await s.run('savePlan',{input:input()});let release;s.cloud={check:()=>new Promise(done=>release=done)};s.engine={sync:async()=>({})};const sync=s.run('sync');await tick();await s.run('record',{revisionId:first.operation.body.opId,kind:'reflection',note:'合成記録'});assert.equal((await s.run('state')).pending,2);release();await sync;}); // 保存済み計画への実施記録も同期から分離します。
test('L03 closeは進行中の同期と保存の両方を待つ',async t=>{const s=new AppService(new DatabaseSync(':memory:'),'guest-local');let release;s.cloud={check:()=>new Promise(done=>release=done)};s.engine={sync:async()=>s.repo.state()};const sync=s.run('sync');await tick();const save=s.run('savePlan',{input:input()});let closed=false;const close=s.run('close').then(()=>closed=true);await tick();assert.equal(closed,false);release();await Promise.all([sync,save,close]);assert(closed);}); // 同期が触るDBを途中で閉じません。
test('L04 通信期限切れの後も保存要求を受け付け遅延応答は無視する',async()=>{let expire;const messages=[];let fatal=0;const bridge=new WorkerBridge({postMessage:m=>messages.push(m)},{onFatal:()=>fatal++,timers:{setTimeout(fn){expire=fn;return 1;},clearTimeout(){}}});const sync=bridge.call('sync');const rejected=assert.rejects(sync,{code:'NETWORK'});expire();await rejected;const save=bridge.call('savePlan');await bridge.receive({type:'result',id:1,value:'late'});await bridge.receive({type:'result',id:2,value:'saved'});assert.equal(await save,'saved');assert.equal(fatal,0);assert.equal(bridge.pending.size,0);}); // 通信遅延だけでは保存結果を不明にしません。
test('L05 端末書込の結果不明は自動再保存せず引き続き停止する',async()=>{let expire;let fatal=0;const bridge=new WorkerBridge({postMessage(){}},{onFatal:()=>fatal++,timers:{setTimeout(fn){expire=fn;return 1;},clearTimeout(){}}});const save=bridge.call('savePlan');const rejected=assert.rejects(save,/自動再保存せず/);expire();await rejected;assert.equal(fatal,1);assert(bridge.failed);}); // 二重保存を防ぐ既存の保護を緩めません。
test('L06 直前のメタデータだけを再利用し古い入力はGraphで再確認する',async()=>{let graph=0,downloads=0;const meta={id:'synthetic',size:2,'@microsoft.graph.downloadUrl':'https://synthetic.invalid/data'};const client=new GraphClient({getToken:async()=> 'synthetic',fetcher:async url=>{if(url.includes('graph.microsoft.com')){graph++;return Response.json(meta);}downloads++;return new Response('{}');}});await client.readText(meta,{fresh:true});assert.equal(graph,0);await client.readText(meta);assert.equal(graph,1);assert.equal(downloads,2);}); // 本文の検証用ダウンロードは省略しません。
test('L07 履歴の並列取得は最大4件で欠落を検知し未送信分を残す',async t=>{const s=fixture(t);for(let n=0;n<8;n++)await s.run('savePlan',{input:input()});const files=new Map();let active=0,peak=0;const cloud={scope:s.repo.scope,list:async()=>[...files.keys()],get:async key=>{active++;peak=Math.max(peak,active);await tick();active--;return files.get(key)||null;},put:async(key,value)=>files.set(key,value)};const engine=new SyncEngine(s.repo,cloud);await engine.sync();assert.equal(s.repo.pending().length,0);await engine.sync();assert.equal(peak,4);assert.equal(active,0);files.delete([...files.keys()].find(key=>key.startsWith('O_')));await s.run('savePlan',{input:input()});await assert.rejects(engine.sync(),{code:'CLOUD_MISSING'});assert.equal(s.repo.pending().length,1);assert.equal(active,0);}); // 破損の隠蔽や同期の重複を許しません。
test('L08 失敗した並列読込を全て終了してから次の同期を受け付ける',async t=>{const s=fixture(t);for(let n=0;n<4;n++)await s.run('savePlan',{input:input()});for(const op of s.repo.operations())s.repo.acknowledge(op.body.opId);let active=0;const engine=new SyncEngine(s.repo,{scope:s.repo.scope,get:async key=>{active++;await tick();active--;throw Object.assign(Error('合成通信失敗'),{code:'NETWORK'});}});await assert.rejects(engine.sync(),{code:'NETWORK'});assert.equal(active,0);assert.equal(engine.busy,false);assert.equal(s.repo.operations().length,4);}); // 遅れて終了する通信を次の同期へ残しません。
test('L09 版が同じ本文だけを再利用し変更・削除を毎回検知する',async()=>{let version='a',content='{}',exists=true,downloads=0,metadata=0;const client=new GraphClient({getToken:async()=> 'synthetic',fetcher:async url=>{if(url.includes('graph.microsoft.com')){metadata++;return exists?Response.json({id:'synthetic',eTag:version,size:content.length,'@microsoft.graph.downloadUrl':'https://synthetic.invalid/data'}):new Response('',{status:404});}downloads++;return new Response(content);}});assert.equal(await client.readText({id:'synthetic'}),'{}');assert.equal(await client.readText({id:'synthetic'}),'{}');assert.equal(downloads,1);content='{"changed":true}';version='b';assert.equal(await client.readText({id:'synthetic'}),content);assert.equal(downloads,2);exists=false;await assert.rejects(client.readText({id:'synthetic'}),{code:'CLOUD_MISSING'});assert.equal(metadata,4);}); // キャッシュだけでクラウド成功を判断しません。
test('L10 本文取得の通信失敗をデータ破損へ変換しない',async()=>{const cloud=new OneDriveCloud({request:async()=>({id:'synthetic'}),readText:async()=>{throw Object.assign(Error('通信未完了'),{code:'NETWORK'});}},'guest-local',null);cloud.folderId='synthetic';await assert.rejects(cloud.get('B_'+'a'.repeat(64)+'.data'),{code:'NETWORK'});}); // 再試行可能な通信障害を正しく伝えます。
test('L11 同時取得でも本文キャッシュの容量を正確に数え上限を超えない',async()=>{const raw='x'.repeat(1024*1024);const client=new GraphClient({getToken:async()=> 'synthetic',fetcher:async()=>{await tick();return new Response(raw);}});const meta=id=>({id,eTag:'stable',size:raw.length,'@microsoft.graph.downloadUrl':'https://synthetic.invalid/'+id});await Promise.all([client.readText(meta('same'),{fresh:true}),client.readText(meta('same'),{fresh:true})]);assert.equal(client.textCacheBytes,raw.length*2);for(let n=0;n<8;n++)await client.readText(meta(String(n)),{fresh:true});assert(client.textCacheBytes<=8*1024*1024);assert.equal(client.textCache.has('same'),false);assert.equal(client.textCache.size,4);}); // 背景復帰時の重複読込でもメモリを無制限に増やしません。
