import { chromium, webkit } from 'playwright'; // 旧版から本番版への更新を二つのブラウザで確認します。
import { createServer } from './serve-project.mjs'; // 同じURLを維持して配信するファイルだけを切り替えます。
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises'; // 合成プロファイルと証拠を保存します。
import { resolve, join } from 'node:path'; // 試験対象の保存領域を明確にします。
import { tmpdir } from 'node:os'; // 利用者とは無関係な試験用OSホームを作ります。
import assert from 'node:assert/strict'; // 保存前後の全記録を厳密に比較します。
const results=[];const errors=[];const output=resolve('reports/upgrade');await mkdir(output,{recursive:true}); // 更新試験を他の試験から区別して記録します。
const stop=server=>new Promise(done=>{server.close(done);server.closeAllConnections();}); // 接続を含めて配信を停止します。
async function ready(page){await page.waitForFunction(()=>document.getElementById('editorFields')&&!document.getElementById('editorFields').disabled,null,{timeout:30000});} // 本物のOPFS初期化完了を確認します。
async function backup(page){await page.getByRole('button',{name:'接続・バックアップ',exact:true}).click();const waiting=page.waitForEvent('download');await page.locator('#backup').click();const file=await waiting;return JSON.parse(await readFile(await file.path(),'utf8'));} // 実画面からDB内容と送信待ちを取得します。
for(const [name,engine]of Object.entries({chromium,webkit})){ // 各ブラウザで新しい合成端末を用意します。
  const root=await mkdtemp(join(tmpdir(),'zero-one-upgrade-'));const home=join(root,'home');await mkdir(home);const env={...process.env,HOME:home,CFFIXED_USER_HOME:home,XDG_DATA_HOME:join(home,'data'),XDG_CACHE_HOME:join(home,'cache'),XDG_CONFIG_HOME:join(home,'config')}; // OS保存領域を分離します。
  const launch=()=>engine.launchPersistentContext(join(root,'profile'),{headless:true,env}); // 更新の前後で同じプロファイルと同じOSホームを再利用します。
  let server=createServer(resolve('baseline-web'));await new Promise(done=>server.listen(0,'127.0.0.1',done));const port=server.address().port;const url=`http://127.0.0.1:${port}/zero-one-practice-lab/`;let context;let page; // 同じオリジンのまま新しいコードを提供します。
  try{ // 旧版のデータ作成から開始します。
    context=await launch();page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push({engine:name,message:error.message}));await page.goto(url);await ready(page);assert.match(await page.locator('footer').innerText(),/0\.3\.2/); // まず本当の旧版を読みます。
    await page.locator('#title').fill('更新前の計画');await page.locator('#goal').fill('旧版から保持するゴール');await page.locator('[data-field="name"]').first().fill('旧版の2対2');await page.locator('[data-field="minutes"]').first().fill('12');await page.getByRole('button',{name:'端末に保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#savedPlans [data-open]')); // 旧版で端末保存を完了します。
    await page.getByRole('button',{name:'保存した練習',exact:true}).click();await page.locator('[data-open]').first().click();await page.waitForFunction(()=>document.getElementById('detail').hidden===false);await page.locator('#reflection').fill('更新前の学び');await page.locator('#saveReflection').click();await page.waitForFunction(()=>document.getElementById('records').textContent.includes('更新前の学び')); // 関連する振り返りも保存します。
    const before=await backup(page);assert.equal(before.body.operations.length,2);assert.equal(before.body.pending.length,2);await page.waitForFunction(()=>document.getElementById('offlineStatus').textContent.includes('事前取得済み'));await context.close();context=null; // 保存確定した旧版のキャッシュとDBを残して閉じます。
    await stop(server);server=createServer();await new Promise(done=>server.listen(port,'127.0.0.1',done));context=await launch();page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push({engine:name,message:error.message}));await page.goto(url);await ready(page); // 同じURLへ戻って更新を検出します。
    await page.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();if(registration)await registration.update();}); // 旧版のキャッシュを削除せず通常の更新確認を実行します。
    await page.waitForFunction(async()=>{const registration=await navigator.serviceWorker.getRegistration();if(!registration)return false;if(registration.waiting)return true;const response=await fetch('./config.mjs');return(await response.text()).includes('1.0.0');},null,{timeout:30000}); // 新版の事前取得完了か適用完了を待ちます。
    await context.close();context=null;context=await launch();page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push({engine:name,message:error.message}));await page.goto(url);await ready(page);assert.match(await page.locator('footer').innerText(),/1\.0\.0/); // 全タブを閉じてから新しい版を開きます。
    const after=await backup(page);for(const key of ['scope','operations','objects','pending','acknowledged'])assert.deepEqual(after.body[key],before.body[key],`Upgrade changed ${key}`); // 作成時刻以外のバックアップ全体を比較します。
    await page.getByRole('button',{name:'保存した練習',exact:true}).click();assert.equal(await page.locator('.saved-card').count(),1);await page.locator('[data-open]').first().click();await page.waitForFunction(()=>document.getElementById('detail').hidden===false);assert.match(await page.locator('#records').innerText(),/更新前の学び/);await page.locator('#copyPlan').click();assert.equal(await page.locator('#title').inputValue(),'更新前の計画（コピー）');await page.locator('#savePlan').click();await page.waitForFunction(()=>document.getElementById('saveFeedback').textContent.includes('端末に保存しました')); // 旧版の計画も本番のコピー機能で使えます。
    const copied=await backup(page);assert.equal(copied.body.operations.length,3);assert.equal(copied.body.pending.length,3);for(const original of before.body.operations)assert.deepEqual(copied.body.operations.find(operation=>operation.body.opId===original.body.opId),original); // コピー後も元の計画と振り返りを変更しません。
    results.push({engine:name,status:'passed',from:'0.3.2',to:'1.0.0',sameProfile:true,sameOrigin:true,oldOperations:2,preservedPending:2,copyCreated:true});console.log('PASS',name,'version upgrade preserves exact existing records and outbox'); // 実行した移行結果を記録します。
  }catch(error){results.push({engine:name,status:'failed',error:error.message});if(page)await page.screenshot({path:join(output,name+'-failure.png'),fullPage:true}).catch(()=>{});}finally{if(context)await context.close();await stop(server);} // 失敗も残して環境を閉じます。
} // 全ブラウザの更新試験を終えます。
const passed=results.length===2&&results.every(result=>result.status==='passed')&&errors.length===0;await writeFile(join(output,'results.json'),JSON.stringify({results,errors,status:passed?'passed':'failed',physicalIPhone:false,realMicrosoft:false,clearedBrowserData:false},null,2));if(!passed)process.exitCode=1; // 未合格の更新を配信許可しません。
